{
  "hash": "d45d0c107e1aa27d94e8a8d8aa55ccae",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 3: Modelling Geography of Financial Inclusion in Tanzania with Geographically Weighted Methods \"\nauthor: \"Sei Sar Hla Kyi\"\ndate: \"14 October 2024\"\ndate-modified: \"2024-11-07\"\nexecute: \n  eval: true\n  echo: true\n  message: false\n  freeze: true\n  warning: false\n---\n\n\n# 1 Overview\n\n## 1.1 Background\n\nFinancial inclusion plays a key role in promoting equitable economic growth by enabling individuals and businesses to access essential financial services such as banking, loans, insurance, and equity products. In Tanzania, financial inclusion initiatives have become a priority in addressing the needs of underserved populations, particularly those in rural or economically disadvantaged areas. These initiatives aim to improve household incomes, reduce income inequality, and foster inclusive economic participation by providing timely and affordable access to financial products and services(United Nations Capital Development Fund \\[UNCDF\\], 2024).\n\nDespite significant progress in financial inclusion efforts, access to financial services is uneven across different geographical regions within Tanzania. Rural areas, particularly in districts with low levels of economic activity, often face greater challenges in accessing financial services compared to more urbanized districts. These spatial disparities raise important questions about the factors driving financial inclusion at the district level and how regional policies can be designed to promote more inclusive economic outcomes.\n\n## 1.2 Objectives\n\nThis analysis aims to build an explanatory model using Multiple Linear Regression as well as Geographically Weighted Regression (GWR) to identify the key factors affecting financial inclusion across districts in Tanzania. By focusing on multiple socio-economic and infrastructural variables, this study will provide insights into how these factors vary geographically and influence financial access ***at a district level***.\n\nSpecifically, the objectives are:\n\n-   **Identify Key Determinants**: Determine the primary socio-economic and infrastructural factors that influence financial inclusion.\n\n-   **Examine Regional Variation**: Explore how the effects of these factors vary across different districts, providing a localized understanding of financial inclusion.\n\n# 2 Methodology\n\nThe explanatory model will be developed first using **Multiple Linear Regression** and **Geographically Weighted Regression (GWR)**, which is a spatial extension of multiple linear regression that allows for localized variations in the relationships between predictors and the response variable—in this case, financial inclusion.\n\nThe process will follow these steps:\n\n-   **Defining dependent variable (y)**: Derive dependent variable which represents financial inclusion from the FinScope dataset.\n\n-   **Explanatory Variable Selection (x)**: Identify key predictor variables, both continuous and categorical, from the FinScope dataset. These will serve as explanatory variables in the model.\n\n-   **Model Building**: Build the explanatory model using multiple linear regression techniques, enhanced by GWR to account for geographical variations. This will allow us to evaluate the influence of each predictor on financial inclusion across different districts.\n\n-   **Model Calibration and Validation**: Calibrate the model to ensure that it effectively captures the localized relationships between financial inclusion and its determinants.\n\n-   **Spatial Visualization**: Mapping the results of the GWR model to visualize how the effects of each factor vary geographically, will highlight districts where specific variables have a stronger or weaker influence on financial inclusion.\n\n------------------------------------------------------------------------\n\n# 3 Loading R Packages\n\n::: panel-tabset\n## Packages Used\n\nThe following packages were used for this study:\n\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| Package                  | Description                                                                                                                      |\n+==========================+==================================================================================================================================+\n| olsrr                    | For creating and evaluating ordinary least squares regression models.                                                            |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| ggstatsplot              | for producing statistical visualizations that combine ggplot2 graphics with statistical results                                  |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| e1071                    | For checking skewness of variables                                                                                               |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| ggpubr                   | To create publication-ready visualizations with ggplot2 and arranging multiple plots                                             |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| sf                       | For importing, managing, and handling geospatial data                                                                            |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| sfdep                    | To analyze spatial relationships and incorporate them into regression models                                                     |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| spdep                    | For calculating spatial weights and conducting tests for spatial relationships                                                   |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| GWmodel                  | To explore spatially varying relationships between the dependent and independent variables                                       |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| tmap                     | For thematic mapping, allowing us to visualize spatial data in an intuitive and aesthetically pleasing manner                    |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| tidyverse                | For data manipulation, cleaning, and visualization                                                                               |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| gtsummary                | To create summary tables for regression results, providing a clear and concise presentation of model outputs                     |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| see                      | For visualizing model diagnostics and results                                                                                    |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| performance              | For evaluating model performance and diagnostics                                                                                 |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| datawizard               | To handle missing values, recode variables, and perform exploratory data analysis before modeling                                |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n| gtsummary                | To create publication ready summary tables                                                                                       |\n+--------------------------+----------------------------------------------------------------------------------------------------------------------------------+\n\n## Code\n\nWe will use this code to load the packages mentioned:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(st,olsrr,e1071, ggstatsplot, ggpubr, sf, spdep, sfdep, GWmodel, tmap, tidyverse, gtsummary,see,performance,datawizard,gtsummary)\n```\n:::\n\n:::\n\n------------------------------------------------------------------------\n\n# 4 Importing the Data\n\n## 4.1 The Datasets\n\nFor this analysis, we will use two primary datasets: (1) FinScope Tanzania 2023, which provides district-level data on financial inclusion, and (2) district-level boundary GIS data from the geoBoundaries portal to facilitate spatial analysis.\n\n-   **FinScope Tanzania 2023**: This dataset include comprehensive district-level data on access to financial services, covering indicators such as banking services, mobile money usage, savings, loans, and insurance. The dataset will be used to identify the key factors affecting financial inclusion and to develop the explanatory model.\n\n-   **District Boundary GIS Data**: Geographic boundary data for the districts of Tanzania, sourced from the geoBoundaries, will enable us to link the financial inclusion data to specific geographic locations for spatial analysis using GWR.\n\n## 4.2 Aspatial Data\n\nThe *FinScope* *Tanzania* dataset from 2023, was imported by using *read_csv()* package.\n\nThen, the data was prepared for analysis with the following steps:\n\n-   We extract the columns with the variables chosen which will be explained in the Variable Selection section.\n-   Rename some district names to match the boundary dataset in section 4.3.\n-   Remove columns with all missing/NA values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania <- read_csv(\"data/rawdata/FinScope_Tanzania.csv\") %>%\n  select(5, 9, 11, 13:14,16, 65:67,70:73, 82:83, 85, 95:103, 107:119, 125, \n         140, 142:151, 160:174, 177:178, 180, 183:192, 196, 215:223, \n         275:278, 294:306, 344:353, 361:372, 374:378, 395:397, 455:460, \n         495, 497, 507:529, 574:580, 591, 612, 650:651, 653, 655, 657, \n         678, 680:685, 697:698, 702:716, 718) %>%\n  mutate(dist_name = ifelse(dist_name == \"Magharibi A\", \"Magharibi\", dist_name),\n         dist_name = ifelse(dist_name == \"Magharibi B\", \"Magharibi\", dist_name),\n         dist_name = ifelse(dist_name == \"Nyang'hwale\", \"Nyanghwale\", dist_name),\n         dist_name = ifelse(dist_name == \"Wanging'ombe\", \"Wangingombe\", dist_name),\n         dist_name = ifelse(dist_name == \"Tanganyika\", \"Tanga\", dist_name))%>%\n  select(where(~ !all(is.na(.))))\n```\n:::\n\n\nWe will use ***glimpse()*** to quickly check the attributes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(tanzania)\n```\n:::\n\n\nLastly, we will save the prepared dataframe into rds format.\n\n::: panel-tabset\n## Save\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(tanzania, \"data/rds/tanzania.rds\")\n```\n:::\n\n\n## Load\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania <- read_rds(\"data/rds/tanzania.rds\")\n```\n:::\n\n:::\n\n## 4.3 Geospatial Data - Study Area\n\nThe *geo Boundaries of Tanzania* dataset, was imported by using *st_read()* package.\n\nThe dataset was prepared for analysis with the following steps:\n\n-   We note that Tanzania is in WGS 84/ UTM Zone 37S. We will use st_transform to reproject coordinate reference system to EPSG: 32737 for Tanzania.\n\n-   To perform left join with the aspatial dataset, we need a common column - districts name. Therefore, we need to change the variable, shapeName, to 'dist_name' to make it a common variable with the FinScope Tanzania dataset.\n\n-   To ensure the districts are common, some districts will be renamed from \"Arusha Urban\" to \"Arusha\" as the same way it was displayed in FinScope Tanzania dataset. Since the FinScope Tanzania dataset already have a variable that classifies if the surveyee is residing in an urban or rural area, we do not need to have a separate district with the title Urban as it falls under the same district.\n\n-   We will also remove some district names that are not present in the FinScope Tanzania dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzbounds <- st_read(dsn = \"data/rawdata/\", \n                      layer = \"geoBoundaries-TZA-ADM2\",\n                      crs=4326) %>%\n  st_transform(crs=32737) %>%\n  rename(dist_name = shapeName) %>%\n  mutate(dist_name = ifelse(dist_name == \"Arusha Urban\", \"Arusha\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Meru\", \"Arumeru\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Iringa Urban\",\"Iringa\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Bukoba Urban\", \"Bukoba\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Mpanda Urban\", \"Mpanda\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Kigoma  Urban\", \"Kigoma\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Moshi Urban\", \"Moshi\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Lindi Urban\", \"Lindi\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Musoma Urban\", \"Musoma\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Mbeya Urban\", \"Mbeya\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Babati UrbanBabati Urban\", \"Babati\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Dodoma Urban\", \"Dodoma\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Kibaha Urban\", \"Kibaha\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Morogoro Urban\", \"Morogoro\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Mtwara Urban\", \"Mtwara\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Njombe Urban\", \"Njombe\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Mtwara Urban\", \"Mtwara\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Shinyanga Urban\", \"Shinyanga\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Singida Urban\", \"Singida\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Songea Urban\", \"Songea\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Sumbawanga Urban\", \"Sumbawanga\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Tabora Urban\", \"Tabora\", dist_name))%>%\n  mutate(dist_name = ifelse(dist_name == \"Tanga Urban\", \"Tanga\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Nyang'hwale\", \"Nyanghwale\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Wanging'ombe\", \"Wangingombe\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Butiam\", \"Butiama\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Kahama Township Authority\", \"Kahama\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Kasulu Township Authority\", \"Kasulu\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Masasi  Township Authority\", \"Masasi\", dist_name)) %>%\n  mutate(dist_name = ifelse(dist_name == \"Handeni Mji\", \"Handeni\", dist_name))%>%\n  filter(!dist_name %in% c(\"Korogwe Township Authority\",\"Mafia\",\"Tunduma\",\"Korogwe\",\"Mafinga Township Authority\",\"Makambako Township Authority\")) %>%\n  select (-c(\"shapeISO\",\"shapeID\",\"shapeGroup\",\"shapeType\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-TZA-ADM2' from data source \n  `/Users/seesarhlakyi/Desktop/ssrhk/ISSS626-GAA/Take-home_Ex/Take-home_Ex03/data/rawdata' \n  using driver `ESRI Shapefile'\nSimple feature collection with 170 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 29.58953 ymin: -11.76235 xmax: 40.44473 ymax: -0.983143\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nTo ensure the study area is in the correct format, we will use ***st_crs*** to check.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(tanzbounds)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:32737 \n  wkt:\nPROJCRS[\"WGS 84 / UTM zone 37S\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"UTM zone 37S\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",39,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",10000000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"Between 36°E and 42°E, southern hemisphere between 80°S and equator, onshore and offshore. Kenya. Mozambique. Tanzania.\"],\n        BBOX[-80,36,0,42]],\n    ID[\"EPSG\",32737]]\n```\n\n\n:::\n:::\n\n\nNow that we have seen that study area is correct and names are properly changed, we will use the code chunk below to dissolve the geometries within each district into a single, unified shape using `st_union()`. By doing this, we ensure that each district has only one consolidated geometry, removing any duplicate shapes associated with that district. The `.groups = 'drop'` argument is included to simplify the output, dropping the grouping structure after summarizing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzbounds <- tanzbounds %>%\n  group_by(dist_name) %>%\n  summarise(\n    geometry = st_union(geometry),\n    .groups = 'drop'\n  )\n```\n:::\n\n\nNow we are ready to save the dataset.\n\n::: panel-tabset\n## Save\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(tanzbounds, \"data/rds/tanzbounds.rds\")\n```\n:::\n\n\n## Load\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzbounds<- read_rds(\"data/rds/tanzbounds.rds\")\n```\n:::\n\n:::\n\n------------------------------------------------------------------------\n\n# 5 The Dependent Variable\n\n## **5.1 Financial Inclusion in Tanzania**\n\nFinancial inclusion ensures that individuals and businesses have access to affordable financial products and services—spanning payments, savings, credit, and insurance—that meet their needs. It plays a crucial role in economic growth and poverty alleviation, enabling people to manage financial risks, invest in education, and improve livelihoods. According to the World Bank, financial inclusion is \"a key enabler for reducing poverty and boosting shared prosperity by providing underserved populations access to essential financial services\" (World Bank, 2023).\n\nIn Tanzania, financial inclusion is especially important for rural populations, where limited access to traditional banking infrastructure can hinder economic mobility. Many rely on informal financial services, which are often less secure and limit access to broader economic opportunities. Mobile financial services have had a transformative impact across Sub-Saharan Africa, enabling millions to participate in the financial system without needing a physical bank. In Tanzania, mobile money usage has become one of the foundation of financial inclusion, especially in rural and remote areas where mobile access is far more prevalent than traditional banking facilities (World Bank Group, 2024).\n\nHowever, access to financial services remains uneven, with notable disparities between urban and rural regions. Understanding the factors that drive financial inclusion across various communities in Tanzania is essential to improve access and support inclusive economic growth. This study aims to create a robust dependent variable reflecting financial inclusion using the FinScope dataset, capturing financial engagement through the use of mobile money services.\n\n## **5.2 Deriving The Dependent Variable - Mobile Money Usage**\n\nFor this study, mobile money usage is used as a primary indicator of financial inclusion, reflecting the importance of mobile banking in bridging the financial access gap across Tanzania. By focusing on mobile money usage as a core indicator, this study recognizes mobile banking as a primary driver of financial inclusion in Tanzania. Mobile money services enable financial transactions in remote areas, where traditional banking infrastructure is sparse. This approach reflects the integration of mobile financial services into daily life and acknowledges their role in bridging the access gap for underserved communities.\n\nThe dependent variable, Mobile Money Usage (MMU), is calculated as follows:\n\n$$MMU_i = \\frac{\\text{MobileMoneyUsers}_i}{\\text{DistrictCount}_i}$$\n\nwhere:\n\n-   $MobileMoneyUsers_i$ = Number of individuals in district i who use mobile money/banking services.\n\n-   $DistrictCount​_i$ = Number of total records in that particular district i\n\n::: callout-note\n## Dividing by the total records in each district normalizes the measure of mobile money usage across districts, allowing for a more accurate comparison between areas of different population sizes. Without normalization, districts with larger populations would disproportionately influence the results, making it harder to observe patterns in smaller or more rural areas. A normalized indicator ensures that each district's financial inclusion level is weighted by its own population, avoiding skewed results.\n:::\n\n## 5.3 Dependent Variable Implications\n\nSince *Mobile Money Users* is divided by number of records in the district, it is represented as a percentage or proportion of people that has access to mobile money in that given district.\n\n-   **Higher MMU Values:** A higher Mobile Money Usage (MMU) value indicates greater financial inclusion within a district, suggesting that a substantial proportion of individuals in that area are using mobile money services. This often reflects improved access to essential financial transactions, enabling individuals to save, transfer funds, and manage payments conveniently. With more people using mobile money, there is likely an increase in financial security and accessibility, allowing residents to participate more actively in the economy. Higher MMU values suggest that individuals in these districts are more empowered to manage financial risks, save for future needs, and potentially invest in small businesses or educational expenses, contributing to overall economic resilience.\n\n-   **Lower MMU Value:** In contrast, a lower MMU value implies limited mobile money usage within a district, often indicating lower financial inclusion. This can reflect barriers to accessing financial services, such as a lack of digital infrastructure, limited mobile network coverage, or economic challenges that prevent individuals from engaging with mobile money services. Individuals in areas with low MMU values may depend on informal financial mechanisms, which can carry higher risks, less security, and fewer opportunities for economic growth. Low MMU values suggest a need for targeted interventions to address the gaps in financial access, as these populations may be more vulnerable to financial instability, lack of savings, and limited economic opportunities, potentially hindering their capacity to break out of poverty cycles.\n\n------------------------------------------------------------------------\n\n# 6 Data Wrangling\n\nIn the development of a multiple linear regression model, the selection of appropriate variables is critical to ensuring the model's accuracy and interpretability. This section focuses on the selection of both categorical and continuous variables that will serve as predictors in our regression analysis.\n\nInitially, we will extract a preliminary set of variables based on theoretical foundations and previous empirical research from the 722 variables of FinScope Tanzania dataset.\n\n## 6.1 Categorical Variables\n\nWe will employ one-hot encoding to transform categorical variables into a format suitable for regression modeling. One-hot encoding allows us to create binary columns for each category, enabling the regression model to assess the impact of each nominal variable effectively. This approach ensures that we capture the distinct effects of categorical factors on the dependent variable while maintaining the integrity of the data.\n\nBefore we further prepare our variables (which are in the form of survey questions), we will convert the column names into a more R-friendly format using `make.names()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(tanzania) <- make.names(colnames(tanzania))\n```\n:::\n\n\nWe will use the following variables and code chunk to one-hot encode all the nominal variables as mentioned above. Some one hot encoded columns will be used to derive continuous variables as well.\n\n::: panel-tabset\n## Variables and Justification\n\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| **Variable**                                                             | **Justification for Selection**                                                                                                                                                                                                                                                                                                                                                                                                                                          | **Modification**                                                                                                 |\n+==========================================================================+==========================================================================================================================================================================================================================================================================================================================================================================================================================================================================+==================================================================================================================+\n| Cluster type                                                             | Urban-rural differences may impact access to mobile banking services due to differences in infrastructure, network coverage, and accessibility.                                                                                                                                                                                                                                                                                                                          | Encoded as two columns - 'Urban' and 'Rural'                                                                     |\n|                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |                                                                                                                  |\n|                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | If respondent indicates 'urban', this variable will be 1 and 0 for rural.                                        |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Respondent gender                                                        | Gender may influence mobile banking adoption, as social and economic factors often create differences in financial access between men and women.                                                                                                                                                                                                                                                                                                                         | Encoded as two columns - 'male' and 'female'                                                                     |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Education Background                                                     | Education level may affect the likelihood of adopting mobile banking due to varying levels of digital literacy.                                                                                                                                                                                                                                                                                                                                                          | Encoded as eight columns - 'NoFormalEducation' and 'SomePrimary' and so on                                       |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Access to Mobile Phone and Internet                                      | Directly related to mobile banking, as mobile phones are required to use mobile money and mobile banking services. Internet access can influence mobile banking adoption, particularly for smartphone-based banking services that require internet connectivity.                                                                                                                                                                                                         | Encoded as two columns - 'MobilePhone' and 'Internet' (1 if respondent has access, 0 if not).                    |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Mobile Phone's Connection                                                | The quality of mobile phone connection can impact user experience and satisfaction with mobile banking services. A poor connection may hinder transaction speed, reliability, and user confidence, thus influencing adoption rates. This variable allows for a understanding of barriers to mobile banking use.                                                                                                                                                          | Encoded as 4 columns - \"NoPhoneConnection\" \"BadPhoneConnection\" \"GoodPhoneConnection\" \"ExcellentPhoneConnection\" |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Have 2 or more devices                                                   | Ownership of multiple devices may indicate a respondent's comfort and familiarity with technology, potentially facilitating easier access to mobile banking services. This variable helps to identify tech-savvy users who may be more likely to engage with mobile banking.                                                                                                                                                                                             | Encoded as \"Own2Phones\"                                                                                          |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| If Phone is smart phone                                                  | The type of mobile device, particularly whether it is a smartphone, is significant because smartphones typically offer enhanced capabilities for mobile banking compared to basic phones. They allow access to apps and services that facilitate easier financial transactions, thus influencing mobile banking adoption.                                                                                                                                                | Encoded as \"SmartPhone                                                                                           |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Using mobile phone to pay or lottery game                                | This variable captures the extent to which respondents are already engaging with their mobile phones for financial transactions or gaming. If individuals are using their phones for payments or other financial activities, they may be more inclined to adopt mobile banking services, making this a valuable predictor.                                                                                                                                               | Encoded as \"Phone_PayforThings\" and \"Phone_LotteryGaming\"                                                        |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Main Reason the respondent don't own a phone                             | Understanding the reasons for not owning a phone provides insight into barriers that may prevent respondents from accessing mobile banking. By encoding various reasons, such as financial constraints or social restrictions, this variable can highlight the nature of mobile banking access challenges and inform targeted interventions to improve financial inclusion.                                                                                              | Encoded as 4 columns - \"NoMoneyForPhone\" \"UseSomeoneElsePhone\" \"ParentsSpouseDontAllowPhone\" \"DontNeedPhone\"     |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Financial Documents owned Bank/MFI Statements                            | Ownership of bank or MFI statements may indicate financial inclusion and readiness to adopt mobile banking.                                                                                                                                                                                                                                                                                                                                                              | Encoded as 'BankMFIStatement'                                                                                    |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| If Business is registered with government                                | Owning a registered business can increase the likelihood of using mobile banking for transactions. This variable also reflects formal economic activity, which may correlate with mobile banking usage.                                                                                                                                                                                                                                                                  | Encoded as two columns - 'BusinessRegistered_Yes' and 'BusinessRegistered_No'                                    |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Coping Mechanisms(What they did when they could not meet spending needs) | Indicates financial behavior and reliance on financial services, which can influence the adoption of mobile banking for emergency needs.                                                                                                                                                                                                                                                                                                                                 | Encoded as 10 columns - 'UsedSavings' and 'BorrowedFromBank'                                                     |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Comfort with Banks                                                       | Reflects trust in formal financial institutions, which may correlate with comfort using mobile banking services.                                                                                                                                                                                                                                                                                                                                                         | Encoded as 'ComfortableWithBank_Yes' and 'ComfortableWithBank_No'                                                |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Financial Education                                                      | Financial literacy can influence the ability to understand and trust mobile banking services.                                                                                                                                                                                                                                                                                                                                                                            | Encoded as 'ReceivedFinancialEducation_Yes' and 'ReceivedFinancialEducation_No'                                  |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Confidence in financial institutions                                     | Trust in banks and mobile money may be a predictor of mobile banking adoption.                                                                                                                                                                                                                                                                                                                                                                                           | Encoded as \"ConfidentWithBanks\" and 'ConfidentWithPensionFund' and so on                                         |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| If they have borrowed money from any financial institutions              | Access to credit services from banks or MFIs can be linked to mobile banking adoption, especially for transactions.                                                                                                                                                                                                                                                                                                                                                      | Encoded as binary columns for each financial institution type such as 'BorrowedFrom_Bank' and 'BorrowedFrom_MFI' |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| How often a respondent use the payment type for purchases                | Patterns in payment methods can reveal familiarity with financial technology and willingness to adopt mobile-based transactions.                                                                                                                                                                                                                                                                                                                                         | Encoded as binary columns for each payment type such as Used_Cash, Used_ATM, Used_CreditCard and so on.          |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Reporting problems regarding financial matters                           | Access to or barriers in resolving financial issues could impact mobile banking adoption, especially if respondents face challenges that could be solved by mobile services.                                                                                                                                                                                                                                                                                             | Encoded as binary columns such as 'Do_Not_Know_Where_To_Go' and 'Do_Not_Think_They_Care'                         |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Confidence and Trust in Insurance Companies                              | Confidence in formal financial institutions like insurance companies can influence openness to adopting other formal services, including mobile banking.                                                                                                                                                                                                                                                                                                                 | Encoded as relevant indicators such as Trust_Insurance_Companies                                                 |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Issues Accessing Mobile/Online Financial Products                        | These barriers are directly relevant to mobile banking, as access issues like network failure and agent availability can significantly impact the usability and reliability of mobile money services. If respondents frequently experience these problems, they may be less likely to adopt or rely on mobile banking. Understanding these barriers helps identify structural challenges in mobile banking infrastructure that could hinder financial inclusion efforts. | Encoded as Network_Failure and Agent_Absent and so on                                                            |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n| Access and relationship with moneylender                                 | Engagement with informal lenders may indicate a lack of access to formal banking, which mobile banking could address.                                                                                                                                                                                                                                                                                                                                                    | Encoded as Moneylender_Access and Moneylender_TreatsWell                                                         |\n+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_onehotencoded<- tanzania %>%\n  mutate(\n    Urban = ifelse(`Cluster.type` == \"Urban\", 1, 0),\n    Rural = ifelse(`Cluster.type` == \"Rural\", 1, 0)) %>%\n  mutate(\n    Male = ifelse(`C9..Respondent.gender.Interviewer.to.observe` == \"Male\", 1, 0), \n    Female = ifelse(`C9..Respondent.gender.Interviewer.to.observe` == \"Female\", 1, 0))%>% \n  mutate(\n    NoFormalEducation = ifelse(`C11..Highest.level.of.education.completed..Can.read.out` == \"No formal education\", 1, 0),\n    SomePrimary = ifelse(`C11..Highest.level.of.education.completed..Can.read.out` == \"Some primary\", 1, 0),\n    PrimaryCompleted = ifelse(`C11..Highest.level.of.education.completed..Can.read.out` == \"Primary completed\", 1, 0),\n    PostPrimaryTechnicalTraining = ifelse(`C11..Highest.level.of.education.completed..Can.read.out` == \"Post primary technical training\", 1, 0),\n    SomeSecondary = ifelse(`C11..Highest.level.of.education.completed..Can.read.out` == \"Some secondary\", 1, 0),\n    SecondaryCompleted_OLevel = ifelse(`C11..Highest.level.of.education.completed..Can.read.out` == \"Secondary competed-O level\", 1, 0),\n    SomeUniversityOrHigherEducation = ifelse(`C11..Highest.level.of.education.completed..Can.read.out` == \"Some University or other higher education\", 1, 0),\n    UniversityOrHigherEducationCompleted = ifelse(`C11..Highest.level.of.education.completed..Can.read.out` == \"University or higher education completed\", 1, 0))%>%\n  mutate(\n    MobilePhone = ifelse(`C23..Which.of.the.following.do.you.have.access..to..Mobile.phone` == \"Yes\", 1, 0),\n    Internet = ifelse(`C23..Which.of.the.following.do.you.have.access..to..Internet` == \"Yes\", 1, 0),\n    NoPhoneConnection = ifelse (`C24.3.How.good.is.the.mobile.phone.connection.from.your.home..would.you.say.that...` == \"There is no connection\",1,0),\nBadPhoneConnection = ifelse (`C24.3.How.good.is.the.mobile.phone.connection.from.your.home..would.you.say.that...` == \"It is bad – calls rarely connect, calls often drop, it is hard to hear what people say\",1,0),\nGoodPhoneConnection = ifelse (`C24.3.How.good.is.the.mobile.phone.connection.from.your.home..would.you.say.that...` == \"It is good – calls sometimes drop, sound is often poor, although you can still understand what people say\",1,0),\nExcellentPhoneConnection = ifelse (`C24.3.How.good.is.the.mobile.phone.connection.from.your.home..would.you.say.that...` == \"It is excellent – calls mostly connect, sound is excellent\",1,0)) %>%\n  mutate(\n    Own2MobilePhone = ifelse(`C24.1..Do.you.personally.own.a.mobile.phone.`== \"2\",1,0),\n    SmartPhone= ifelse(`C25..Is.your.phone.a.smart.phone.or.a.simple.mobile.phone..Smart.phone`== \"Yes\",1,0),\n    Phone_PayforThings = ifelse(`C25X2..Which.of.these.things.are.you.using..apps.on.your.phone.to.do...Pay.for.things` == \"Yes\",1,0),\n    Phone_LotteryGaming = ifelse(`C25X2..Which.of.these.things.are.you.using..apps.on.your.phone.to.do...Lottery..gaming` == \"Yes\",1,0),\n    NoMoneyForPhone = ifelse(`C26..What.is.the..main.reason..why.don.t.you.have.a.mobile.phone.` == \"Don’t have enough money/expensive to buy the handset\",1,0),\n    UseSomeoneElsePhone = ifelse(`C26..What.is.the..main.reason..why.don.t.you.have.a.mobile.phone.` == \"Use someone else’s phone\",1,0),\n    DontNeedPhone = ifelse(`C26..What.is.the..main.reason..why.don.t.you.have.a.mobile.phone.` == \"Don’t want to / Don’t need it\",1,0),\n    ParentSpouseDontAllowPhone = ifelse(`C26..What.is.the..main.reason..why.don.t.you.have.a.mobile.phone.` == \"Parents/spouse/other don’t want/allow me to\",1,0))%>%\n  mutate(\n    BankMFIStatement = ifelse(`C27..Which.of.the.following.documents.do.you.currently.have.in.your.name..Bank.MFI.Statement`== \"Yes\",1,0))%>%\n  mutate(\n    BusinessRegistered_Yes = ifelse(`X6.4a.Is.your.business.registered.with.any.government.authority.` == \"Yes\", 1, 0),\n    BusinessRegistered_No = ifelse(`X6.4a.Is.your.business.registered.with.any.government.authority.` == \"No\", 1, 0),\n  ) %>%\n  mutate(\n    Advice_HouseholdMember = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..A.household.member` == \"Yes\", 1, 0),\n    Advice_FamilyMember = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Another.family.member` == \"Yes\", 1, 0),\n    Advice_Employer = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Employer` == \"Yes\", 1, 0),\n    Advice_Bank = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Bank` == \"Yes\", 1, 0),\n    Advice_Microfinance = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Microfinance.institution` == \"Yes\", 1, 0),\n    Advice_SACCOS = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Savings.and.credit.cooperative..SACCOS.` == \"Yes\", 1, 0),\n    Advice_FinancialAdvisor = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Financial.advisor` == \"Yes\", 1, 0),\n    Advice_FarmersAssociation = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Farmers.association` == \"Yes\", 1, 0),\n    Advice_BusinessAssociation = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Business.association` == \"Yes\", 1, 0),\n    Advice_SavingsGroup = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Savings.group` == \"Yes\", 1, 0),\n    Advice_Moneylender = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Moneylender.in.community` == \"Yes\", 1, 0),\n    Advice_GovernmentOfficial = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Government.official` == \"Yes\", 1, 0),\n    Advice_VillageElder = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Village.elder.elder` == \"Yes\", 1, 0),\n    Advice_OtherSpecify = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..Other.specify` == \"Yes\", 1, 0),\n    Advice_NoOne = ifelse(`E.3.3..Who.do.you.talk.with.for.advice.about.money.matters..I.do.not.speak.with.anyone` == \"Yes\", 1, 0)\n  )%>%\n  mutate(\n    UsedSavings = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Used.savings` == \"Yes\", 1, 0),\n    BorrowedFromBank = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Borrowed.from.a.bank.MFI.SACCO` == \"Yes\", 1, 0),\n    BorrowedThroughMM = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Borrowed.money.through.MM` == \"Yes\", 1, 0),\n    BorrowedFromMoneyLender = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Borrowed.from.money.lender` == \"Yes\", 1, 0),\n    BorrowedFromFriendFamily = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Borrowed.from.friend.family.community` == \"Yes\", 1, 0),\n    GotAssistanceFromFamily = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Got.assistance.from.family.friends.community..that.I.did.not.need.to.repay.` == \"Yes\", 1, 0),\n    SoldLivestock = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Sold.livestock` == \"Yes\", 1, 0),\n    CutSpending = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Cut.spending` == \"Yes\", 1, 0),\n    WorkedMore = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Worked.more` == \"Yes\", 1, 0),\n    Others_CouldntMeetNeeds = ifelse(`E.7.N.1..Last.12.months...what.did.you.do.when.you.couldn.t.meet.your.regular.spending.needs._Others` == \"Yes\", 1, 0)\n  )%>%\n  mutate(\n    ComfortableWithBank_Yes = ifelse(`E.5.1..You.feel.comfortable.to.go.into.a.bank.or.another.financial.institution` == \"TRUE\", 1, 0),\n    ComfortableWithBank_No = ifelse(`E.5.1..You.feel.comfortable.to.go.into.a.bank.or.another.financial.institution` == \"FALSE\", 1, 0), ReceivedFinancialEducation_Yes = ifelse(`E.5.2..You.have.received.some.financial.education.in.your.life` == \"TRUE\", 1, 0),\n    ReceivedFinancialEducation_No = ifelse(`E.5.2..You.have.received.some.financial.education.in.your.life` == \"FALSE\", 1, 0),\n    ConfidentWithBanks = ifelse(`F.3.2.1..I.will.read.for.you.a.list.of.institutions..and.pease.tell.me.which.you.feel.confident.with.SAVINGS.your.money.with._Banks` == \"Yes\", 1, 0),\n    ConfidentWithMFIs = ifelse(`F.3.2.1..I.will.read.for.you.a.list.of.institutions..and.pease.tell.me.which.you.feel.confident.with.SAVINGS.your.money.with._MFIs` == \"Yes\", 1, 0),\n    ConfidentWithSACCOs = ifelse(`F.3.2.1..I.will.read.for.you.a.list.of.institutions..and.pease.tell.me.which.you.feel.confident.with.SAVINGS.your.money.with._SACCOs` == \"Yes\", 1, 0),\n    ConfidentWithMobileMoney = ifelse(`F.3.2.1..I.will.read.for.you.a.list.of.institutions..and.pease.tell.me.which.you.feel.confident.with.SAVINGS.your.money.with._Mobile.money.operators` == \"Yes\", 1, 0),\n    ConfidentWithPensionFund = ifelse(`F.3.2.1..I.will.read.for.you.a.list.of.institutions..and.pease.tell.me.which.you.feel.confident.with.SAVINGS.your.money.with._Pension.fund` == \"Yes\", 1, 0),\n    ConfidentWithSavingsGroups = ifelse(`F.3.2.1..I.will.read.for.you.a.list.of.institutions..and.pease.tell.me.which.you.feel.confident.with.SAVINGS.your.money.with._Savings.groups.CMGs` == \"Yes\", 1, 0),\n    ConfidentWithFamilyFriends = ifelse(`F.3.2.1..I.will.read.for.you.a.list.of.institutions..and.pease.tell.me.which.you.feel.confident.with.SAVINGS.your.money.with._Family.friends` == \"Yes\", 1, 0),\n    ConfidentWithUTTs = ifelse(`F.3.2.1..I.will.read.for.you.a.list.of.institutions..and.pease.tell.me.which.you.feel.confident.with.SAVINGS.your.money.with._UTTs` == \"Yes\", 1, 0),\n    BorrowedFrom_Bank = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..Bank` == \"Yes\", 1, 0),\n    BorrowedFrom_MFI = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..Microfinance.institution.such.as` == \"Yes\", 1, 0),\n    BorrowedFrom_SACCO = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..SACCOS` == \"Yes\", 1, 0),\n    BorrowedFrom_MobileMoney = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..A.mobile.money.service.provider` == \"Yes\", 1, 0),\n    BorrowedFrom_PensionFund = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..A.pension.fund` == \"Yes\", 1, 0),\n    BorrowedFrom_Employer = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..Your.employer` == \"Yes\", 1, 0),\n    BorrowedFrom_Family_PayBack = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..Family.friends.that.you.had.to.pay.back` == \"Yes\", 1, 0),\n    BorrowedFrom_Family_NoPayBack = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..Family.friends.that.you.did.not.have.to.pay.back` == \"Yes\", 1, 0),\n    BorrowedFrom_SavingsGroup = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..Savings.group` == \"Yes\", 1, 0),\n    BorrowedFrom_CommunityLender = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..Someone.in.the.community.who.lend` == \"Yes\", 1, 0),\n    BorrowedFrom_OtherSource = ifelse(`G.5.2.Did.you.borrow.money.from.the.following..Did.you.borrow.money.from.another.source` == \"Yes\", 1, 0),\n    Used_Cash = ifelse(`X2.1.In.the.past.12.months..how.often.did.you.use.the.Cash.for.purchases.of.goods` == \"Yes\", 1, 0),\n    Used_ATM_DebitCard = ifelse(`X2.2.In.the.past.12.months..how.often.did.you.use.the.ATM...Debit.card.for.purchases.of.goods` == \"Yes\", 1, 0),\n    Used_Cash = ifelse(`X2.1.In.the.past.12.months..how.often.did.you.use.the.Cash.for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_ATM_DebitCard = ifelse(`X2.2.In.the.past.12.months..how.often.did.you.use.the.ATM...Debit.card.for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_CreditCard = ifelse(`X2.3.In.the.past.12.months..how.often.did.you.use.the.Credit.card.for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_BankTransfer = ifelse(`X2.4.In.the.past.12.months..how.often.did.you.use.the.Bank.transfer.for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_MobileMoney = ifelse(`X2.5.In.the.past.12.months..how.often.did.you.use.the.Mobile.money.for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_Cryptocurrency = ifelse(`X2.6.In.the.past.12.months..how.often.did.you.use.the.Cryptocurrency.for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_QR_Code = ifelse(`X3.1.In.the.past.12.months..how.often.did.you.use.the.QR.code..for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_POS = ifelse(`X3.2.In.the.past.12.months..how.often.did.you.use.the.POS.for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_LipaNamba = ifelse(`X3.3.In.the.past.12.months..how.often.did.you.use.the.Lipa.Namba.for.purchases.of.goods` == \"Never\", 0, 1),\nUsed_AZAMPay = ifelse(`X3.4.In.the.past.12.months..how.often.did.you.use.the.AZAM.Pay.for.purchases.of.goods` == \"Never\", 0, 1),\n    Do_Not_Know_Where_To_Go = ifelse(`J1.7.Why.don.t.you.report.problems..I.do.not.know.where.to.go` == \"Yes\", 1, 0),\n    Places_Not_In_My_Area = ifelse(`J1.7.Why.don.t.you.report.problems..The.places.are.not.in.my.area` == \"Yes\", 1, 0),\n    Do_Not_Think_They_Care = ifelse(`J1.7.Why.don.t.you.report.problems..I.do.not.think.they.care.about` == \"Yes\", 1, 0),\n     Trust_Insurance_Companies = ifelse(`X1.3.Please.tell.me.which.of.the.following.you.is.true.for.you...You.trust.insurance.companies.to.pay.out.when.something.does.go.wrong` == \"Yes\", 1, 0),\n    Insurance_Good_Idea = ifelse(`X1.3.Please.tell.me.which.of.the.following.you.is.true.for.you...Insurance.is.a.good.idea.for.everyone` == \"Yes\", 1, 0),\n    Have_Insurance_Cover = ifelse(`X2.Do.you.have.insurance.cover.` == \"Yes\", 1, 0),\n    Network_Failure = ifelse(`X10.1.In.the.past.12.months.have.you.experienced.any.of.the.following.when.you.wanted.to.use.mobile.money._Network.failure` == \"Yes\", 1, 0),\n    Agent_Absent = ifelse(`X10.1.In.the.past.12.months.have.you.experienced.any.of.the.following.when.you.wanted.to.use.mobile.money._Agent.absent.not.available` == \"Yes\", 1, 0),\n    Agent_No_Cash_Float = ifelse(`X10.1.In.the.past.12.months.have.you.experienced.any.of.the.following.when.you.wanted.to.use.mobile.money._Agent.didn.t.have.enough.cash.float` == \"Yes\", 1, 0),\n    Agent_Overcharged = ifelse(`X10.1.In.the.past.12.months.have.you.experienced.any.of.the.following.when.you.wanted.to.use.mobile.money._Agent.overcharged.for.transactions` == \"Yes\", 1, 0),\n    Lost_Money = ifelse(`X10.1.In.the.past.12.months.have.you.experienced.any.of.the.following.when.you.wanted.to.use.mobile.money._Lost.money` == \"Yes\", 1, 0),\n    Agent_Requested_PIN = ifelse(`X10.1.In.the.past.12.months.have.you.experienced.any.of.the.following.when.you.wanted.to.use.mobile.money._Agent.wanted.you.to.reveal.your.PIN.number` == \"Yes\", 1, 0),\n    Other_Problems = ifelse(`X10.1.In.the.past.12.months.have.you.experienced.any.of.the.following.when.you.wanted.to.use.mobile.money._Any.other.problem` == \"Yes\", 1, 0),\n    Moneylender_Access = ifelse(`X4b.Please.tell.me.which.of.the.following.statements.you.agree.with..You.can.use.or.access.your.moneylender.whenever.you.need.to` == \"Yes\", 1, 0),\n    Moneylender_TreatsWell = ifelse(`X4b.Please.tell.me.which.of.the.following.statements.you.agree.with..Your.moneylender.always.treats.you.well` == \"Yes\", 1, 0),\n    Moneylender_InfoClear = ifelse(`X4b.Please.tell.me.which.of.the.following.statements.you.agree.with..Before.you.took.out.a.loan.with.your.moneylender..you.got.as.much.info.as.needed.and.it.was.easy.to.understand` == \"Yes\", 1, 0),\n    Moneylender_NeedsMet = ifelse(`X4b.Please.tell.me.which.of.the.following.statements.you.agree.with..The.products.and.services.offered.by.your.moneylender.meets.your.financial.needs` == \"Yes\", 1, 0),\n    Moneylender_FeesReasonable = ifelse(`X4b.Please.tell.me.which.of.the.following.statements.you.agree.with..Your.moneylender.s.fees.and.charges.are.reasonable` == \"Yes\", 1, 0),\n    Moneylender_CustomerSupport = ifelse(`X4b.Please.tell.me.which.of.the.following.statements.you.agree.with..You.are.satisfied.with.your.moneylender.s.customer.support` == \"Yes\", 1, 0),\nFORM_INVESTMENTS = ifelse(FORM_INVESTMENTS == \"FORM_INVESTMENTS\", 1, 0),\n    PayingBack_Yes = ifelse(`G.2.4..Have.you..in.the.past.12.months..been.paying.back.money.that.you.borrowed.` == \"Yes\", 1, 0),\n    PayingBack_No = ifelse(`G.2.4..Have.you..in.the.past.12.months..been.paying.back.money.that.you.borrowed.` == \"No\", 1, 0),\n    MobileMoney = ifelse(Mobile.money == \"MM\", 1, 0)\n  )  \n```\n:::\n\n:::\n\nWe will ensure these newly encoded variables are numeric format and all NA will be replaced by 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_onehotencoded <- tanzania_onehotencoded %>%\n  mutate_at(vars(204:312), ~ as.numeric(replace_na(., 0)))\n```\n:::\n\n\nNow, we will aggregate the one hot encoded variables to group by district since our analysis on district level and not on each respondent level.\n\nThe following table explains the code chunk below and how the variables will be grouped.\n\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| **Variable**                                                              | **District Level Transformation (Group by)**                                                                                                                                                                                                                                                                                                                                        |\n+===========================================================================+=====================================================================================================================================================================================================================================================================================================================================================================================+\n| Cluster type                                                              | Percentage of Urban for each district ( to reduce multicollinearity in regression as Rural and Urban will add up to 1, we will only choose one out of the two)                                                                                                                                                                                                                      |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Respondent gender                                                         | Ratio of Male vs Female (1: equal number, \\<1: less Male than Female, \\>1: More Male than Female, 0: No male in this district)                                                                                                                                                                                                                                                      |\n|                                                                           |                                                                                                                                                                                                                                                                                                                                                                                     |\n|                                                                           | \\*To reduce multicollinearity, we will not be using the same denominator, number of total respondents in district, as we did in Cluster type.                                                                                                                                                                                                                                       |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Education Background                                                      | Ratio of poeple with No Formal Education vs other categories of education fromPrimary \\~ University (1: equal number, \\<1: less people with no formal education than people with some formal education, \\>1: More people with no formal education than people with some formal education, 0: All respondents have some kind of education in this district; there is no one without) |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Access to Mobile Phone and Internet                                       | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Mobile Phone's Connection                                                 | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Have 2 or more devices                                                    | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| If Phone is smart phone                                                   | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Using mobile phone to pay or lottery game                                 | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Financial Documents owned                                                 | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| If Business is registered with government                                 | Ratio of Registered Businesses vs Not Registered (1: equal number, \\<1: less Registered Businesses than Not, \\>1: More Registered Businesses than Not, 0: No registered business in this district)                                                                                                                                                                                  |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Coping Mechanisms( What they did when they could not meet spending needs) | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Comfort with banks                                                        | Ratio of People comfortable with Banks vs Not comfortable (1: equal number, \\<1: less people comfortable with banks than Not, \\>1: More people comfortable with banks than Not, 0: No one is comfortable with banks in this district)                                                                                                                                               |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Financial Education                                                       | Ratio of People that received financial education vs No financial education (1: equal number, \\<1: less people received financial edcation than Not, \\>1: More people received financial education than Not, 0: No one received financial education in this district)                                                                                                               |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Confidence in financial institutions                                      | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| If they have borrowed money from any financial institutions               | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| How often a respondent use the payment type for purchases                 | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Reporting problems regarding financial matters                            | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Confidence and Trust in Insurance Companies                               | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Insurance ownership                                                       | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Issues accessing mobile/online financial products                         | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Access and relationship with moneylender                                  | Sum/Count of each category for each district                                                                                                                                                                                                                                                                                                                                        |\n+---------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncategorical_var <- tanzania_onehotencoded %>%\n  group_by(dist_name) %>%\n  summarise(\n    district_count = n(),  # total records in each district\n    Urban = ifelse(\n      (sum(Urban, na.rm = TRUE) + sum(Rural, na.rm = TRUE)) == 0,\n      0,\n      sum(Urban, na.rm = TRUE) / (sum(Urban, na.rm = TRUE) + sum(Rural, na.rm = TRUE))\n    ), # Percentage of Urban\n    Male_Female_Ratio =sum(Male, na.rm = TRUE) / sum(Female, na.rm = TRUE), # Ratio of Male to Female in each district\n    Registered_YesNo_Ratio =sum(BusinessRegistered_Yes, na.rm = TRUE) / sum(BusinessRegistered_No, na.rm = TRUE)\n, # Ratio of Registered Businesses vs Not Registered\n    ComfortableBank_YesNo_Ratio =sum(ComfortableWithBank_Yes, na.rm = TRUE) / sum(ComfortableWithBank_No, na.rm = TRUE), # Ratio of Comfortable with Bank vs Not Comfortable\nPayingBack_YesNo_Ratio =sum(PayingBack_Yes, na.rm = TRUE) / sum(PayingBack_No, na.rm = TRUE), # Ratio of People that currently owes money vs people that does not\n     FinancialEducation_YesNo_Ratio =sum(ReceivedFinancialEducation_Yes, na.rm = TRUE) / sum(ReceivedFinancialEducation_No, na.rm = TRUE), # Ratio of People Received Financial Education vs No Financial Education\n    NoEdu_SomeEdu = sum(NoFormalEducation, na.rm = TRUE) / (sum(SomePrimary, na.rm = TRUE) +sum(PrimaryCompleted, na.rm = TRUE) + sum(PostPrimaryTechnicalTraining, na.rm = TRUE) + sum(SomeSecondary, na.rm = TRUE) + sum(SecondaryCompleted_OLevel, na.rm = TRUE) + sum(SomeUniversityOrHigherEducation, na.rm = TRUE) + sum(UniversityOrHigherEducationCompleted, na.rm = TRUE)), #Ratio of People Received No Education vs Some Education\n    MobilePhone = sum(MobilePhone, na.rm = TRUE), \n    Internet = sum(Internet, na.rm = TRUE),\nNoPhoneConnection_Some= sum(NoPhoneConnection, na.rm = TRUE) / (sum(BadPhoneConnection, na.rm = TRUE) +sum(GoodPhoneConnection, na.rm = TRUE)+sum(ExcellentPhoneConnection, na.rm = TRUE)), #Ratio of People with No connection at all vs Some \nOwn2MobilePhone = sum(Own2MobilePhone, na.rm = TRUE),\nNoPhoneConnection= sum(NoPhoneConnection, na.rm = TRUE),\nBadPhoneConnection= sum(BadPhoneConnection, na.rm = TRUE),\nGoodPhoneConnection= sum(GoodPhoneConnection, na.rm = TRUE),\nExcellentPhoneConnection= sum(ExcellentPhoneConnection, na.rm = TRUE),\nSmartPhone = sum(SmartPhone, na.rm = TRUE),\nPhone_PayforThings = sum(Phone_PayforThings, na.rm = TRUE),\nPhone_LotteryGaming = sum(Phone_LotteryGaming, na.rm = TRUE),\nNoMoneyForPhone = sum(NoMoneyForPhone, na.rm = TRUE),\nUseSomeoneElsePhone = sum(UseSomeoneElsePhone, na.rm = TRUE),\nDontNeedPhone = sum(DontNeedPhone, na.rm = TRUE),\nParentSpouseDontAllowPhone = sum(ParentSpouseDontAllowPhone, na.rm = TRUE),\n    BankMFIStatement = sum(BankMFIStatement, na.rm = TRUE),\n    ConfidentWithBanks = sum(ConfidentWithBanks, na.rm = TRUE),\n    ConfidentWithMFIs = sum(ConfidentWithMFIs, na.rm = TRUE),\n    ConfidentWithSACCOs = sum(ConfidentWithSACCOs, na.rm = TRUE),\n    ConfidentWithMobileMoney = sum(ConfidentWithMobileMoney, na.rm = TRUE),\n    ConfidentWithPensionFund = sum(ConfidentWithPensionFund, na.rm = TRUE),\n    ConfidentWithSavingsGroups = sum(ConfidentWithSavingsGroups, na.rm = TRUE),\n    ConfidentWithFamilyFriends = sum(ConfidentWithFamilyFriends, na.rm = TRUE),\n    ConfidentWithUTTs = sum(ConfidentWithUTTs, na.rm = TRUE),\n    BorrowedFrom_Bank = sum(BorrowedFrom_Bank, na.rm = TRUE),\n    BorrowedFrom_MFI = sum(BorrowedFrom_MFI, na.rm = TRUE),\n    BorrowedFrom_SACCO = sum(BorrowedFrom_SACCO, na.rm = TRUE),\n    BorrowedFrom_MobileMoney = sum(BorrowedFrom_MobileMoney, na.rm = TRUE),\n    BorrowedFrom_PensionFund = sum(BorrowedFrom_PensionFund, na.rm = TRUE),\n    BorrowedFrom_Employer = sum(BorrowedFrom_Employer, na.rm = TRUE),\n    BorrowedFrom_Family_PayBack = sum(BorrowedFrom_Family_PayBack, na.rm = TRUE),\n    BorrowedFrom_Family_NoPayBack = sum(BorrowedFrom_Family_NoPayBack, na.rm = TRUE),\n    BorrowedFrom_SavingsGroup = sum(BorrowedFrom_SavingsGroup, na.rm = TRUE),\n    BorrowedFrom_CommunityLender = sum(BorrowedFrom_CommunityLender, na.rm = TRUE),\n    BorrowedFrom_OtherSource = sum(BorrowedFrom_OtherSource, na.rm = TRUE),\nBorrowedFrom_MoneyLender = sum(BorrowedFromMoneyLender, na.rm = TRUE),\n    BorrowedFrom_FriendFamily = sum(BorrowedFromFriendFamily, na.rm = TRUE),\n    GotAssistanceFrom_Family = sum(GotAssistanceFromFamily, na.rm = TRUE),\n    SoldLivestock = sum(SoldLivestock, na.rm = TRUE),\n    CutSpending = sum(CutSpending, na.rm = TRUE),\n    WorkedMore = sum(WorkedMore, na.rm = TRUE),\n  Advice_HouseholdMember = sum(Advice_HouseholdMember, na.rm = TRUE),\n    Advice_FamilyMember = sum(Advice_FamilyMember, na.rm = TRUE),\n    Advice_Employer = sum(Advice_Employer, na.rm = TRUE),\n    Advice_Bank = sum(Advice_Bank, na.rm = TRUE),\n    Advice_Microfinance = sum(Advice_Microfinance, na.rm = TRUE),\n    Advice_SACCOS = sum(Advice_SACCOS, na.rm = TRUE),\n    Advice_FinancialAdvisor = sum(Advice_FinancialAdvisor, na.rm = TRUE),\n    Advice_FarmersAssociation = sum(Advice_FarmersAssociation, na.rm = TRUE),\n    Advice_BusinessAssociation = sum(Advice_BusinessAssociation, na.rm = TRUE),\n    Advice_SavingsGroup = sum(Advice_SavingsGroup, na.rm = TRUE),\n    Advice_Moneylender = sum(Advice_Moneylender, na.rm = TRUE),\n    Advice_GovernmentOfficial = sum(Advice_GovernmentOfficial, na.rm = TRUE),\n    Advice_VillageElder = sum(Advice_VillageElder, na.rm = TRUE),\n    Advice_OtherSpecify = sum(Advice_OtherSpecify, na.rm = TRUE),\n    Advice_NoOne = sum(Advice_NoOne, na.rm = TRUE),\nUsedSavings = sum(UsedSavings, na.rm = TRUE),\n    Others_CouldntMeetNeeds = sum(Others_CouldntMeetNeeds, na.rm = TRUE),\n    Used_Cash = sum(Used_Cash, na.rm = TRUE),\n    Used_ATM_DebitCard = sum(Used_ATM_DebitCard, na.rm = TRUE),\n    Used_CreditCard = sum(Used_CreditCard, na.rm = TRUE),\n    Used_MobileMoney = sum(Used_MobileMoney, na.rm = TRUE),\n    Used_Cryptocurrency = sum(Used_Cryptocurrency, na.rm = TRUE),\n    Used_QR_Code = sum(Used_QR_Code, na.rm = TRUE),\n    Used_POS = sum(Used_POS, na.rm = TRUE),\n    Used_LipaNamba = sum(Used_LipaNamba, na.rm = TRUE),\n    Used_AZAMPay = sum(Used_AZAMPay, na.rm = TRUE),\n    Do_Not_Know_Where_To_Go = sum(Do_Not_Know_Where_To_Go, na.rm = TRUE),\n    Places_Not_In_My_Area = sum(Places_Not_In_My_Area, na.rm = TRUE),\n    Do_Not_Think_They_Care = sum(Do_Not_Think_They_Care, na.rm = TRUE),\n    Trust_Insurance_Companies = sum(Trust_Insurance_Companies, na.rm = TRUE),\n    Insurance_Good_Idea = sum(Insurance_Good_Idea, na.rm = TRUE),\n    Have_Insurance_Cover = sum(Have_Insurance_Cover,na.rm = TRUE),\n    Network_FailureMM = sum(Network_Failure, na.rm = TRUE),\n    Agent_AbsentMM = sum(Agent_Absent, na.rm = TRUE),\n    Agent_No_Cash_FloatMM = sum(Agent_No_Cash_Float, na.rm = TRUE),\n    Agent_OverchargedMM = sum(Agent_Overcharged, na.rm = TRUE),\n    Lost_MoneyMM = sum(Lost_Money, na.rm = TRUE),\n    Agent_Requested_PINMM = sum(Agent_Requested_PIN, na.rm = TRUE),\n    Other_ProblemsMM = sum(Other_Problems, na.rm = TRUE),\n    Moneylender_Access = sum(Moneylender_Access, na.rm = TRUE),\n    Moneylender_TreatsWell = sum(Moneylender_TreatsWell, na.rm = TRUE),\n    Moneylender_InfoClear = sum(Moneylender_InfoClear, na.rm = TRUE),\n    Moneylender_NeedsMet = sum(Moneylender_NeedsMet, na.rm = TRUE),\n    Moneylender_FeesReasonable = sum(Moneylender_FeesReasonable, na.rm = TRUE),\n    Moneylender_CustomerSupport = sum(Moneylender_CustomerSupport, na.rm = TRUE),\nFORM_INVESTMENTS = sum(FORM_INVESTMENTS, na.rm = TRUE),\nMobileMoney = sum(MobileMoney,na.rm = TRUE)\n  )\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n## 6.2 Continuous Variables\n\nThe following are the chosen continuous variables for our initial model:\n\n+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+\n| **Variable**                  | **Justification for Selection**                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | District Level (Group by)                                       |\n+===============================+======================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================+=================================================================+\n| Age                           | Age is a critical demographic variable that often influences various socio-economic outcomes. It can affect financial behaviors, access to resources, and the types of assistance individuals might require.                                                                                                                                                                                                                                                                                         | Mean Age at each district                                       |\n+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+\n| Amount Owed                   | The amount of debt an individual holds may influence their adoption of mobile banking, as those with higher financial obligations may seek convenient options for managing and repaying debt. Mobile money services can facilitate easier debt payments and transfers, making mobile banking particularly valuable for financially burdened individuals. Understanding average debt levels in each district can reveal areas where mobile banking may have higher utility due to financial distress. | Mean Amount Owed at each district                               |\n+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+\n| Money Spent on Betting        | Spending on betting, often linked with financial behaviors that may involve digital payments, has a connection to mobile money services, which are frequently used in betting transactions. Understanding the average betting expenditure can provide insights into districts where mobile money usage is integrated into daily financial activities.                                                                                                                                                | Mean Money Spent on Betting at each district                    |\n+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+\n\nFor these three continuous variables, we will prepare the data in the following steps:\n\n-   Rename the variables\n\n-   Replace NA values with 0, Except for Age\n\n    ::: callout-note\n    ## Age 0 does not make logical sense, Therefore the missing ones will be replaced with the mean_age of the whole dataset excluding NA values which is 39\n    :::\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    mean_age <- mean(tanzania$Age, na.rm = TRUE)\n    mean_age\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    \n    ```\n    [1] 39.67635\n    ```\n    \n    \n    :::\n    :::\n\n\n-   Ensure they are in numeric format\n\n-   Derive the district level variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania <- tanzania %>%\n  mutate(\n    Age = as.numeric(replace_na(as.numeric(as.character(Age)), 39)),\n    Amount_Owed = as.numeric(replace_na(as.numeric(as.character(G.2.6..Approximately.how.much.money.do.you.owe..in.TZS)), 0)),\n    Amount_Betting = as.numeric(replace_na(as.numeric(as.character(X17c.On.average..how.much.do.you.spend.on.betting.in.a.month.)), 0)))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncontinuous_var <- tanzania %>%\n  group_by(dist_name) %>%\n  summarise(\n    Mean_Age = mean(Age, na.rm = TRUE), \n    Mean_AmountOwed = mean(Amount_Owed, na.rm = TRUE),\n    Mean_AmountBetting = mean(Amount_Betting, na.rm = TRUE),\n  )\n```\n:::\n\n\nWe will use ***left_join*** to combine the categorical and continuous variable dataframe to derive the final dataframe, using the common column ***dist_name***.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_combined <- categorical_var %>%\n  left_join(continuous_var, by = \"dist_name\")\n```\n:::\n\n\n## 6.3 Dependent Variable\n\nRecall that dependent variable, Mobile Money Usage (MMU) will be calculated as:\n\n$$MMU_i = \\frac{\\text{MobileMoneyUsers}_i}{\\text{DistrictCount}_i}$$\n\nTherefore, we create a new column, MMU, in the combined dataframe with the following code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_combined<- tanzania_combined %>%\n  mutate(MMU = (MobileMoney / district_count))\n```\n:::\n\n\n## 6.4 Forming Centroids\n\nWe noted that the geometry column is in MULTIPOLYGON format. For GWR analysis later on, we will need point geometries to represent specific locations. Leaving the geometry as MULTIPOLYGON can negatively affect the GWR analysis, as the model requires precise locations for its local regression estimations.We will use st_centroid to find the centroid points of each district.\n\nTo start, we will create a dataframe that includes the geoboundaries by left joining the geospatial dataframe (tanzbound) to the attribute dataframe (tanzania) by using ***left_join()***.\n\n::: callout-note\n## To perform a left_join(), we must ensure that there is a common column between the two. For our case, the common column is 'dist_name' as we have prepared the data in Section 4.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_cleaned <- left_join(tanzbounds,tanzania_combined)\n```\n:::\n\n\nWe will also save a polygon version for choloropleth map analysis in later sections.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_cleaned_polygons <- left_join(tanzbounds,tanzania_combined)\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\\\nWith the following code ***st_point_on_surface*** we find the centroids on the joined dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_cleaned$centroids <- st_point_on_surface(tanzania_cleaned$geometry)\ntanzania_cleaned <- tanzania_cleaned %>%\n  mutate(geometry = centroids) %>%\n  select(-centroids)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(tanzania_cleaned,\"data/rds/tanzania_cleaned\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_cleaned <- read_rds(\"data/rds/tanzania_cleaned\")\n```\n:::\n\n\nWe will visualize the points with **tmap** to ensure they are properly placed (not in water).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\ntm_shape(tanzbounds) + \n  tm_polygons(col = \"lightblue\", border.col = \"black\") +\n  tm_shape(tanzania_cleaned$geometry) + \n  tm_dots(size = 0.03, col = \"red\") +\n  tm_layout(\n    title = \"Centroids of Districts in Tanzania\", \n    title.position = c(\"center\", \"top\"),\n    title.size = 0.8\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nFrom the map, we have verified that none of the points fall into water and are properly placed. 3 districts: Mafinga, Makambako, and Korogwe are missing since there is no data collected in theses districts for FinScope dataset.\n\n------------------------------------------------------------------------\n\n# 7 Exploratory Data Analysis (EDA)\n\nExploratory Data Analysis (EDA) is a crucial step allowing us to uncover underlying patterns and identify anomalies in our cleaned dataset. EDA not only aids in formulating hypotheses but also guides feature selection and model building, ensuring that the subsequent analysis is robust and meaningful. In this section, we will explore our dataset through descriptive statistics, visualizations, and correlation analysis to derive insights that can inform our understanding of financial inclusion in Tanzania.\n\n## 7.1 Descriptive Statistics and Visualizations\n\n### 7.1.1 Visualizing Dependent Variable\n\nTo begin our exploratory data analysis, we will first visualize the distribution of the dependent variable, the Mobile Money Usage (MMU). The histogram created using `ggplot2` provides a clear representation of how the MMU is distributed across the dataset. By setting the `bins` to 20, we can observe the frequency of different MMU values, revealing patterns such as skewness or the presence of outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=tanzania_cleaned, aes(x=`MMU`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nFrom the figure above, we can confirm that the dependent variable MMU is in normal distribution.\n\nNext, we utilize a histogram to visualize Mobile Money Usage (MMU) values across different districts in Tanzania. This visualization effectively highlights disparities in mobile money usage among districts, providing insights into areas where financial inclusion may be particularly high or low.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = tanzania_cleaned, aes(x = reorder(dist_name,MMU), y = MMU)) +\n  geom_bar(stat = \"identity\", color = \"black\", fill = \"light blue\") +\n  labs(title = \"Average MMU Values by District\",\n       x = \"District Name\",\n       y = \"Mobile Money Usage (MMU)\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 5)) \n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nFrom the histogram, we see that Meatu with around 25% access to mobile money has the lowest and Ilala with around 95% access to mobile money has the highest access.\n\n### 7.1.2 Histogram Plots of Predictor Variables\n\nNext we will use the code chunk below to visualize histograms of key predictor variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAge <- ggplot(data=tanzania_cleaned, aes(x= `Mean_Age`)) + \n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nRegistered_YesNo_Ratio <- ggplot(data=tanzania_cleaned, aes(x= `Registered_YesNo_Ratio`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nMale_Female_Ratio <- ggplot(data=tanzania_cleaned, aes(x= `Male_Female_Ratio`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nUrban <- ggplot(data=tanzania_cleaned, aes(x= `Urban`)) + \n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nMobileMoney <- ggplot(data=tanzania_cleaned, aes(x= `MobileMoney`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nFinancialEducation <- ggplot(data=tanzania_cleaned, \n                               aes(x= `FinancialEducation_YesNo_Ratio`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nMean_AmountBetting <- ggplot(data=tanzania_cleaned, aes(x= `Mean_AmountBetting`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nMean_AmountOwed <- ggplot(data=tanzania_cleaned, aes(x= `Mean_AmountOwed`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nMobilePhone <- ggplot(data=tanzania_cleaned, aes(x= `MobilePhone`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\n\nggarrange(Age, Registered_YesNo_Ratio, Male_Female_Ratio, Urban, \n          FinancialEducation, Mean_AmountBetting, Mean_AmountOwed,MobilePhone,\n          ncol = 2, nrow = 5)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nFrom the histogram, it was noted that some variables are highly skewed. We will apply $log(10+1)$ transformation to normalize variables that has an absolute skewness of 3 or more. The following code chunk was used to check which variables were skewed.\n\nWe must use the dataframe without geometry for this task.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnogeom_df <- as.data.frame(st_drop_geometry(tanzania_cleaned))\n\nskew_threshold <- 3\nskewed_vars <- nogeom_df %>%\n  select(where(is.numeric)) %>%\n  summarise(across(everything(), skewness)) %>%\n  unlist() %>%\n  as.data.frame() %>%\n  rename(Skewness = 1) %>%\n  rownames_to_column(var = \"Variable\") %>%\n  filter(abs(Skewness) > skew_threshold)\nprint(skewed_vars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                Variable Skewness\n1        Registered_YesNo_Ratio.Skewness 7.939190\n2                 NoEdu_SomeEdu.Skewness 5.191753\n3        NoPhoneConnection_Some.Skewness 3.057964\n4            Phone_PayforThings.Skewness 3.669470\n5      BorrowedFrom_PensionFund.Skewness 5.764491\n6  BorrowedFrom_CommunityLender.Skewness 3.021749\n7               Advice_Employer.Skewness 6.891396\n8                   Advice_Bank.Skewness 5.405322\n9           Advice_Microfinance.Skewness 6.731263\n10                Advice_SACCOS.Skewness 5.764491\n11      Advice_FinancialAdvisor.Skewness 3.195030\n12    Advice_FarmersAssociation.Skewness 6.726136\n13   Advice_BusinessAssociation.Skewness 5.044916\n14          Advice_SavingsGroup.Skewness 3.173397\n15           Advice_Moneylender.Skewness 6.731263\n16    Advice_GovernmentOfficial.Skewness 4.405674\n17          Advice_OtherSpecify.Skewness 4.600732\n18           Used_ATM_DebitCard.Skewness 3.400497\n19              Used_CreditCard.Skewness 4.909681\n20                 Used_QR_Code.Skewness 3.549885\n21                     Used_POS.Skewness 4.598958\n22              Mean_AmountOwed.Skewness 3.443722\n23           Mean_AmountBetting.Skewness 5.153680\n```\n\n\n:::\n:::\n\n\nWe will apply $log(10+1)$ transformation to these variables with the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_cleaned$Registered_YesNo_Ratio <- log10(tanzania_cleaned$Registered_YesNo_Ratio + 1)\ntanzania_cleaned$NoEdu_SomeEdu <- log10(tanzania_cleaned$NoEdu_SomeEdu + 1)\ntanzania_cleaned$Phone_PayforThings <- log10(tanzania_cleaned$Phone_PayforThings + 1)\ntanzania_cleaned$BorrowedFrom_PensionFund <- log10(tanzania_cleaned$BorrowedFrom_PensionFund + 1)\ntanzania_cleaned$Advice_Employer <- log10(tanzania_cleaned$Advice_Employer + 1)\ntanzania_cleaned$Advice_Bank <- log10(tanzania_cleaned$Advice_Bank + 1)\ntanzania_cleaned$Advice_Microfinance <- log10(tanzania_cleaned$Advice_Microfinance + 1)\ntanzania_cleaned$Advice_SACCOS <- log10(tanzania_cleaned$Advice_SACCOS + 1)\ntanzania_cleaned$Advice_FinancialAdvisor <- log10(tanzania_cleaned$Advice_FinancialAdvisor + 1)\ntanzania_cleaned$Advice_FarmersAssociation <- log10(tanzania_cleaned$Advice_FarmersAssociation + 1)\ntanzania_cleaned$Advice_BusinessAssociation <- log10(tanzania_cleaned$Advice_BusinessAssociation + 1)\ntanzania_cleaned$Advice_SavingsGroup <- log10(tanzania_cleaned$Advice_SavingsGroup + 1)\ntanzania_cleaned$Advice_Moneylender <- log10(tanzania_cleaned$Advice_Moneylender + 1)\ntanzania_cleaned$Advice_GovernmentOfficial <- log10(tanzania_cleaned$Advice_GovernmentOfficial + 1)\ntanzania_cleaned$Advice_OtherSpecify <- log10(tanzania_cleaned$Advice_OtherSpecify + 1)\ntanzania_cleaned$Used_ATM_DebitCard <- log10(tanzania_cleaned$Used_ATM_DebitCard + 1)\ntanzania_cleaned$Used_CreditCard <- log10(tanzania_cleaned$Used_CreditCard + 1)\ntanzania_cleaned$Used_QR_Code <- log10(tanzania_cleaned$Used_QR_Code + 1)\ntanzania_cleaned$Used_POS <- log10(tanzania_cleaned$Used_POS + 1)\ntanzania_cleaned$Mean_AmountOwed <- log10(tanzania_cleaned$Mean_AmountOwed + 1)\ntanzania_cleaned$Mean_AmountBetting <- log10(tanzania_cleaned$Mean_AmountBetting + 1)\n```\n:::\n\n\n## 7.2 Correlation Analysis\n\nSince we have around 80 variables chosen, it is hard to visualize a correlation matrix. Therefore we will display the highly correlated pairs of variables (with absolute correlations greater than 0.8) with the following code chunk. Again we will use the dataframe without geometry.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_data <- nogeom_df %>%\n  select(-c(MMU,district_count, dist_name, MobileMoney))\ncor_matrix <- cor(cor_data, use = \"complete.obs\")\n\nhigh_correlations <- which(abs(cor_matrix) > 0.8, arr.ind = TRUE)\nhigh_cor_df <- data.frame(\n  Var1 = rownames(cor_matrix)[high_correlations[, 1]],\n  Var2 = colnames(cor_matrix)[high_correlations[, 2]],\n  Correlation = cor_matrix[high_correlations]\n)\n\nhigh_cor_df <- high_cor_df %>%\n  filter(Var1 != Var2) %>%\n  distinct()\n\nprint(high_cor_df)\n```\n:::\n\n\nFrom the correlation table we will keep and eliminate the following variables:\n\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Keep                        | Eliminate                         | Rationale                                                                                                                                                               |\n+=============================+===================================+=========================================================================================================================================================================+\n| `Used_MobileMoney`          | `ConfidentWithMobileMoney`        | `Used_MobileMoney` likely indicates behavior, while `ConfidentWithMobileMoney` is more attitudinal. Behavior often has a stronger impact in financial inclusion models. |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `BorrowedFrom_FriendFamily` | `CutSpending`                     | Borrowing behavior is more directly tied to financial inclusion than cutting expenses, which might be more of a personal decision.                                      |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `Advice_FamilyMember`       | `Used_Cash`                       | Family advice could capture unique information on social support or trust, whereas `Used_Cash` may overlap with other usage variables like mobile money.                |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `GoodPhoneConnection`       | `Used_Cash` (additional instance) | Phone connectivity could be critical for mobile money use, which is essential in financial inclusion contexts.                                                          |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `Used_MobileMoney`          | `Used_LipaNamba`                  | `Used_MobileMoney` can serve as a broader measure of digital financial inclusion.                                                                                       |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `MobilePhone`               | `ExcellentPhoneConnection`        | Having a mobile phone itself is more foundational to financial inclusion than connection quality.                                                                       |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `Trust_Insurance_Companies` | `Insurance_Good_Idea`             | Trust is a more robust predictor of willingness to engage with insurance providers.                                                                                     |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `Moneylender_Access`        | `Moneylender_FeesReasonable`      | Access to moneylenders may be more indicative of financial reach than opinions on fees, which could be subjective.                                                      |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `Do_Not_Know_Where_To_Go`   | `Advice_HouseholdMember`          | Not knowing where to seek financial help may indicate a gap in inclusion more directly than family advice.                                                              |\n+-----------------------------+-----------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\nThe following code excludes the variables from the highly correlated pairs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_cleaned <- tanzania_cleaned %>%\n  select(-c(\n  \"ConfidentWithMobileMoney\",\n  \"CutSpending\",\n  \"Advice_FamilyMember\",\n  \"GoodPhoneConnection\",\n  \"WorkedMore\",\n  \"GotAssistanceFrom_Family\",\n  \"ExcellentPhoneConnection\",\n  \"Trust_Insurance_Companies\",\n  \"Internet\",\n  \"Phone_PayforThings\",\n  \"Network_FailureMM\",\n  \"SmartPhone\",\n  \"Used_LipaNamba\",\n  \"Moneylender_FeesReasonable\",\n  \"Advice_HouseholdMember\",\n  \"Do_Not_Know_Where_To_Go\",\n  \"MobilePhone\",\n  \"Insurance_Good_Idea\",\n  \"UsedSavings\",\n  \"NoPhoneConnection_Some\",\n  \"Agent_No_Cash_FloatMM\",\n  \"Moneylender_Access\",\n  \"BorrowedFrom_FriendFamily\",\n  \"BorrowedFrom_Family_PayBack\",\n  \"NoMoneyForPhone\",\n  \"Own2MobilePhone\",\n  \"ConfidentWithBanks\",\n  \"Moneylender_InfoClear\",\n  \"Moneylender_NeedsMet\",\n  \"Moneylender_CustomerSupport\"\n  ))\n```\n:::\n\n\nWe will also conduct a VIF test to confirm correlation after building our first linear regression model later on.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n# 8 Multiple Linear Regression\n\n## 8.1 Initial Model\n\nWe will construct our initial model using these derived variables and use summary() to check the initial model's explanatory power.\n\n::: panel-tabset\n## Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania.mlr <- lm(formula <- MMU ~ Urban + Male_Female_Ratio + Registered_YesNo_Ratio + ComfortableBank_YesNo_Ratio + \n           PayingBack_YesNo_Ratio + FinancialEducation_YesNo_Ratio + NoEdu_SomeEdu + NoPhoneConnection + \n           BadPhoneConnection + Phone_LotteryGaming + UseSomeoneElsePhone + DontNeedPhone + \n           ParentSpouseDontAllowPhone + BankMFIStatement + ConfidentWithMFIs + ConfidentWithSACCOs + \n           ConfidentWithFamilyFriends + \n           ConfidentWithUTTs + BorrowedFrom_Bank + BorrowedFrom_SACCO + \n           BorrowedFrom_MobileMoney + BorrowedFrom_PensionFund + BorrowedFrom_Employer + \n           BorrowedFrom_Family_NoPayBack + BorrowedFrom_SavingsGroup + BorrowedFrom_CommunityLender + \n           BorrowedFrom_OtherSource + BorrowedFrom_MoneyLender + SoldLivestock + Advice_Employer + \n           Advice_Bank + Advice_Microfinance + Advice_SACCOS + Advice_FinancialAdvisor + \n           Advice_FarmersAssociation + Advice_BusinessAssociation + Advice_SavingsGroup + \n           Advice_Moneylender + Advice_GovernmentOfficial + Advice_VillageElder + Advice_OtherSpecify + \n           Advice_NoOne + Others_CouldntMeetNeeds + Used_ATM_DebitCard + Used_CreditCard + \n           Used_Cryptocurrency + Used_QR_Code + Used_POS + Used_AZAMPay + \n           Places_Not_In_My_Area + Do_Not_Think_They_Care + Have_Insurance_Cover + \n           Agent_OverchargedMM + Lost_MoneyMM + Agent_Requested_PINMM + Other_ProblemsMM + \n           Moneylender_TreatsWell + FORM_INVESTMENTS + Mean_Age + Mean_AmountOwed + Mean_AmountBetting\n, data = tanzania_cleaned)\n```\n:::\n\n\n## Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(tanzania.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = formula <- MMU ~ Urban + Male_Female_Ratio + Registered_YesNo_Ratio + \n    ComfortableBank_YesNo_Ratio + PayingBack_YesNo_Ratio + FinancialEducation_YesNo_Ratio + \n    NoEdu_SomeEdu + NoPhoneConnection + BadPhoneConnection + \n    Phone_LotteryGaming + UseSomeoneElsePhone + DontNeedPhone + \n    ParentSpouseDontAllowPhone + BankMFIStatement + ConfidentWithMFIs + \n    ConfidentWithSACCOs + ConfidentWithFamilyFriends + ConfidentWithUTTs + \n    BorrowedFrom_Bank + BorrowedFrom_SACCO + BorrowedFrom_MobileMoney + \n    BorrowedFrom_PensionFund + BorrowedFrom_Employer + BorrowedFrom_Family_NoPayBack + \n    BorrowedFrom_SavingsGroup + BorrowedFrom_CommunityLender + \n    BorrowedFrom_OtherSource + BorrowedFrom_MoneyLender + SoldLivestock + \n    Advice_Employer + Advice_Bank + Advice_Microfinance + Advice_SACCOS + \n    Advice_FinancialAdvisor + Advice_FarmersAssociation + Advice_BusinessAssociation + \n    Advice_SavingsGroup + Advice_Moneylender + Advice_GovernmentOfficial + \n    Advice_VillageElder + Advice_OtherSpecify + Advice_NoOne + \n    Others_CouldntMeetNeeds + Used_ATM_DebitCard + Used_CreditCard + \n    Used_Cryptocurrency + Used_QR_Code + Used_POS + Used_AZAMPay + \n    Places_Not_In_My_Area + Do_Not_Think_They_Care + Have_Insurance_Cover + \n    Agent_OverchargedMM + Lost_MoneyMM + Agent_Requested_PINMM + \n    Other_ProblemsMM + Moneylender_TreatsWell + FORM_INVESTMENTS + \n    Mean_Age + Mean_AmountOwed + Mean_AmountBetting, data = tanzania_cleaned)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.199529 -0.052297 -0.006167  0.047776  0.194935 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)   \n(Intercept)                     1.703e-01  1.789e-01   0.952  0.34395   \nUrban                           8.288e-02  6.326e-02   1.310  0.19388   \nMale_Female_Ratio               1.990e-02  4.302e-02   0.463  0.64487   \nRegistered_YesNo_Ratio          4.641e-01  3.089e-01   1.502  0.13691   \nComfortableBank_YesNo_Ratio     1.358e-02  1.176e-02   1.154  0.25183   \nPayingBack_YesNo_Ratio          2.668e-01  1.014e-01   2.631  0.01020 * \nFinancialEducation_YesNo_Ratio  3.197e-01  1.173e-01   2.726  0.00787 **\nNoEdu_SomeEdu                  -3.252e-01  1.707e-01  -1.905  0.06040 . \nNoPhoneConnection              -1.013e-03  6.168e-03  -0.164  0.86996   \nBadPhoneConnection             -4.845e-03  1.789e-03  -2.709  0.00825 **\nPhone_LotteryGaming            -1.897e-02  1.407e-02  -1.348  0.18143   \nUseSomeoneElsePhone            -1.040e-02  5.622e-03  -1.850  0.06801 . \nDontNeedPhone                  -2.051e-03  1.326e-02  -0.155  0.87750   \nParentSpouseDontAllowPhone     -8.388e-03  6.899e-03  -1.216  0.22765   \nBankMFIStatement               -1.061e-02  7.078e-03  -1.499  0.13774   \nConfidentWithMFIs               4.881e-03  5.286e-03   0.923  0.35863   \nConfidentWithSACCOs            -1.893e-03  4.882e-03  -0.388  0.69917   \nConfidentWithFamilyFriends      3.539e-05  1.420e-03   0.025  0.98018   \nConfidentWithUTTs               2.018e-03  5.658e-03   0.357  0.72223   \nBorrowedFrom_Bank               9.632e-03  1.498e-02   0.643  0.52205   \nBorrowedFrom_SACCO             -3.070e-02  2.190e-02  -1.402  0.16475   \nBorrowedFrom_MobileMoney       -1.203e-02  9.981e-03  -1.205  0.23169   \nBorrowedFrom_PensionFund        1.494e-01  2.765e-01   0.540  0.59057   \nBorrowedFrom_Employer          -1.417e-02  1.201e-02  -1.179  0.24170   \nBorrowedFrom_Family_NoPayBack   7.678e-03  8.696e-03   0.883  0.37993   \nBorrowedFrom_SavingsGroup      -5.923e-03  4.287e-03  -1.382  0.17088   \nBorrowedFrom_CommunityLender   -4.019e-03  8.109e-03  -0.496  0.62154   \nBorrowedFrom_OtherSource        3.345e-02  2.990e-02   1.119  0.26655   \nBorrowedFrom_MoneyLender        6.019e-03  8.335e-03   0.722  0.47233   \nSoldLivestock                   4.284e-03  2.186e-03   1.959  0.05354 . \nAdvice_Employer                 1.169e-02  1.216e-01   0.096  0.92365   \nAdvice_Bank                    -3.471e-01  1.524e-01  -2.278  0.02540 * \nAdvice_Microfinance            -8.690e-02  3.041e-01  -0.286  0.77578   \nAdvice_SACCOS                   4.296e-01  2.564e-01   1.675  0.09775 . \nAdvice_FinancialAdvisor        -2.669e-02  2.048e-01  -0.130  0.89665   \nAdvice_FarmersAssociation      -2.013e-02  1.171e-01  -0.172  0.86398   \nAdvice_BusinessAssociation      1.708e-01  1.610e-01   1.061  0.29202   \nAdvice_SavingsGroup             5.898e-02  1.252e-01   0.471  0.63892   \nAdvice_Moneylender              5.338e-02  2.702e-01   0.198  0.84388   \nAdvice_GovernmentOfficial      -1.468e-01  1.657e-01  -0.886  0.37836   \nAdvice_VillageElder            -1.070e-02  2.134e-02  -0.502  0.61738   \nAdvice_OtherSpecify             1.627e-01  1.393e-01   1.168  0.24627   \nAdvice_NoOne                    2.012e-03  1.774e-03   1.134  0.26030   \nOthers_CouldntMeetNeeds        -1.198e-02  1.250e-02  -0.958  0.34073   \nUsed_ATM_DebitCard              3.949e-02  5.559e-02   0.710  0.47955   \nUsed_CreditCard                -1.534e-01  6.910e-02  -2.219  0.02930 * \nUsed_Cryptocurrency             1.138e-02  2.042e-02   0.557  0.57884   \nUsed_QR_Code                    1.466e-03  7.760e-02   0.019  0.98497   \nUsed_POS                        2.552e-02  7.568e-02   0.337  0.73683   \nUsed_AZAMPay                    5.224e-03  7.326e-03   0.713  0.47782   \nPlaces_Not_In_My_Area           3.276e-03  2.977e-03   1.101  0.27435   \nDo_Not_Think_They_Care         -1.521e-04  7.263e-03  -0.021  0.98334   \nHave_Insurance_Cover           -1.329e-03  3.674e-03  -0.362  0.71850   \nAgent_OverchargedMM            -1.244e-03  7.077e-03  -0.176  0.86089   \nLost_MoneyMM                    7.626e-03  9.855e-03   0.774  0.44131   \nAgent_Requested_PINMM           6.410e-03  9.639e-03   0.665  0.50796   \nOther_ProblemsMM               -1.187e-02  2.568e-02  -0.462  0.64510   \nMoneylender_TreatsWell          1.812e-02  6.048e-03   2.996  0.00364 **\nFORM_INVESTMENTS                7.945e-03  7.208e-03   1.102  0.27361   \nMean_Age                        9.222e-03  3.750e-03   2.459  0.01608 * \nMean_AmountOwed                -1.925e-02  2.832e-02  -0.680  0.49876   \nMean_AmountBetting              3.178e-02  1.153e-02   2.755  0.00727 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0993 on 80 degrees of freedom\nMultiple R-squared:  0.761,\tAdjusted R-squared:  0.5788 \nF-statistic: 4.176 on 61 and 80 DF,  p-value: 2.022e-09\n```\n\n\n:::\n:::\n\n:::\n\nThe initial model has an adjusted R-squared value of 0.5788, meaning that approximately 58% of the variation in the Mobile Money Usage (MMU) is explained by these predictors.\n\n::: callout-note\n## In multiple linear regression, adjusted R-squared is prioritized over R-squared because it adjusts for the number of predictors in the model, providing a more accurate assessment of model fit. Unlike R-squared, adjusted R-squared penalizes unnecessary predictors, helping to prevent overfitting and offering a more reliable measure of predictive power.\n:::\n\n## 8.2 The Refined Model - Stepwise Regression\n\nIn this section, we perform **stepwise regression** for variable selection. This method systematically includes or excludes variables based on specific criteria, such as the Akaike Information Criterion (AIC) or the Bayesian Information Criterion (BIC). Stepwise regression refines the model by retaining only those predictors that significantly contribute to explaining variations in the Financial Inclusion Index, leading to a more parsimonious and interpretable model.\n\nThrough this process, the multiple linear regression model is optimized to identify the key factors impacting FPAI while addressing multicollinearity and ensuring model stability. This approach ultimately enhances the model's explanatory power, enabling more accurate and actionable insights into the drivers of financial inclusion.\n\n::: callout-note\n## Criteria for Variable Selection: Reject p-value greater than alpha value of 0.05\n:::\n\nWe will use the `olsrr` package to do this. The `olsrr` package in R provides a streamlined process for diagnosing multicollinearity issues, performing variable selection, and generating organized model assessment reports. This stage is critical for refining our initial model, ensuring each retained variable significantly contributes to explaining the dependent variable, the FPAI.\n\nSince p value is our defined criteria, we use ***ols_step_forward_p()*** as shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_vs_mlr <- ols_step_forward_p(tanzania.mlr, p_val= 0.05, details=FALSE)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-42-1.png){width=1152}\n:::\n:::\n\n\nThe stepwise regression analysis streamlined the initial variable set to 12 significant predictors, as illustrated in the accompanying plots. This selection process resulted in an increase in the model's adjusted R-squared value, which increased from 0.5788 in the initial model to 0.625 in the final model. **It suggests a greater proportion of the variance in the Mobile Money Usage (MMU), namely 62.5%, explained by the chosen predictors.**\n\nThe final model with the final variables selected by stepwise regression is shown below.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nMMU ~ Urban + ComfortableBank_YesNo_Ratio + Mean_Age + Mean_AmountBetting + \n    BadPhoneConnection + PayingBack_YesNo_Ratio + FinancialEducation_YesNo_Ratio + \n    Moneylender_TreatsWell + Advice_Bank + Do_Not_Think_They_Care + \n    Advice_SACCOS + Registered_YesNo_Ratio + Used_CreditCard\n<environment: 0x151cdd110>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n## 8.3 Variable Selected\n\nLastly, we will use the ***tbl_regression()*** from *gtsummary* package which helps us to create a publication-ready summary table in R.\n\n[*Results of Multiple Linear Regression for Impact of Selected Variables on Moblie Money Usage (MMU)*]{.underline}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uwjrkmcvxz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uwjrkmcvxz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uwjrkmcvxz thead, #uwjrkmcvxz tbody, #uwjrkmcvxz tfoot, #uwjrkmcvxz tr, #uwjrkmcvxz td, #uwjrkmcvxz th {\n  border-style: none;\n}\n\n#uwjrkmcvxz p {\n  margin: 0;\n  padding: 0;\n}\n\n#uwjrkmcvxz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uwjrkmcvxz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uwjrkmcvxz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uwjrkmcvxz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uwjrkmcvxz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uwjrkmcvxz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uwjrkmcvxz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uwjrkmcvxz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uwjrkmcvxz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uwjrkmcvxz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uwjrkmcvxz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uwjrkmcvxz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uwjrkmcvxz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uwjrkmcvxz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uwjrkmcvxz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwjrkmcvxz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uwjrkmcvxz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uwjrkmcvxz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uwjrkmcvxz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwjrkmcvxz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uwjrkmcvxz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwjrkmcvxz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uwjrkmcvxz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwjrkmcvxz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uwjrkmcvxz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uwjrkmcvxz .gt_left {\n  text-align: left;\n}\n\n#uwjrkmcvxz .gt_center {\n  text-align: center;\n}\n\n#uwjrkmcvxz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uwjrkmcvxz .gt_font_normal {\n  font-weight: normal;\n}\n\n#uwjrkmcvxz .gt_font_bold {\n  font-weight: bold;\n}\n\n#uwjrkmcvxz .gt_font_italic {\n  font-style: italic;\n}\n\n#uwjrkmcvxz .gt_super {\n  font-size: 65%;\n}\n\n#uwjrkmcvxz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uwjrkmcvxz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uwjrkmcvxz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uwjrkmcvxz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uwjrkmcvxz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uwjrkmcvxz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uwjrkmcvxz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uwjrkmcvxz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uwjrkmcvxz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipDaGFyYWN0ZXJpc3RpYyoq&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Characteristic&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><div class='gt_from_md'><p><strong>Characteristic</strong></p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipCZXRhKio=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Beta&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipCZXRhKio=\"><div class='gt_from_md'><p><strong>Beta</strong></p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;Kio5NSUgQ0kqKg==&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;95% CI&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><div class='gt_from_md'><p><strong>95% CI</strong></p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipwLXZhbHVlKio=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;p-value&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipwLXZhbHVlKio=\"><div class='gt_from_md'><p><strong>p-value</strong></p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.0843</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.1254, 0.2940</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Urban</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.1149</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.0356, 0.1942</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.005</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">ComfortableBank_YesNo_Ratio</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.0264</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.0096, 0.0433</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.002</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Mean_Age</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.0094</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.0044, 0.0144</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Mean_AmountBetting</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.0313</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.0159, 0.0468</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">BadPhoneConnection</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.0034</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.0059, -0.0010</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.007</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PayingBack_YesNo_Ratio</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.1831</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.0430, 0.3232</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.011</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FinancialEducation_YesNo_Ratio</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.2741</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.1239, 0.4243</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Moneylender_TreatsWell</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.0118</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.0047, 0.0188</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Advice_Bank</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.3851</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.5748, -0.1954</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Do_Not_Think_They_Care</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.0111</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.0024, 0.0198</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.013</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Advice_SACCOS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.4847</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.1027, 0.8668</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.013</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Registered_YesNo_Ratio</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.4829</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.0885, 0.8773</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.017</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Used_CreditCard</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.0831</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-0.1657, -0.0004</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.049</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><div data-qmd-base64=\"UsKyID0gMC42NjA7IEFkanVzdGVkIFLCsiA9IDAuNjI1OyBBSUMgPSAtMjU0OyBTdGF0aXN0aWMgPSAxOS4xOyBwLXZhbHVlID0gPDAuMDAxOyDPgyA9IDAuMDk0\"><div class='gt_from_md'><p>R² = 0.660; Adjusted R² = 0.625; AIC = -254; Statistic = 19.1; p-value = &lt;0.001; σ = 0.094</p>\n</div></div></td>\n    </tr>\n  </tfoot>\n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span> <div data-qmd-base64=\"Q0kgPSBDb25maWRlbmNlIEludGVydmFs\"><div class='gt_from_md'><p>CI = Confidence Interval</p>\n</div></div></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nInterpretation of Model Results:\n\n-   **Intercept (β = 0.0843)**: The intercept represents the baseline level of financial participation when all other predictors are at zero. A positive but non-significant intercept suggests that financial participation would remain low if no other variables provided a positive influence, indicating limited financial engagement under baseline conditions.\n\n-   **Urban (β = 0.1149)**: Living in an urban area is positively associated with financial participation, likely due to better access to financial services and institutions in urban settings. The effect is moderate and statistically significant, indicating that urban residents tend to have higher financial access compared to rural counterparts.\n\n-   **ComfortableBank_YesNo_Ratio (β = 0.0264)**: This positive effect shows that individuals who feel comfortable using banks are more likely to engage in mobile banking activities. It highlights the importance of trust in financial institutions for financial participation.\n\n-   **Mean_Age (β = 0.0094)**: There’s a small positive association between age and financial participation, suggesting that older individuals may have higher access to mobile banking, potentially due to greater wealth accumulation or financial experience over time.\n\n-   **Mean_AmountBetting (β = 0.0313)**: A positive association with financial participation indicates that individuals who bet more may also be more financially active, possibly due to a greater tendency to take risks or engage in diverse financial behaviors.\n\n-   **BadPhoneConnection (β = -0.0034)**: A poor phone connection has a small but significant negative effect on mobile banking, indicating that connectivity challenges may hinder access to mobile-based financial services, which are critical in many regions.\n\n-   **PayingBack_YesNo_Ratio (β = 0.1831)**: This variable has a strong positive association with financial participation, suggesting that individuals who are currently paying back loans may be using mobile banking and thus increased access to financial resources.\n\n-   **FinancialEducation_YesNo_Ratio (β = 0.2741)**: A significant positive effect of financial education on participation implies that financial literacy promotes engagement with financial products, as educated individuals are likely to feel more confident in managing finances.\n\n-   **Moneylender_TreatsWell (β = 0.0118)**: The positive coefficient indicates that favorable experiences with moneylenders correlate with higher financial participation, possibly due to increased trust in these informal lending sources.\n\n-   **Advice_Bank (β = -0.3851)**: A strong negative effect, suggesting that relying on banks for financial advice is associated with lower financial participation and participation in mobile banking. This may reflect distrust in formal financial institutions or a lack of accessible, personalized advice from banks.\n\n-   **Do_Not_Think_They_Care (β = 0.0111)**: This small positive association suggests that individuals who believe financial institutions do not care about them are slightly more likely to engage in mobile banking activities, underscoring the role of perceived institutional support in financial inclusion.\n\n-   **Advice_SACCOS (β = 0.4847)**: The positive effect indicates that those who receive financial advice from SACCOs (Savings and Credit Cooperative Organizations) are more engaged in financial and mobile money activities, likely due to SACCOs' community-based approach and support.\n\n-   **Registered_YesNo_Ratio (β = 0.4829)**: This positive association implies that individuals with formal registered businesses are more likely to participate in mobile banking, likely because they meet formal requirements for accessing financial services.\n\n-   **Used_CreditCard (β = -0.0831)**: The negative association suggests that individuals who use credit cards may have lower usage of mobile money, potentially due to reliance on this form of credit or barriers to other financial products.\n\nThe predictors, especially those with larger positive coefficients like **Registered_YesNo_Ratio** (0.4829) and **FinancialEducation_YesNo_Ratio** (0.2741), reveal impactful areas where improvements could directly boost MMU and financial inclusion. Similarly, variables with negative coefficients, like **Advice_Bank** (-0.3851) and **BadPhoneConnection** (-0.0034**)**, suggest barriers that significantly limits access to financial products and would require attention to enhance inclusion.\n\n## 8.4 Model Diagnostics\n\n### **8.4.1 Multicollinearity - VIF**\n\nGiven the large number of variables and low Adjusted R-squared, multicollinearity becomes a concern. High Variance Inflation Factor (VIF) scores indicate that some variables may be highly correlated with one another, which can distort the model's estimates and inflate standard errors. By calculating the VIF for each predictor, we can identify those with excessive multicollinearity—typically with VIF values above 10, suggesting that they should be either removed or consolidated to improve model stability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_vif_tol(final_tanzania.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        Variables Tolerance      VIF\n1                           Urban 0.5391961 1.854613\n2     ComfortableBank_YesNo_Ratio 0.8278066 1.208012\n3                        Mean_Age 0.8853934 1.129441\n4              Mean_AmountBetting 0.7942952 1.258978\n5              BadPhoneConnection 0.7228062 1.383497\n6          PayingBack_YesNo_Ratio 0.8077738 1.237970\n7  FinancialEducation_YesNo_Ratio 0.6237903 1.603103\n8          Moneylender_TreatsWell 0.8842631 1.130885\n9                     Advice_Bank 0.4909498 2.036868\n10         Do_Not_Think_They_Care 0.6649623 1.503845\n11                  Advice_SACCOS 0.6677164 1.497642\n12         Registered_YesNo_Ratio 0.5915445 1.690490\n13                Used_CreditCard 0.6820998 1.466061\n```\n\n\n:::\n:::\n\n\nAfter stepwise regression and significant variables were selected, we can see that there is no VIF greater than 10, indicating no multicollinearity is present in our refined model. This is expect since multicollinearity was not present in the initial model before stepwise regression as well.\n\n### 8.4.2 Test for Non Linearity\n\nTesting for non-linearity assesses whether the relationship between the predictor variables and the FPAI deviates from a straight line, as linear regression assumes a linear relationship. If non-linearity is present, the residuals will show systematic patterns rather than a random scatter. Testing for non-linearity ensures that the model captures the true relationships within the data and improves predictive accuracy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_resid_fit(tanzania_vs_mlr$model)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\nFrom the figure above, we can confirm that residuals are non linear.\n\n### 8.4.3 Test for Normality Assumption\n\nThe normality assumption in linear regression pertains to the distribution of residuals, not the predictor variables. Residuals should follow a normal distribution for valid inference in terms of hypothesis testing and confidence intervals. If residuals are not normally distributed, transformations or robust regression techniques may be needed to satisfy the assumption, ensuring reliable and accurate estimates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_resid_hist(tanzania_vs_mlr$model)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\nFrom the figure above, we can confirm that residuals are normally distributed.\n\n### 8.4.4 Test for Spatial Autocorrelation\n\nTesting for spatial autocorrelation is crucial when working with geographically clustered data, as it assesses whether residuals are correlated across spatial locations. Spatial autocorrelation implies that observations close in space may influence each other, violating the independence assumption in linear regression. Moran’s I statistic will be used to detect spatial autocorrelation in residuals.\n\nFirst we will extract the residuals from the model and name this column as VS\\_ MLR_RES with the following code chunk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr_output <- as.data.frame(tanzania_vs_mlr$model$residuals)%>%\n  rename ('VS_MLR_RES' = 'tanzania_vs_mlr$model$residuals')\n```\n:::\n\n\nThen we will use **cbind** (since there is no unique identifier) to join the newly created dataframe of residuals with our point feature data.frame, tanzania_cleaned_polygons, to plot the distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_cleaned_polygons <- cbind(tanzania_cleaned_polygons,\n                         mlr_output$VS_MLR_RES) %>%\n  rename ('MLR_RES'='mlr_output.VS_MLR_RES')\n```\n:::\n\n::: {.cell}\n\n:::\n\n\nWe will visualize the MLR residual values in a choloropleth map as follows.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\nThe map displays the spatial distribution of residuals from our multiple linear regression model across various districts in Tanzania. Each dot represents a point in the dataset, colored based on quantiles of residual values, ranging from low residuals (dark red) to high residuals (dark green). Negative residuals (red to yellow shades) suggest areas where the model underestimates the observed values, while positive residuals (yellow to green shades) indicate overestimations.\n\nClusters of similar residual values are visible in several regions. For instance, areas in the eastern parts of Tanzania show concentrations of positive residuals, whereas some **central** (Manyoni, Sikonge,Urambo) and **northern regions** (Karagwe,Ngara) display clusters of negative residuals. These clusters suggest spatial patterns in the model's performance, indicating that it may overestimate or underestimate values systematically in specific areas.\n\n#### 8.4.4.1 Spatially Stationary Test\n\nTo determine whether similar or dissimilar values are clustered in space, we will conduct a Global Moran’s I test. This test will allow us to measure the degree of spatial autocorrelation in the data. If the residuals from the model are spatially independent, Moran’s I should indicate no significant spatial autocorrelation.\n\nThe hypotheses for this test are as follows:\n\n-   **Null Hypothesis (H0):** The distribution of FPAI residuals is spatially independent, meaning there is no spatial pattern (random distribution).\n-   **Alternative Hypothesis (H1):** There is spatial dependence in the FPAI residuals, suggesting that similar values are spatially clustered or dispersed.\n\nA 95% confidence level will be used to evaluate significance (alpha level of 0.05).\n\nTo perform the Global Moran’s I test, we will first compute distance-based weights using `st_knn` to determine nearest neighbors and `st_weights` to assign weights based on these distances. This setup will provide the foundation for assessing spatial autocorrelation in the residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntanzania_cleaned <- tanzania_cleaned %>%\n  mutate (nb = st_knn(geometry, k = 6,\n                      longlat= FALSE),\n          wt = st_weights(nb,\n                          style = 'W'),\n          .before = 1)\n```\n:::\n\n\nWe are ready to perform Global Moran I with 100 simulations using ***global_moran_perm.*** We will first set.seed tomake the random number generation deterministic, allowing us to get the same results every time this code is ran.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nglobal_moran_perm(tanzania_cleaned$MLR_RES,\n                  tanzania_cleaned$nb,\n                  tanzania_cleaned$wt,\n                  alternative = \"two.sided\",\n                  nsim=99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = 0.093571, observed rank = 100, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nSince the p-value is much smaller than our significance level of 0.05, we **reject the null hypothesis**. This indicates that the residuals are not randomly distributed but instead exhibit clustering, suggesting spatial dependence. To further explore this spatial dependence in Mobile Money Usage(MMU) across districts in Tanzania, we will proceed with a geographically weighted linear regression (GWR) analysis. This approach will help us understand how the relationship between financial inclusion and its predictors varies across different locations.\n\n------------------------------------------------------------------------\n\n# 9 Geographically Weighted Linear Regression\n\n## 9.1 Adaptive Bandwidth\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- bw.gwr(formula = MMU ~ Urban + ComfortableBank_YesNo_Ratio + Mean_Age + Mean_AmountBetting + \n    BadPhoneConnection + PayingBack_YesNo_Ratio + FinancialEducation_YesNo_Ratio + \n    Moneylender_TreatsWell + Advice_Bank + Do_Not_Think_They_Care + \n    Advice_SACCOS + Registered_YesNo_Ratio + Used_CreditCard,\n                      data = tanzania_cleaned, \n                      approach=\"CV\", \n                      kernel=\"gaussian\", \n                      adaptive=TRUE, \n                      longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive bandwidth: 95 CV score: 1.359257 \nAdaptive bandwidth: 67 CV score: 1.359526 \nAdaptive bandwidth: 114 CV score: 1.363338 \nAdaptive bandwidth: 85 CV score: 1.359637 \nAdaptive bandwidth: 103 CV score: 1.360108 \nAdaptive bandwidth: 91 CV score: 1.359477 \nAdaptive bandwidth: 98 CV score: 1.360422 \nAdaptive bandwidth: 93 CV score: 1.360228 \nAdaptive bandwidth: 96 CV score: 1.359983 \nAdaptive bandwidth: 94 CV score: 1.359824 \nAdaptive bandwidth: 95 CV score: 1.359257 \n```\n\n\n:::\n:::\n\n\nThe adaptive bandwidth values control the number of neighboring points included in each localized regression. Each bandwidth produced a Cross-Validation (CV) score, with lower scores indicating a better model fit. Here, an adaptive bandwidth of 95 neighbors provided the lowest CV score (1.359257), suggesting it best balances model accuracy with spatial variability across the regions studied.\n\n## 9.2 GWR Model\n\nThen we compute the GWR based on this bandwidth of 95 neighbors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- gwr.basic(formula = MMU ~ Urban + ComfortableBank_YesNo_Ratio + Mean_Age + Mean_AmountBetting + \n    BadPhoneConnection + PayingBack_YesNo_Ratio + FinancialEducation_YesNo_Ratio + \n    Moneylender_TreatsWell + Advice_Bank + Do_Not_Think_They_Care + \n    Advice_SACCOS + Registered_YesNo_Ratio + Used_CreditCard,\n                      data = tanzania_cleaned, \n                          bw=bw_adaptive, \n                          kernel = 'gaussian', \n                          adaptive=TRUE, \n                          longlat = FALSE)\ngwr_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2024-11-07 13:04:34.293031 \n   Call:\n   gwr.basic(formula = MMU ~ Urban + ComfortableBank_YesNo_Ratio + \n    Mean_Age + Mean_AmountBetting + BadPhoneConnection + PayingBack_YesNo_Ratio + \n    FinancialEducation_YesNo_Ratio + Moneylender_TreatsWell + \n    Advice_Bank + Do_Not_Think_They_Care + Advice_SACCOS + Registered_YesNo_Ratio + \n    Used_CreditCard, data = tanzania_cleaned, bw = bw_adaptive, \n    kernel = \"gaussian\", adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  MMU\n   Independent variables:  Urban ComfortableBank_YesNo_Ratio Mean_Age Mean_AmountBetting BadPhoneConnection PayingBack_YesNo_Ratio FinancialEducation_YesNo_Ratio Moneylender_TreatsWell Advice_Bank Do_Not_Think_They_Care Advice_SACCOS Registered_YesNo_Ratio Used_CreditCard\n   Number of data points: 142\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n      Min        1Q    Median        3Q       Max \n-0.234523 -0.058602  0.002197  0.064349  0.252286 \n\n   Coefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)                     0.084295   0.105985   0.795 0.427884    \n   Urban                           0.114939   0.040080   2.868 0.004836 ** \n   ComfortableBank_YesNo_Ratio     0.026421   0.008518   3.102 0.002367 ** \n   Mean_Age                        0.009428   0.002520   3.741 0.000275 ***\n   Mean_AmountBetting              0.031325   0.007810   4.011 0.000102 ***\n   BadPhoneConnection             -0.003431   0.001240  -2.766 0.006506 ** \n   PayingBack_YesNo_Ratio          0.183052   0.070805   2.585 0.010850 *  \n   FinancialEducation_YesNo_Ratio  0.274112   0.075927   3.610 0.000438 ***\n   Moneylender_TreatsWell          0.011756   0.003571   3.292 0.001286 ** \n   Advice_Bank                    -0.385100   0.095880  -4.016 0.000100 ***\n   Do_Not_Think_They_Care          0.011081   0.004412   2.511 0.013274 *  \n   Advice_SACCOS                   0.484732   0.193080   2.511 0.013301 *  \n   Registered_YesNo_Ratio          0.482927   0.199324   2.423 0.016800 *  \n   Used_CreditCard                -0.083065   0.041767  -1.989 0.048858 *  \n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 0.09364 on 128 degrees of freedom\n   Multiple R-squared:  0.66\n   Adjusted R-squared: 0.6254 \n   F-statistic: 19.11 on 13 and 128 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 1.122394\n   Sigma(hat): 0.08953827\n   AIC:  -254.353\n   AICc:  -250.5435\n   BIC:  -277.6782\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 95 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                        Min.    1st Qu.     Median    3rd Qu.\n   Intercept                       0.0024397  0.0151368  0.0657616  0.1244325\n   Urban                           0.0972698  0.1029681  0.1144813  0.1230138\n   ComfortableBank_YesNo_Ratio     0.0242926  0.0250739  0.0263692  0.0274140\n   Mean_Age                        0.0081776  0.0087924  0.0098121  0.0106637\n   Mean_AmountBetting              0.0272839  0.0281781  0.0310304  0.0342018\n   BadPhoneConnection             -0.0036780 -0.0034616 -0.0032737 -0.0031668\n   PayingBack_YesNo_Ratio          0.1303799  0.1441565  0.1824606  0.2293617\n   FinancialEducation_YesNo_Ratio  0.2560450  0.2693637  0.2862596  0.2974368\n   Moneylender_TreatsWell          0.0107185  0.0112226  0.0118736  0.0123978\n   Advice_Bank                    -0.4066164 -0.3923835 -0.3659927 -0.3531177\n   Do_Not_Think_They_Care          0.0106830  0.0109336  0.0113517  0.0114650\n   Advice_SACCOS                   0.4242574  0.4350353  0.4871346  0.5362002\n   Registered_YesNo_Ratio          0.3795064  0.4222253  0.4528071  0.5088361\n   Used_CreditCard                -0.0868426 -0.0856401 -0.0817866 -0.0803661\n                                     Max.\n   Intercept                       0.1540\n   Urban                           0.1319\n   ComfortableBank_YesNo_Ratio     0.0278\n   Mean_Age                        0.0109\n   Mean_AmountBetting              0.0354\n   BadPhoneConnection             -0.0031\n   PayingBack_YesNo_Ratio          0.2437\n   FinancialEducation_YesNo_Ratio  0.3023\n   Moneylender_TreatsWell          0.0128\n   Advice_Bank                    -0.3339\n   Do_Not_Think_They_Care          0.0117\n   Advice_SACCOS                   0.5705\n   Registered_YesNo_Ratio          0.5257\n   Used_CreditCard                -0.0798\n   ************************Diagnostic information*************************\n   Number of data points: 142 \n   Effective number of parameters (2trace(S) - trace(S'S)): 22.11386 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 119.8861 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): -252.0175 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): -279.1281 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): -347.8753 \n   Residual sum of squares: 1.022093 \n   R-square value:  0.6903413 \n   Adjusted R-square value:  0.6327421 \n\n   ***********************************************************************\n   Program stops at: 2024-11-07 13:04:34.302975 \n```\n\n\n:::\n:::\n\n\nThe comparison between the results of the global regression and Geographically Weighted Regression (GWR) reveals a significant improvement in model fit with GWR. The adjusted R-squared for the global regression stands at 0.6254, indicating that approximately 62.54% of the variance in the financial participation index (FPAI) is explained by the predictors. In contrast, **the GWR model exhibits a substantially higher adjusted R-squared value of 0.6327, suggesting that about 63.27% of the variance is explained.** This increase of approximately 0.73 percentage points indicates that GWR captures local variations and spatial heterogeneity slightly more effectively than the global model, highlighting the importance of accounting for geographical differences in understanding factors influencing access to Mobile Money/Banking.\n\n## 9.3 Visualizing GWR Output\n\nTo visualize the GWR output, we first convert the GWR output spatial data frame (SDF) into a standard `sf` data frame. In this step, we extract the relevant information from the GWR output while excluding the intercept found in column number 1. The code snippet for this operation is as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive_output <- as.data.frame(\n  gwr_adaptive$SDF)%>%\n  select (-c(2:13))\n```\n:::\n\n\nNext, we combine the cleaned Tanzania dataset with the GWR output to create a new spatial data frame, `gwr_sf_adaptive`, which includes both the geographical information and the localized regression results\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_sf_adaptive_poly <- cbind(tanzania_cleaned_polygons,\n                         gwr_adaptive_output)\n```\n:::\n\n\n### 9.3.1 Visualizing Local $R^2$\n\nThe localized model demonstrates a significant enhancement in performance, with the local $R^2$ values reaching as high as 0.72 for specific locations. This improvement illustrates the effectiveness of GWR in capturing spatial variations in model performance across different regions. The following code generates a map that overlays the Tanzania boundary with the localized $R^2$ values represented as dots.\n\nTo visualize a choloropleth map we will take the following steps:\n\n1.  Set geometry of gwr_sf_adaptive to the polygons\n2.  Plot the choloropleth map of aggregated values\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\nThe map displays the spatial distribution of local $R^2$ values from the geographically weighted regression (GWR) model, overlaid on Tanzania's district boundaries. Each dot represents a location with a local $R^2$ value, color-coded according to its range. Darker shades indicate higher local $R^2$ values, while lighter shades indicate lower values.\n\nThe local $R^2$ values range from 0.65 to 0.72 in this visualization, with clusters of higher values (0.71 to 0.72) concentrated in certain areas. This variation in local $R^2$ suggests that the model's explanatory power varies across Tanzania, reflecting differences in how well the predictors explain financial inclusion in different districts. Higher $R^2$ values in specific **northern and western districts** highlight areas where the GWR model better captures the relationship between Mobile Money Usage (MMU) and its predictors, likely due to localized factors influencing financial inclusion outcomes.\n\n### 9.3.2 Visualizing coefficient estimates\n\nLastly, we will visualize the standard error and t-value maps of the key significant predictors.\n\n#### 9.3.2.1 Financial Literacy and Comfort\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\n1. **FinancialEducation_YesNo Ratio**\n\n-   **Left (SE):** The map displays the standard error values associated with the ratio of individuals with financial education versus those without. Districts with darker orange dots in the north show higher standard errors, suggesting greater variability or uncertainty in how financial education impacts financial inclusion in these areas. Lighter shades in other districts indicate more stable estimates, implying a more consistent influence of financial education on financial inclusion.\n\n\n```{=html}\n<!-- -->\n```\n\n-   **Right (TV):**The t-value map illustrates the strength and direction of the influence of financial education on Mobile Money Usage. Higher t-values, shown by darker dots, indicate a stronger positive impact of financial education on financial inclusion in those regions. The northeastern areas have relatively high t-values, suggesting that financial education is statistically significant and positively associated with financial inclusion in these regions.\n\n2. **ComfortableBank_YesNo_Ratio (Bottom Row)**\n\n-   **Left (SE):** Darker colors in northern regions indicate greater variability, reflecting more uncertainty in the influence of comfort with banking on Mobile banking in these areas. Lighter colors elsewhere suggest more stable estimates of this effect.\n-   **Right (TV):** The t-value map represents the strength and direction of the effect of comfort with banking services on Mobile Money Usage. Darker shades indicate stronger positive effects, where a higher proportion of individuals comfortable with banking correlates with higher levels of financial inclusion. The coastal and southern districts, with darker orange dots, show that comfort with banking has a particularly positive influence on MMU in these areas.\n\n#### 9.3.2.2 Demographics\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n\n1\\. Urban Ratio (Top Row)\n\n-   **Left (Urban_SE):** The map displays the standard error values for the Urban ratio, representing the difference between urban and rural populations. Districts with darker orange shades, particularly in northern and central districts, show higher standard errors. This indicates greater variability or uncertainty in the influence of being in an urban setting on financial inclusion in these districts. Lighter colors elsewhere reflect more stable estimates.\n\n-   **Right (Urban_TV):** The t-value map illustrates the statistical significance and strength of the impact of urban residence on MMU. Higher t-values, shown by darker dots in the northwestern and southwestern districts, suggest a significant positive effect of urban residence on financial inclusion in these areas.\n\n2\\. Mean Age Ratio (Bottom Row)\n\n-   **Left (Mean_Age_SE):** This map shows the standard error values for the Mean Age ratio, indicating the variability in the effect of mean age on financial inclusion across districts. Darker shades in the dis districts point to higher uncertainty in how age impacts financial inclusion, while lighter colors in the south suggest more consistent effects.\n\n-   **Right (Mean_Age_TV):** The t-value map represents the strength and direction of the relationship between mean age and MMU. Darker areas, mostly concentrated in the northern parts, indicate a statistically significant effect, implying that mean age is an influential factor in financial inclusion for these districts.\n\n#### 9.3.2.3 Access to Financial Products and Basic Technology\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n\n1\\. Used_CreditCard (Top Row)\n\n-   **Left (Used_CreditCard_SE):** The map displays the standard error values, indicating the uncertainty in the effect of credit card usage on MMU across districts. The darker areas, mostly in the northern and eastern parts of the region, have higher standard errors, suggesting greater variability in these locations. Lighter colors elsewhere reflect more stable estimates.\n\n-   **Right (Used_CreditCard_TV):** The map on the right shows the t-values, representing the statistical significance of credit card usage on financial inclusion. Higher negative t-values, represented by darker points primarily in the north, indicate a significant effect. This suggests that, in these districts, credit card usage may have a more notable relationship with financial inclusion, even if the effect size is negative.\n\n2\\. BadPhoneConnection (Bottom Row)\n\n-   **Left (BadPhoneConnection_SE):** Higher standard errors are shown in darker orange shades, mainly in southern and eastern districts, indicating greater uncertainty in how phone connection quality impacts financial inclusion in these areas. Lighter colors suggest more stable estimates in other regions.\n\n-   **Right (BadPhoneConnection_TV):** The t-value map shows the significance of the relationship between poor phone connectivity and financial inclusion. Darker colors in the southern districts represent stronger negative t-values, suggesting a statistically significant impact. This implies that poor phone connectivity may negatively affect financial inclusion more prominently in these areas.\n\n#### 9.3.2.3 Financial Institution's Involvement\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n\n1\\. Do_Not_Think_They_Care (Top Row)\n\n-   **Left (Do_Not_Think_They_Care_SE):** The map displays the standard error values, indicating the uncertainty in the effect of financial institutions not caring on mobile money usage across districts. There are only a few darker areas, mostly in the central districts, have higher standard errors, suggesting greater variability in these locations. Lighter colors elsewhere reflect more stable estimates.\n\n-   **Right (Do_Not_Think_They_Care_TV):** The map on the right shows the t-values, representing the statistical significance of financial institutions not caring on financial inclusion. Higher negative t-values, represented by darker points primarily in the western coastal districts, indicate a significant effect. This suggests that, in these districts, when financial institutions don't care there may be a greater impact on financial inclusion.\n\n2\\. Advice_Bank (Bottom Row)\n\n-   **Left (Advice_Bank_SE):** Higher standard errors are shown in darker orange shades, mainly in southern and central districts, indicating greater uncertainty in how advice from banks impacts Mobile banking in these areas. Lighter colors suggest more stable estimates in other regions.\n\n-   **Right (Advice_Bank_TV):** The t-value map shows the significance of the relationship between bank advice and financial inclusion. Darker colors in the southern districts represent stronger negative t-values, suggesting a statistically significant impact. This implies that advice from banks may negatively affect Mobile Banking more prominently in these districts. This calls for improvement in advice from banks to promote mobile banking,\n\n------------------------------------------------------------------------\n\n# 10 Conclusion\n\nThis study provides an in-depth analysis of the factors influencing financial inclusion in Tanzania through the lens of Mobile Money Usage (MMU), a core indicator of financial participation in underserved regions. By employing Multiple Linear Regression (MLR) and Geographically Weighted Regression (GWR), this analysis explores both the overall and localized effects of socio-economic, demographic, and infrastructural variables on financial access across Tanzanian districts.\n\nThe initial model, capturing approximately 58% of the variance in MMU, demonstrated a substantial explanatory power in identifying key drivers of financial inclusion. Through stepwise regression, a refined model achieved an adjusted R-squared of 62.5%, pinpointing significant predictors including urban residency, comfort with banking, financial education, mobile connectivity, and advice from SACCOs. Notably, urban residency and financial education emerged as critical enablers, emphasizing the importance of financial literacy and regional access to financial infrastructure. Conversely, reliance on banks for financial advice was associated with lower engagement, highlighting potential mistrust or accessibility issues with formal institutions.\n\nFurthermore, the exploration of Geographically Weighted Regression (GWR) provided valuable insights into the spatial variations of these factors across different districts. GWR allowed for a better understanding of how the effects of key variables vary regionally, thereby increasing the explanatory power of the model to 63.27%.\n\nThis study emphasizes the multifaceted nature of financial inclusion, where socio-economic and infrastructural factors interact to influence access to financial services. The findings suggest targeted interventions, such as enhancing mobile connectivity in rural areas, promoting financial education, and fostering community-based financial organizations like SACCOs, could foster broader financial participation.\n\n------------------------------------------------------------------------\n\n# References\n\nDemirgüç-Kunt, A., Klapper, L., & Singer, D. (2017). *Financial inclusion and inclusive growth: A review of recent empirical evidence* (WPS8040). Development Research Group, Finance and Private Sector Development Team. https://doi.org/10.1596/1813-9450-8040\n\nKoomson, I., Churchill, S.A. & Munyanyi, M.E. Gambling and Financial Stress. *Soc Indic Res***163**, 473–503 (2022). https://doi.org/10.1007/s11205-022-02898-6\n\nUnited Nations Capital Development Fund (UNCDF). (2024). *Insights from Tanzania: Global data reveals financial inclusion for women*. Retrieved from <https://policyaccelerator.uncdf.org/whats-new/insights-tanzania-global-data-reveals-financial-inclusion-women>\n\nWorld Bank. (17 April, 2024). *Financial inclusion in Sub-Saharan Africa: Overview*. Retrieved from <https://www.worldbank.org/en/publication/globalfindex/brief/financial-inclusion-in-sub-saharan-africa-overview>\n\nWorld Bank. (2022). *Global financial inclusion: A comprehensive overview*. Retrieved from <https://documents1.worldbank.org/curated/en/099305408252329233/pdf/SECBOS1e6ff9a00041b4261bcdc9c154a7b.pdf>\n",
    "supporting": [
      "Take-home_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}