{
  "hash": "06efa87ae0f03199fd8b1fa9e8ad6215",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 2: Impacts of COVID-19 on Thailand tourism economy at the province level using spatial and spatio-temporal statistics\"\nauthor: \"Sei Sar Hla Kyi\"\ndate: \"25 September 2024\"\ndate-modified: \"2024-10-07\"\nexecute: \n  eval: true\n  echo: true\n  message: false\n  freeze: true\n  warning: false\n---\n\n\n# 1 Overview\n\n## 1.1 Background\n\nTourism has long been one of the key pillars of Thailand’s economy, contributing significantly to the country's gross domestic product (GDP). In 2019, prior to the COVID-19 pandemic, the tourism sector generated approximately 90 billion US dollars from domestic and international visitors, representing around 20% of the nation’s GDP. However, the pandemic severely impacted global travel and tourism, leading to a dramatic revenue decline to just 24 billion US dollars in 2020. The recovery of the tourism industry began gradually around September 2021, driven by both domestic reopening and the resumption of international travel.\n\nDespite this gradual recovery, tourism income is not evenly distributed across the country. Thailand’s tourism economy is heavily concentrated in a few key provinces—Bangkok, Phuket, Chiang Mai, Sukhothai, and Phetchaburi—due to their cultural significance, economic importance, and tourism infrastructure. These provinces attract the bulk of visitors, while other areas benefit less from tourism activities. This uneven distribution raises questions about the spatial dependence and clustering of tourism-related economic indicators, which are of great interest to policymakers, economists, and urban planners aiming to foster more inclusive economic development through tourism.\n\nWith advancements in geospatial analytics, we can examine how economic patterns shift regionally and temporally. Understanding the spatial and spatio-temporal dynamics of tourism is critical for promoting equitable growth, improving infrastructure, and enhancing the resilience of local economies. By investigating these patterns, it becomes possible to detect clusters of tourism activity, emerging hot spots, and potential cold spots, allowing for more targeted interventions in the tourism sector.\n\n------------------------------------------------------------------------\n\n## 1.2 Objectives\n\nThe primary goal of this analysis is to explore whether the key indicators of Thailand's tourism economy demonstrate space and space and time dependence. Specifically, the objectives of this study are as follows:\n\n1.  **Assess Space and Space and Time Independence**: Investigate whether the tourism economy is independent of geographic space and time, or if there is significant clustering of economic activity in certain regions over specific time periods.\n\n2.  **Identify Clusters and Outliers**: If space and space and time dependence exists, detect the locations of clusters and outliers, identifying areas where tourism-related economic activity is abnormally high or low compared to neighboring regions.\n\n3.  **Detect Emerging Hot Spots and Cold Spots**: Conduct emerging hotspot analysis to determine areas where tourism activity is intensifying or declining over time, highlighting regions that may be experiencing rapid growth or a downturn in tourism-driven economic development.\n\n## 1.3 Determining Tourism Economy Indicators\n\n[**Total Revenue**]{.underline}\n\nWe chose to use total revenue from the tourism sector (denoted as `revenue_all`) as our one of our indicator of interest because it serves as a comprehensive indicator of the economic impact of tourism on a region. Revenue from tourism is a direct reflection of the sector's contribution to the local economy, by including spending from both domestic and international tourists across various services. By focusing on total revenue, we capture the aggregate demand generated by tourism, which is a critical driver of economic growth, employment, and infrastructure development within a province. Furthermore, revenue is a more stable and reliable measure compared to other variables like visitor count, as it accounts for variations in the types of tourists and the value of their spending. This makes it a more appropriate and meaningful variable to assess the overall economic benefits that tourism brings to the regions in our study.\n\n[**Occupancy Rate**]{.underline}\n\nThe occupancy rate (denoted as `ratio_tourist_stay`)is a critical indicator of tourism economy as it measures the percentage of available accommodations (e.g., hotels, guesthouses) that are occupied by tourists at a given time. A high occupancy rate suggests strong demand for tourist services and indicates a thriving tourism sector, which can positively affect related industries like hospitality, transportation, and local businesses. Tracking this variable allows for assessing seasonal variations in tourist flow.\n\n[**Number of foreign tourists**]{.underline}\n\nThe number of foreign tourists (denoted as `no_tourist_foreign)` visiting a province is another valuable indicator of tourism's contribution to the economy. Foreign tourists typically bring in foreign currency, contributing to the province's overall economic growth. They may also have different spending behaviors compared to domestic tourists, which could stimulate demand for luxury goods, international cuisine, or premium tourist experiences. Understanding the volume of foreign tourists also allows us to understand the impact of COVID-19 clearly.\n\n------------------------------------------------------------------------\n\n# 2 Loading R Packages\n\n::: panel-tabset\n## Packages Used\n\nThe following packages were used for this study:\n\n| Package   | Description                                                    |\n|------------------------------------|------------------------------------|\n| tidyverse | For non-spatial data wrangling                                 |\n| corrplot  | For correlation analysis among chosen variables                |\n| sf        | For importing, managing, and handling geospatial data          |\n| sfdep     | To derive tourism economy indicator layer                      |\n| tmap      | For visualizing maps                                           |\n| ggplot2   | To visualize other statistics                                  |\n| plotly    | For interactive mapping                                        |\n| Kendall   | For performing Mann Kendall test for emerging hotspot analysis |\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse,corrplot, sf, sfdep, tmap, ggplot2, plotly, Kendall)\n```\n:::\n\n:::\n\n------------------------------------------------------------------------\n\n# 3 Data Preparation\n\n## 3.1 The Datasets\n\nFor the purpose of this analysis, two datasets are utilized to explore the spatial and spatio-temporal patterns of Thailand’s tourism economy.\n\n1.  **Thailand Domestic Tourism Statistics (version 2)** from Kaggle, provides detailed tourism-related data such as monthly revenue receipts and visitor counts at the provincial level. This dataset is critical for analyzing economic trends within the tourism sector and identifying regional disparities in tourism activities across different provinces in Thailand.\n2.  **Thailand - Subnational Administrative Boundaries** from the Humanitarian Data Exchange (HDX), provides geographic boundary data at the provincial level. This dataset offers the spatial context required for mapping and conducting spatial autocorrelation and hotspot analysis, linking tourism statistics to specific geographic regions across Thailand.\n\nThese datasets together enable a comprehensive geospatial analysis of the tourism economy, facilitating both spatial and temporal investigations into tourism clusters, outliers, and emerging hot spots or cold spots across Thailand’s provinces.\n\n## 3.2 Import the Data\n\n### 3.2.1 Aspatial Data\n\nThe *Thailand Domestic Tourism Statistics* dataset from 2019-2023, was imported by using *read_csv()* package.\n\nThen, the data was prepared for analysis with the following steps:\n\n-   **`pivot_wider()`** function was used to reshape the dataset by transforming the long format (multiple rows per `date` & `province_eng`) into a wide format (one row per `date`& `province_eng` combination). This transposes the variables and assign corresponding values in the cells.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism <- read_csv(\"data/rawdata/thailand_domestic_tourism_2019_2023_ver2.csv\")%>%\n  pivot_wider(\n    names_from = variable,  \n    values_from = value)\n```\n:::\n\n\nWe visualize which province contributes the highest tourism revenue to roughly understand areas where tourism is a key economic driver, providing more relevant insights into spatial and temporal tourism trends.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nHere, we noted that revenue is quite skewed and unevenly distributed.\n\nWe will also see if there is any correlation among our three chosen tourism economy indicators.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nFrom viewing the correlation analysis, we see that `revenue_all` and `no_tourist_foreign` have a high correlation of 0.96. However, we will still choose `no_tourist_foreign` as one of our tourism economy indicators because the number of foreign tourists provides direct insights into international tourism demand and its influence on local economies. While highly correlated with revenue, `no_tourist_foreign` captures the volume of international visitors, which is crucial for understanding trends in foreign market engagement, the potential for tourism-driven economic policies, and the impact of external factors such as global travel restrictions.\n\nWe are now ready to select relevant rows in our dataset using ***select()*** as shown in code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism <- tourism %>%\n  select(date, province_eng, ratio_tourist_stay, no_tourist_foreign, revenue_all)\n```\n:::\n\n\nWe will use ***glimpse()*** to quickly check the attributes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(tourism)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,850\nColumns: 5\n$ date               <date> 2019-01-01, 2019-01-01, 2019-01-01, 2019-01-01, 20…\n$ province_eng       <chr> \"Bangkok\", \"Lopburi\", \"Phra Nakhon Si Ayutthaya\", \"…\n$ ratio_tourist_stay <dbl> 93.37, 61.32, 73.37, 67.33, 79.31, 71.70, 64.65, 71…\n$ no_tourist_foreign <dbl> 2425014, 2363, 168776, 5836, 559, 11699, 248, 5281,…\n$ revenue_all        <dbl> 81926490000, 457240000, 1438730000, 347790000, 1017…\n```\n\n\n:::\n:::\n\n\nLastly, we will save the prepared dataframe into rds format.\n\n::: panel-tabset\n## Save\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(tourism, \"data/rds/tourism.rds\")\n```\n:::\n\n\n## Load\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism <- read_rds(\"data/rds/tourism.rds\")\n```\n:::\n\n:::\n\n### 3.2.2 Geospatial Data - Study Area\n\nThe *Thailand - Subnational Administrative Boundaries* dataset, was imported by using *st_read()* package.\n\nThe dataset was prepared for analysis with the following steps:\n\n-   From a quick review of the dataset, variable ***ADM1_EN*** contains the provinces in Thailand. Since our analysis for this study is on provincial level, we will use this variable as a common variable to join with the tourism dataset. Therefore, we need to change the name of this variable to 'province_eng' to make it a common variable with the Tourism Statistics dataset.\n\n-   We will use st_transform to reproject coordinate reference system to EPSG: 32647 for Thailand.\n\n-   Change the spelling of some provinces such as Chon Buri to \"Chonburi\" to be the same as the way it was spelled in Tourism Statistics dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthaibounds <- st_read(dsn = \"data/rawdata/\", \n                      layer = \"tha_admbnda_adm2_rtsd_20220121\",\n                      crs=4326) %>%\n  st_transform(crs=32647) %>%\n  rename(province_eng = ADM1_EN) %>%\n  select(-date)%>%\n  mutate(province_eng = ifelse(province_eng == \"Chon Buri\", \"Chonburi\", province_eng)) %>%\n  mutate(province_eng = ifelse(province_eng == \"Lop Buri\", \"Lopburi\", province_eng)) %>%\n  mutate(province_eng = ifelse(province_eng == \"Chai Nat\", \"Chainat\", province_eng)) %>%\n  mutate(province_eng = ifelse(province_eng == \"Prachin Buri\", \"Prachinburi\", province_eng))%>%\n  mutate(province_eng = ifelse(province_eng == \"Buri Ram\", \"Buriram\", province_eng))%>%\n  mutate(province_eng = ifelse(province_eng == \"Si Sa Ket\", \"Sisaket\", province_eng))%>%\n  mutate(province_eng = ifelse(province_eng == \"Nong Bua Lam Phu\", \"Nong Bua Lamphu\", province_eng))%>%\n  mutate(province_eng = ifelse(province_eng == \"Phangnga\", \"Phang Nga\", province_eng))\n```\n:::\n\n\n::: panel-tabset\n## Save\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(thaibounds, \"data/rds/thaibounds.rds\")\n```\n:::\n\n\n## Load\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthaibounds <- read_rds(\"data/rds/thaibounds.rds\")\n```\n:::\n\n:::\n\n### 3.2.3 Creating Tourism Economy Indicators Layer\n\nNext, we will create a tourism economy indicators layer by left joining the geospatial dataframe (thaibounds) to the attribute dataframe (tourism) by using ***left_join()***.\n\n::: callout-note\n## To perform a left_join(), we must ensure that there is a common column between the two. For our case, the common column is 'province_eng'\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthai_tourism <- left_join(thaibounds,tourism)%>%\n  select(1:2, 11, 19:23)\n```\n:::\n\n\nThen, to check whether the correct columns are present and the output thai_tourism is properly joined, we will be viewing the data content using ***glimpse()***.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(thai_tourism)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 46,400\nColumns: 8\n$ Shape_Leng         <dbl> 0.08541733, 0.08541733, 0.08541733, 0.08541733, 0.0…\n$ Shape_Area         <dbl> 0.0004504685, 0.0004504685, 0.0004504685, 0.0004504…\n$ province_eng       <chr> \"Bangkok\", \"Bangkok\", \"Bangkok\", \"Bangkok\", \"Bangko…\n$ date               <date> 2019-01-01, 2020-01-01, 2021-01-01, 2022-01-01, 20…\n$ ratio_tourist_stay <dbl> 93.37, 89.36, 7.54, 26.34, 75.02, 89.19, 68.37, 9.9…\n$ no_tourist_foreign <dbl> 2425014, 2473725, 49154, 137591, 2122201, 2291482, …\n$ revenue_all        <dbl> 81926490000, 88202890000, 9539730000, 11823610000, …\n$ geometry           <MULTIPOLYGON [m]> MULTIPOLYGON (((662263.2 15..., MULTIP…\n```\n\n\n:::\n:::\n\n\nNow that we see the dataset is prepared, we will save it in rds format.\n\n::: panel-tabset\n## Save\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(thai_tourism, \"data/rds/thai_tourism.rds\")\n```\n:::\n\n\n## Load\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthai_tourism <- read_rds(\"data/rds/thai_tourism.rds\")\n```\n:::\n\n:::\n\n### 3.2.4 Derived Tourism Economy Indicators Layer in spacetime\n\nLastly, for our emerging hotspot analysis in later sections, we will have to derive a study area layer in **spacetime s3 class of sfdep.**\n\n::: callout-note\n## We use the `sfdep` package over `spdep` in this study due to its enhanced functionality and flexibility in handling modern spatial data formats, particularly `sf` (simple features) objects. Unlike `spdep`, which requires more manual steps to manage spatial objects and coordinate systems, `sfdep` seamlessly integrates spatial data processing with `sf` objects, making it more appropriate for our study's workflow.\n:::\n\nTo convert the data into `spacetime` format, we will take the following steps:\n\n1.  We need to convert date field to integer, lubridated with the format YYYYMM as '201901'.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    tourism <- tourism %>%\n      mutate(date_int = year(date) * 100 + month(date))\n    ```\n    :::\n\n\n2.  Since each province should only have **one** geometry (e.g., one polygon representing the whole province) we will aggregate thaibounds dataframe using ***st_union()*** and to convert all geometry types to be POLYGON in unison.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    thaibounds_agg <- thaibounds %>%\n      group_by(province_eng) %>%\n      summarise(geometry = st_union(geometry))%>%\n      mutate(geometry = st_cast(geometry, \"POLYGON\"))\n    ```\n    :::\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    write_rds(thaibounds_agg, \"data/rds/thaibounds_agg.rds\")\n    ```\n    :::\n\n    ::: {.cell}\n    \n    :::\n\n\n3.  Lastly, we convert it into a `spacetime` structure with ***spacetime()*** from `sfdep` with the following code chunk.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    tourism_spt <- spacetime(\n      .data = tourism, \n      .geometry = thaibounds_agg, \n      .loc_col = \"province_eng\", \n      .time_col = \"date_int\"\n      )\n    ```\n    :::\n\n\n4.  To verify if tourism_spt is space-time cube object we use the ***is_spacetime_cube()*** code chunk below.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    is_spacetime_cube(tourism_spt)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    \n    ```\n    [1] TRUE\n    ```\n    \n    \n    :::\n    :::\n\n\n------------------------------------------------------------------------\n\n# 4 Independence of Thailand's Tourism Economy Indicators from Space\n\n## 4.1 Global Spatial Autocorrelation Analysis\n\nGlobal Spatial Autocorrelation Analysis is a crucial method for examining the spatial dependence of economic variables, such as tourism revenue, across different regions. It tests whether the distribution of variables such as total revenue, is randomly dispersed, clustered, or exhibits a pattern based on the geographical arrangement of locations.\n\nIn this study, we apply Global Spatial Autocorrelation, specifically Moran's I, to investigate whether the tourism economy in Thailand is spatially independent or if neighboring provinces tend to have similar or dissimilar levels of tourism activity for the three economy indicators. A significant positive spatial autocorrelation would indicate clustering of similar tourism levels across provinces, while negative autocorrelation suggests dissimilar values are adjacent to one another.\n\n### 4.1.1 Method Overview\n\nWe will use the **K-nearest neighbors (KNN) approach** for computing distance-based spatial weights in our analysis of tourism economy indicators across provinces because it is the most suitable to capture local interactions among neighboring provinces, especially since the data from our chosen economy indicators are skewed. By selecting a fixed number of nearest neighbors, KNN allows us to identify patterns and relationships within the tourism data that are particularly relevant to local contexts.\n\nOn the other hand, contiguity weights, which focus on shared borders between regions, are not appropriate in this scenario because the provinces in Thailand may have significant tourism interactions even if they are not geographically adjacent. Given that tourism flows can transcend physical boundaries and depend on accessibility rather than mere contiguity, KNN provides a more relevant method for capturing the spatial relationships critical to our analysis of the tourism economy.\n\nLastly, we will use the computed KNN weights to test for independence and perform Moran I's on our chosen indicators of tourism economy.\n\n### 4.1.2 K-nearest neighbors (KNN)\n\nTo find the K-nearest neighbor distance we will take the following steps:\n\n1.  First, we will extract the centroids of the `thai_tourism` for each province to get the coordinates for distance calculation. To overcome the issue of having multiple points for each location in the `thai_tourism` dataset (since it is a result of left join), we will now aggregate the data grouped by only province since we are not interested in time aspect here; just distance. We average ratio_tourist_stay since it is in percentage.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    agg_tourism_prov <- thai_tourism %>%\n      group_by(province_eng) %>%\n      summarize(\n        revenue_all = sum(revenue_all, na.rm = TRUE), \n        ratio_tourist_stay = mean(ratio_tourist_stay, na.rm = TRUE), \n        no_tourist_foreign = sum(no_tourist_foreign, na.rm = TRUE),\n        geometry = st_union(geometry)\n      )\n    ```\n    :::\n\n    ::: {.cell}\n    \n    :::\n\n    ::: {.cell}\n    \n    :::\n\n\n2.  We extract unique locations by using the `province_eng` column to ensure each province has a single point (centroid). Then, we compute centroids for the unique provinces using `st_centroid()` with the code chunk below.\n\n    ::: panel-tabset\n    ## Code\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    province_centroids <- agg_tourism_prov %>%\n      st_centroid() %>%  \n      select(province_eng, geometry)\n    ```\n    :::\n\n    ::: {.cell}\n    \n    :::\n\n    ::: {.cell}\n    \n    :::\n\n\n    ## Plot\n\n    To ensure the centroids are in proper locations and not located in the water\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    tmap_mode('plot')\n    tm_shape(thaibounds) +\n      tm_fill(col = \"lightgrey\") +  \n      tm_borders() +\n      tm_shape(province_centroids) +  \n      tm_dots(col = \"blue\", size = 0.2, title = \"Province Centroids\") + \n      tm_text(\"province_eng\", size = 0.7, just = \"top\", col = \"black\") +\n      tm_layout(main.title = \"Province Centroids of Thai Tourism\", main.title.size = 0.5) \n    ```\n    \n    ::: {.cell-output-display}\n    ![](Take-home_Ex02_files/figure-html/unnamed-chunk-28-1.png){width=672}\n    :::\n    :::\n\n    :::\n\n3.  After ensuring the centroids are in proper locations,we convert centroids to coordinates.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    coords <- st_coordinates(province_centroids)\n    ```\n    :::\n\n\n4.  Compute adaptive distance weight matrix with k set at 6 neighbors using ***st_knn()*** from sfdep and view the structure of the matrix\n\n::: panel-tabset\n## Calculation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn <- st_knn(province_centroids, k = 6)\n```\n:::\n\n\n## Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(knn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 77\n $ : int [1:6] 14 25 54 62 72 77\n $ : int [1:6] 7 37 46 60 63 66\n $ : int [1:6] 27 36 37 46 57 58\n $ : int [1:6] 14 28 34 35 56 73\n $ : int [1:6] 24 29 54 55 62 68\n $ : int [1:6] 3 12 26 49 53 57\n $ : int [1:6] 2 22 30 63 66 74\n $ : int [1:6] 17 22 24 29 34 42\n $ : int [1:6] 6 12 49 53 55 71\n $ : int [1:6] 11 19 20 23 41 47\n $ : int [1:6] 10 19 20 32 41 47\n $ : int [1:6] 3 6 9 49 53 57\n $ : int [1:6] 18 31 39 50 51 67\n $ : int [1:6] 17 24 25 54 56 77\n $ : int [1:6] 30 44 45 65 69 74\n $ : int [1:6] 2 7 27 52 66 74\n $ : int [1:6] 8 14 24 34 54 73\n $ : int [1:6] 31 39 40 48 67 70\n $ : int [1:6] 10 20 41 47 65 75\n $ : int [1:6] 10 19 23 47 65 69\n $ : int [1:6] 34 35 42 45 73 75\n $ : int [1:6] 2 7 26 46 60 63\n $ : int [1:6] 10 11 19 20 41 47\n $ : int [1:6] 5 14 17 54 68 77\n $ : int [1:6] 1 14 28 54 56 77\n $ : int [1:6] 3 6 37 46 49 60\n $ : int [1:6] 3 36 37 46 58 59\n $ : int [1:6] 4 14 25 56 73 77\n $ : int [1:6] 5 8 22 26 49 60\n $ : int [1:6] 7 15 22 44 63 74\n $ : int [1:6] 18 39 40 48 67 70\n $ : int [1:6] 11 19 21 41 47 75\n $ : int [1:6] 38 40 61 64 70 76\n $ : int [1:6] 8 14 17 21 35 73\n $ : int [1:6] 4 14 21 34 56 73\n $ : int [1:6] 3 27 37 46 57 58\n $ : int [1:6] 3 26 27 36 46 57\n $ : int [1:6] 33 40 61 64 70 76\n $ : int [1:6] 18 31 48 51 67 70\n $ : int [1:6] 18 31 38 61 64 70\n $ : int [1:6] 10 11 19 32 47 75\n $ : int [1:6] 8 21 22 30 44 45\n $ : int [1:6] 27 36 50 52 58 59\n $ : int [1:6] 7 15 30 42 45 65\n $ : int [1:6] 15 21 42 44 65 75\n $ : int [1:6] 2 3 27 36 37 60\n $ : int [1:6] 19 20 32 41 65 75\n $ : int [1:6] 18 31 39 40 67 70\n $ : int [1:6] 6 12 26 37 55 60\n $ : int [1:6] 13 43 52 57 58 59\n $ : int [1:6] 13 18 31 39 48 67\n $ : int [1:6] 3 27 36 43 58 59\n $ : int [1:6] 3 6 9 12 57 71\n $ : int [1:6] 1 14 24 25 68 77\n $ : int [1:6] 5 6 9 26 29 49\n $ : int [1:6] 4 14 25 28 35 73\n $ : int [1:6] 3 12 27 36 37 58\n $ : int [1:6] 3 27 36 52 57 59\n $ : int [1:6] 3 27 36 43 52 58\n $ : int [1:6] 2 22 26 37 46 63\n $ : int [1:6] 31 38 40 64 70 76\n $ : int [1:6] 1 5 54 68 72 77\n $ : int [1:6] 2 7 22 46 60 66\n $ : int [1:6] 33 38 40 61 70 76\n $ : int [1:6] 15 19 45 47 69 75\n $ : int [1:6] 2 7 16 27 46 63\n $ : int [1:6] 13 18 31 39 48 51\n $ : int [1:6] 5 24 54 62 72 77\n $ : int [1:6] 15 20 30 44 65 74\n $ : int [1:6] 18 31 40 48 61 64\n $ : int [1:6] 6 9 12 49 53 55\n $ : int [1:6] 1 25 54 62 68 77\n $ : int [1:6] 4 14 17 34 35 56\n $ : int [1:6] 7 15 16 30 63 66\n $ : int [1:6] 19 21 32 45 47 65\n $ : int [1:6] 33 38 40 61 64 70\n $ : int [1:6] 1 14 25 54 62 72\n - attr(*, \"region.id\")= chr [1:77] \"1\" \"2\" \"3\" \"4\" ...\n - attr(*, \"call\")= language spdep::knearneigh(x = pnts, k = k)\n - attr(*, \"sym\")= logi FALSE\n - attr(*, \"type\")= chr \"knn\"\n - attr(*, \"knn-k\")= num 6\n - attr(*, \"class\")= chr [1:2] \"nb\" \"list\"\n```\n\n\n:::\n:::\n\n:::\n\nLastly we compute the KNN distance matrix weights using ***st_weights()*** from sfdep with the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_weights <- st_weights(knn, style = \"W\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n### 4.1.3 Performing Global Moran's I\n\nNow that we have the KNN weights ready, we can perform global spatial autocorrelation analysis.\n\nTo measure the degree to which similar or dissimilar values are clustered in space, we will performing Global Moran's I. If the indicators are independent of space, Moran's I should show no significant spatial autocorrelation. The following is the hypothesis that we would like to test.\n\n-   **Null Hypothesis (H0):** The tourism economy indicators are spatially independent (randomly distributed in space).\n\n-   **Alternative Hypothesis (H1) :** There is spatial dependence, indicating that similar values are clustered or dispersed.\n\nThe 95% confident interval will be used. (Significance level of 0.05)\n\nWe will use `global_moran()` function from ***sfdep*** package to compute the Global Moran's I value for our three chosen indicator of tourism economy.\n\n::: panel-tabset\n## Total Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran(agg_tourism_prov$revenue_all, \n                       knn, \n                       knn_weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] -0.02579891\n\n$K\n[1] 73.48954\n```\n\n\n:::\n:::\n\n\nThe Moran’s I value is negative and close to zero, indicating a slight tendency toward spatial dispersion or randomness. However, since the value is small, this suggests that the revenue distribution does not show strong evidence of spatial clustering or dispersion. It is likely that revenue values are fairly random across provinces.\n\n## Occupancy Rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran(agg_tourism_prov$ratio_tourist_stay, \n                       knn, \n                       knn_weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] -0.08109265\n\n$K\n[1] 10.7366\n```\n\n\n:::\n:::\n\n\nThe Moran’s I value is also negative, meaning that areas with high occupancy rates tend to be randomn. The value is slightly higher than revenue's indicating a slightly higher spatial autocorrelation.\n\n## Number of Foreign Tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran(agg_tourism_prov$no_tourist_foreign, \n                       knn, \n                       knn_weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$I\n[1] -0.01733206\n\n$K\n[1] 73.06272\n```\n\n\n:::\n:::\n\n\nThe Moran’s I value for the number of foreign tourists is also negative but very close to zero, indicating little spatial autocorrelation. This suggests that the spatial distribution of foreign tourists across provinces is relatively random, with no strong evidence of clustering or dispersion.\n:::\n\nThen Moran's I test will be performed using `global_moran_test()` to understand deeper with a p-value.\n\n::: panel-tabset\n## Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test(agg_tourism_prov$revenue_all, \n                       knn, \n                       knn_weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = -1.2705, p-value = 0.898\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n    -2.579891e-02     -1.315789e-02      9.900216e-05 \n```\n\n\n:::\n:::\n\n\nSince the p-value (0.898) is greater than 0.05, we **fail to reject the null hypothesis**.\n\n## Occupancy Rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test(agg_tourism_prov$ratio_tourist_stay, \n                       knn, \n                       knn_weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = -1.2199, p-value = 0.8887\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n     -0.081092653      -0.013157895       0.003101321 \n```\n\n\n:::\n:::\n\n\nSince the p-value (0.8887) is greater than 0.05, we **fail to reject the null hypothesis**, meaning that it is spatially independent (randomly distributed in space) for occupancy rate as well.\n\n## Number of Foreign Tourist\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_test(agg_tourism_prov$no_tourist_foreign, \n                       knn, \n                       knn_weights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = -0.38197, p-value = 0.6488\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n    -0.0173320551     -0.0131578947      0.0001194228 \n```\n\n\n:::\n:::\n\n\nSince the p-value (0.6488) is greater than 0.05, we **fail to reject the null hypothesis**.\n:::\n\nThis indicates that there is no significant spatial autocorrelation in all three chosen indicators and the distribution is random.\n\nTo confirm this conclusion, we will perform the statistical test with Monte Carlo simulation, using the `global_moran_perm()` as shown in the code chunk below.\n\nFirst, we will set the seed at a random number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n\n\n::: panel-tabset\n## Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(agg_tourism_prov$revenue_all, \n                       knn, \n                       knn_weights,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.025799, observed rank = 7, p-value = 0.14\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nSince the p-value (0.14) is greater than 0.05, we **fail to reject the null hypothesis**.\n\n## Occupancy Rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(agg_tourism_prov$ratio_tourist_stay, \n                       knn, \n                       knn_weights,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.081093, observed rank = 10, p-value = 0.2\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe p-value (0.2) is also greater than 0.05, leading us to **fail to reject the null hypothesis**.\n\n## Number of Foreign Tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(agg_tourism_prov$no_tourist_foreign, \n                       knn, \n                       knn_weights,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.017332, observed rank = 36, p-value = 0.72\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe p-value (0.72) is substantially greater than 0.05, resulting in a **failure to reject the null hypothesis**.\n:::\n\nFor all the indicators, the Monte Carlo simulations reinforce the earlier conclusions, showing no significant spatial autocorrelation. This suggests that for all three variables, there is no significant spatial autocorrelation present, and their distributions appear to be random rather than clustered or dispersed.\n\n------------------------------------------------------------------------\n\n## 4.2 Local Spatial Autocorrelation Analysis\n\n**Local Moran's I**, also known as **Local Indicator of Spatial Association (LISA)**, is a spatial statistical measure used to identify clusters or spatial autocorrelation at a local level (provinces), rather than globally. While Global Moran’s I evaluates the overall spatial autocorrelation across a dataset, Local Moran’s I detects significant pockets of clustering (high-high or low-low) or outliers (high-low or low-high) by evaluating each individual observation and its relationship to neighboring observations. This test helps pinpoint areas where spatial autocorrelation may differ significantly from the global trend.\n\n-   N**ull hypothesis (H0)**: there is **no local spatial autocorrelation**, meaning the observed value at each province is independent of the values at neighboring provinces.\n\n-   **Alternative hypothesis (H1)** is that there is **local spatial autocorrelation**, indicating that similar values are spatially clustered together or dispersed in specific areas.\n\n### 4.2.1 Computing Local Moran's I for Total Revenue\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrev_local_moranI <- local_moran(agg_tourism_prov$revenue_all, \n                                   knn,\n                                   knn_weights,\n                                   nsim = 999)\nrev_lisa_df <- as.data.frame(rev_local_moranI)\n\nrev_tourism_lisa <- agg_tourism_prov %>%\n  mutate(ii = rev_lisa_df$ii, \n         p_ii_sim = rev_lisa_df$p_ii_sim,\n         p_ii = rev_lisa_df$p_ii,\n         mean = rev_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n\n## Visualize Local Moran's I and p-value\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n:::\n\n-   Local Moran's I of Revenue: Bangkok exhibit the strongest negative spatial autocorrelation for revenue, suggesting it is the spatial outlier in comparison to its neighbors. The majority of the provinces have values closer to zero, indicating a more neutral or weak spatial correlation for revenue. Chonburi has the strongest positive spatial autocorrelation. This is explained further in ***section 4.2.4***.\n\n-   P-value of Local Moran: The p-values of all provinces are not significant for most part of the country except for some central provinces such as Samut Sakhon, Ratchaburi, Phra Nakhon Si Ayutthaya, Samut Songkhram, Nonthaburi and Chonburi. Since their p-value is less than our level of significance at 0.05, we **reject the null hypothesis** for these provinces. This means that there is **local spatial autocorrelation in these provinces**, indicating that similar values of total revenue are spatially clustered together.\n\nWe can also plot the LISA map.\n\nA **LISA map** is a categorical representation highlighting clusters and outliers in spatial data. The map identifies two types of outliers: High-Low, where areas with high values are surrounded by areas with low values, and Low-High, where areas with low values are surrounded by high-value areas. Similarly, it identifies two types of clusters: High-High clusters, where areas with high values are surrounded by other high-value areas, and Low-Low clusters, where low-value areas are surrounded by other low-value areas. The LISA map is derived by combining the local Moran’s I statistic for each geographical area with its corresponding p-values, providing an interpreted spatial pattern of association.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_sig <- rev_tourism_lisa  %>%\n  filter(p_ii_sim < 0.05)\n\nplot3 <- tm_shape(rev_tourism_lisa) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\n  tm_layout(\n    main.title = \"LISA Map\",\n    main.title.size = 0.5,  \n    legend.text.size = 0.5\n  ) +\ntm_shape(lisa_sig) +\n  tm_fill(\"mean\") + \n  tm_borders(alpha = 0.4)\n\n\ntmap_arrange(basic,plot3)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n-   **Low-Low (Nakhon Sawan, Roi Et, Ubon Ratchathani)**: These provinces are classified as \"Low-Low,\" meaning that they have low values of revenue, and they are surrounded by neighboring provinces that also exhibit low revenue values. This suggests a localized cluster of low revenue in these regions, where both the province and its neighbors show poor performance in generating tourism-related revenue.\n\n-   **Low-High (Rayong, Chachoengsao)**: These provinces are classified as \"Low-High,\" meaning that they have relatively low revenue values but are surrounded by provinces with high revenue. This suggests that Rayong and Chachoengsao may be underperforming relative to their neighboring regions, indicating potential issues or challenges in these specific provinces that result in lower tourism revenue compared to nearby areas.\n\n### 4.2.2 Computing Local Moran's I for Occupancy Rate\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_local_moranI <- local_moran(agg_tourism_prov$ratio_tourist_stay, \n                                   knn, \n                                   knn_weights, \n                                   nsim = 999)\nor_lisa_df <- as.data.frame(or_local_moranI)\n\nor_tourism_lisa <- agg_tourism_prov %>%\n  mutate(ii = or_lisa_df$ii, \n         p_ii_sim = or_lisa_df$p_ii_sim,\n         p_ii = or_lisa_df$p_ii,\n         mean = or_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n\n## Visualize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n:::\n\n-   Local Moran's I of Occupancy Rate: Bangkok and Nakhon Ratchasima exhibit the strongest negative spatial autocorrelation for revenue, suggesting they are the spatial outlier in comparison to its neighbors,while the rest of the provinces have values closer to zero. Chiang Rai has the highest positive spatial autocorrelation.\n\n-   P-value of Local Moran: The p-values of all provinces are not significant, indicating that **null hypothesis should not be rejected**. For occupancy rate, there is **no local spatial autocorrelation.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_lisa_sig <- or_tourism_lisa  %>%\n  filter(p_ii_sim < 0.05)\n\ntmap_mode(\"plot\")\n\nor_plot4 <- tm_shape(or_tourism_lisa) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\n  tm_layout(\n    main.title = \"LISA Map\",\n    main.title.size = 0.5,  \n    legend.text.size = 0.5) +\ntm_shape(or_lisa_sig) +\n  tm_fill(\"mean\") + \n  tm_borders(alpha = 0.4)\n\n\ntmap_arrange(basic,or_plot4)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\n**High-Low (Nakhon Sawan, Nakhon Ratchasima)**: Provinces classified as \"High-Low\" indicate that these provinces have relatively high occupancy rates, but they are surrounded by provinces with low occupancy rates. This pattern suggests that Nakhon Sawan and Nakhon Ratchasima have stronger hotel occupancy despite being located near provinces where occupancy rates are lower. This could be due to local attractions, tourism infrastructure, or other factors that make these provinces more appealing to tourists, even though neighboring regions are less successful in attracting or accommodating tourists.\n\n### 4.2.3 Computing Local Moran's I for Number of Foreign Tourists\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft_local_moranI <- local_moran(agg_tourism_prov$ratio_tourist_stay, \n                                   knn, \n                                   knn_weights, \n                                   nsim = 999)\nft_lisa_df <- as.data.frame(ft_local_moranI)\n\nft_tourism_lisa <- agg_tourism_prov %>%\n  mutate(ii = ft_lisa_df$ii, \n         p_ii_sim = ft_lisa_df$p_ii_sim,\n         p_ii = ft_lisa_df$p_ii,\n         mean = ft_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n\n## Visualize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n:::\n\n-   Local Moran's I of Occupancy Rate: Similarly as occupancy rate, Bangkok and Nakhon Ratchasima exhibit the strongest negative spatial autocorrelation for revenue, suggesting they are the spatial outlier in comparison to its neighbors. Again, Chiang Rai has the highest positive spatial autocorrelation. The rest of the provinces have values closer to zero.\n\n-   P-value of Local Moran: The p-values of all provinces are not significant, indicating that **null hypothesis should not be rejected**. For number of foreign tourist, there is **no local spatial autocorrelation.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft_lisa_sig <- ft_tourism_lisa  %>%\n  filter(p_ii_sim < 0.05)\n\nft_plot3 <- tm_shape(ft_tourism_lisa) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\n  tm_layout(\n    main.title = \"LISA Map\",\n    main.title.size = 0.5,  \n    legend.text.size = 0.5\n  ) +\ntm_shape(ft_lisa_sig) +\n  tm_fill(\"mean\") + \n  tm_borders(alpha = 0.4)\n\n\ntmap_arrange(basic,ft_plot3)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n**High-Low (Nakhon Sawan, Nakhon Ratchasima)**: Same as occupancy rate, this classification indicates that Nakhon Sawan and Nakhon Ratchasima have a high number of foreign tourists relative to its neighboring provinces, which have a lower number of foreign tourists. This could imply that these regioins has a unique attraction or infrastructure that draws foreign tourists, while its neighbors are not as successful in attracting international visitors. This is notable because these two provinces stands out in the region despite a general lack of foreign tourist inflow in nearby provinces.\n\n### 4.2.4 Interpretation of Strongest Negative & Positive Moran's I Statistics\n\n[**Bangkok- Highest Negative For All Indicators**]{.underline}\n\nBangkok has the most negative Local Moran’s I statistic consistently for all three tourism economy indicators suggesting that, despite its high tourism revenue, the spatial pattern of tourism revenue in Bangkok is more out of sync with its neighboring provinces. This could happen for the following reasons:\n\n1.  **High Concentration of Tourism Activity**: Bangkok’s tourism revenue may be extremely concentrated within a few key areas, while surrounding provinces generate much less revenue. This creates a situation where Bangkok stands out significantly compared to its neighbors, resulting in a negative Local Moran’s I.\n\n2.  **Uneven Distribution of Tourism**: While Bangkok itself is a tourism hotspot, the neighboring provinces may not benefit equally from the tourism flow, leading to spatial dispersion. This contrast in tourism revenue between Bangkok and its neighbors drives the negative spatial autocorrelation.\n\n[**Chonburi - Highest Positive Moran's I for Revenue**]{.underline}\n\n1.  **Tourism and Economic Hub**: Chonburi’s high positive Moran’s I for revenue means that Chonburi, along with its neighboring provinces, is part of a cluster where tourism revenue is consistently high. Chonburi’s strong attractions like Pattaya and its proximity to Bangkok draw significant tourist spending.\n\n2.  **Coastal Appeal**: Chonburi is a popular destination for both international and domestic tourists, particularly for its beach resorts and recreational activities. This translates into higher spending on hotels, restaurants, and entertainment, contributing to its high tourism revenue (Tourism Authority of Thailand).\n\n[**Chiang Rai - Highest Positive Moran's I for Occupancy Rate and Number of Foreign Tourists**]{.underline}\n\n1.  **Niche International Appeal**: Chiang Rai, located in northern Thailand, is less commercially developed compared to Chonburi but has a strong appeal to foreign tourists interested in cultural experiences, eco-tourism, and the scenic landscapes of the Golden Triangle (Betgem, n.d.). This could explain its high positive Moran’s I for the number of foreign tourists. Chiang Rai is often visited by tourists seeking a more tranquil and unique experience compared to the coastal resorts.\n\n2.  **High Occupancy Rate**: The high Moran's I for occupancy rate suggests that hotels in Chiang Rai are consistently full compared to surrounding provinces. This could be because Chiang Rai has a more limited supply of accommodations relative to demand, especially during peak travel seasons when foreign tourists flock to the area for cultural and nature-based tourism.\n\n------------------------------------------------------------------------\n\n# 5 Independence of Thailand's Tourism Economy Indicators from Space and Time : A Pre, During, and Post-COVID Analysis\n\nThe tourism economy of Thailand has undergone significant transformations across various temporal phases, particularly pre, during, and post-COVID-19. Before the pandemic, Thailand's tourism industry flourished, characterized by robust growth and geographical concentration in aforementioned key areas. However, the onset of COVID-19 brought disruptions, leading to a drastic decline in both domestic and international travel, which raised questions about the space and time dependencies of tourism-related indicators. As the world transitions into a post-pandemic phase, the focus shifts towards understanding whether the key indicators of Thailand's tourism economy, such as foreign visitor numbers, revenue, and the rate of occupancy, are influenced by spatial dimensions and time variables, or if they exhibit independence from these factors. Now that we have uncovered independence of Thailand's tourism economy with space, this analysis aims to uncover its intricate relationship in both space and time context.\n\n## 5.1 Splitting the Data : Defining the Temporal Terms\n\nSince our analysis is focused on impact of COVID-19 to the tourism industry in Thailand, we will split the dataset to different temporal terms: pre, during and post COVID-19 to understand the impacts of the pandemic. We determine the splitting points from the viewing the histogram below.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\nFrom the histogram, we noted that there are three temporal terms:\n\n-   Pre Covid: **Before Jan 2020** (i.e. Dec 2019 and earlier) aligned with announcement about first few covid cases from Thailand's Ministry of Public Health (Cheung, 2020)\n\n-   During Covid: **Jan 2020 - Sep 2021**\n\n-   Post Covid: **After Sep 2021**\n\nTherefore,we will be our splitting our thai_tourism dataframe into these three cross sectional terms to conduct our analysis acrocss.\n\n### 5.1.1 K-nearest neighbors (KNN) on Temporal Terms\n\nWe will now compute the weight matrix for each temporal term with the following steps:\n\n1.  First, to find centroids, we will aggregate the data; now for both space and time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagg_tourism_provtime <- thai_tourism %>%\n  group_by(province_eng, date_int) %>%\n  summarize(\n    ratio_tourist_stay = mean(ratio_tourist_stay, na.rm = TRUE),\n    no_tourist_foreign = sum(no_tourist_foreign, na.rm = TRUE),\n    revenue_all = sum(revenue_all, na.rm = TRUE),\n    geometry = st_union(geometry)\n  )\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n2.  We will split the aggregated data for each temporal term.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npre_covid <- filter(agg_tourism_provtime, date_int < \"202001\")\nduring_covid <- filter(agg_tourism_provtime, date_int >= \"202001\" & date_int < \"202109\")\npost_covid <- filter(agg_tourism_provtime, date_int >= \"202109\")\n```\n:::\n\n\n3.  Then we can now compute centroids and KNN for each of the temporal terms subsets using the code chunk below.\n\n::: panel-tabset\n## Pre Covid\n\nWe will aggregate the data to find the unique centroids for each temporal term.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npre_covid_agg <- pre_covid %>%\n  group_by(province_eng) %>%\n  summarize(\n    revenue_all = sum(revenue_all, na.rm = TRUE),\n    ratio_tourist_stay = mean(ratio_tourist_stay, na.rm = TRUE),\n    no_tourist_foreign = sum(no_tourist_foreign, na.rm = TRUE),\n    geometry = st_union(geometry)\n  )\n\npre_covid_centroids <- pre_covid_agg %>%\n  st_centroid() %>%\n  select(province_eng, geometry)\n\ncoords_pre_covid <- st_coordinates(pre_covid_centroids)\n```\n:::\n\n\nThen compute 6th nearest neighbour distance using KNN approach.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_pre_covid <- st_knn(pre_covid_centroids, k = 6)\nknn_weights_pre_covid <- st_weights(knn_pre_covid, style = \"W\")\n```\n:::\n\n\nTo check whether centroids are appropriate and not in the water, we will visualize them. tmap_mode('view') was used to check carefully but for the purpose of publishing it will now be set as 'plot'\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\ntm_shape(thaibounds) +\n  tm_fill(col = \"lightgrey\") +  \n  tm_borders() +\n  tm_shape(pre_covid_centroids) +  \n  tm_dots(col = \"blue\", size = 0.2, title = \"Province Centroids\") + \n  tm_text(\"province_eng\", size = 0.5, just = \"top\", col = \"black\") +\n  tm_layout(main.title = \"Province Centroids of Thai Tourism\", main.title.size = 0.5)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\n## During Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduring_covid_agg <- during_covid %>%\n  group_by(province_eng) %>%\n  summarize(\n    revenue_all = sum(revenue_all, na.rm = TRUE),\n    ratio_tourist_stay = mean(ratio_tourist_stay, na.rm = TRUE),\n    no_tourist_foreign = sum(no_tourist_foreign, na.rm = TRUE),\n    geometry = st_union(geometry)\n  )\n\nduring_covid_centroids <- during_covid_agg %>%\n  st_centroid() %>%\n  select(province_eng, geometry)\n\ncoords_during_covid <- st_coordinates(during_covid_centroids)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_during_covid <- st_knn(during_covid_centroids, k = 6)\nknn_weights_during_covid <- st_weights(knn_during_covid, style = \"W\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\ntm_shape(thaibounds) +\n  tm_fill(col = \"lightgrey\") +  \n  tm_borders() +\n  tm_shape(during_covid_centroids) +  \n  tm_dots(col = \"blue\", size = 0.2, title = \"Province Centroids\") + \n  tm_text(\"province_eng\", size = 0.5, just = \"top\", col = \"black\") +\n  tm_layout(main.title = \"Province Centroids of Thai Tourism\", main.title.size = 0.5)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n\n## Post Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_covid_agg <- post_covid %>%\n  group_by(province_eng) %>%\n  summarize(\n    revenue_all = sum(revenue_all, na.rm = TRUE),\n    ratio_tourist_stay = mean(ratio_tourist_stay, na.rm = TRUE),\n    no_tourist_foreign = sum(no_tourist_foreign, na.rm = TRUE),\n    geometry = st_union(geometry)\n  )\n\npost_covid_centroids <- post_covid_agg %>%\n  st_centroid() %>%\n  select(province_eng, geometry)\n\ncoords_post_covid <- st_coordinates(post_covid_centroids)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_post_covid <- st_knn(post_covid_centroids, k = 6)\nknn_weights_post_covid <- st_weights(knn_post_covid, style = \"W\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\ntm_shape(thaibounds) +\n  tm_fill(col = \"lightgrey\") +  \n  tm_borders() +\n  tm_shape(post_covid_centroids) +  \n  tm_dots(col = \"blue\", size = 0.2, title = \"Province Centroids\") + \n  tm_text(\"province_eng\", size = 0.5, just = \"top\", col = \"black\") +\n  tm_layout(main.title = \"Province Centroids of Thai Tourism\", main.title.size = 0.5)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-66-1.png){width=672}\n:::\n:::\n\n:::\n\n## 5.2 Total Revenue\n\n### 5.2.1 Global Spatial Autocorrelation Analysis\n\nWe will perform ***global_moran_perm()*** test on each of our three temporal terms with 100 Monte Carlo simulations using the code chunks below.\n\n::: panel-tabset\n## Pre Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(pre_covid_agg$revenue_all, \n                       knn_pre_covid, \n                       knn_weights_pre_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.024998, observed rank = 11, p-value = 0.22\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe slightly negative Moran's I statistic suggests weak spatial dispersion in tourism revenue, though the magnitude is very close to zero, indicating an almost random distribution.The p-value of 0.22 suggests that we **fail to reject the null hypothesis** of spatial independence, meaning that the revenue distribution during the pre-COVID period does not show significant spatial autocorrelation.\n\n## During Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(during_covid_agg$revenue_all, \n                       knn_during_covid, \n                       knn_weights_during_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.030922, observed rank = 4, p-value = 0.08\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nSimilar to pre-COVID, this negative value suggests weak spatial dispersion, but again, the magnitude is very close to zero, indicating an almost random distribution. The p-value of 0.08, again, suggests that we **fail to reject the null hypothesis** of spatial independence.\n\n## Post Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(post_covid_agg$revenue_all, \n                       knn_post_covid, \n                       knn_weights_post_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.0259, observed rank = 15, p-value = 0.3\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe results are comparable to those of the pre-COVID period, with a negative Moran's I statistic indicating spatial dispersion. With the p-value of 0.3, we **fail to reject the null hypothesis** of spatial independence. This is very similar to the pre-COVID period, with a near-random distribution. The p-value is higher, suggesting even weaker evidence of spatial autocorrelation.\n:::\n\nAcross all three periods, the consistent negative values of the Moran's I statistic indicate a trend towards spatial dispersion rather than clustering. The p-values in the all three periods remain above the common significance level (0.05), indicating a lack of evidence to reject the null hypothesis of spatial independence.\n\nOverall, these findings support the conclusion that the revenue variable exhibits independence from space across the specified time periods.\n\n### 5.2.2 Local Spatial Autocorrelation Analysis\n\n::: panel-tabset\n## Pre Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrev_pre_local_moranI <- local_moran(pre_covid_agg$revenue_all, \n                                   knn_pre_covid, \n                                   knn_weights_pre_covid,\n                                   nsim = 999)\nrev_pre_lisa_df <- as.data.frame(rev_pre_local_moranI)\n\nrev_pre_tourism_lisa <- pre_covid_agg %>%\n  mutate(ii = rev_pre_lisa_df$ii, \n         p_ii_sim = rev_pre_lisa_df$p_ii_sim,\n         p_ii = rev_pre_lisa_df$p_ii,\n         mean = rev_pre_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-71-1.png){width=672}\n:::\n:::\n\n\n**Local Moran's I**:\n\n-   **Bangkok** shows the strongest negative spatial autocorrelation for revenue, identifying it as a spatial outlier compared to its neighboring provinces. This suggests that the revenue generated from tourism in Bangkok is significantly different from adjacent areas.\n\n**P-value**:\n\n-   Most provinces across the country do not show significant spatial autocorrelation. However, several central provinces, such as Samut Prakan, Samut Sakhon, Ratchaburi, Phra Nakhon Si Ayutthaya, Samut Songkhram, Nonthaburi, and Chonburi, have p-values less than 0.05. For these provinces, we reject the null hypothesis, indicating significant local spatial autocorrelation and suggesting that tourism revenue values are spatially clustered in these areas.\n\n**LISA Map:**\n\n-   **Low-High (Chachoengsao, Nakhon Nayok, Nakhon Pathom, Nonthaburi, Pathum Thani, Phra Nakhon Si Ayutthaya, Ratchaburi, Rayong, Samut Prakan, Samut Sakhon, Samut Songkhram)**: These provinces are classified as \"Low-High,\" indicating that their revenue values are low compared to neighboring provinces, which show high revenue. This suggests that while their surrounding areas thrive economically in terms of tourism revenue, these provinces might face specific challenges or structural issues preventing them from benefiting equally from tourism.\n\n-   **High-High (Chonburi)**: Chonburi is categorized as \"High-High,\" indicating a cluster of high tourism revenue, both within the province and its neighboring regions. This suggests that Chonburi is a significant tourism hub, not only performing well itself but also likely contributing to the economic strength of surrounding areas.\n\n## During Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrev_during_local_moranI <- local_moran(during_covid_agg$revenue_all, \n                                   knn_during_covid, \n                                   knn_weights_during_covid, \n                                   nsim = 999)\nrev_during_lisa_df <- as.data.frame(rev_during_local_moranI)\n\nrev_during_tourism_lisa <- during_covid_agg %>%\n  mutate(ii = rev_during_lisa_df$ii, \n         p_ii_sim = rev_during_lisa_df$p_ii_sim,\n         p_ii = rev_during_lisa_df$p_ii,\n         mean = rev_during_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-73-1.png){width=672}\n:::\n:::\n\n\n**Local Moran's I**:\n\n-   Similar to pre-COVID, Bangkok continues to exhibit the strongest negative spatial autocorrelation, indicating it remains a spatial outlier in terms of tourism revenue. Additionally, some provinces experienced no tourist visits during the pandemic, leading to missing values for those regions.\n-   Chonburi consistenly has the strongest positive spatial autocorrelation indicating revenue is highly clustered spatially. This means that provinces near Chonburi also tend to have similar high values of tourism revenue. In other words, Chonburi's neighboring provinces are also performing similarly well in terms of tourism revenue.\n\n**P-value**:\n\n-   The p-values remain consistent with pre-COVID results, with significant local spatial autocorrelation in the central provinces mentioned earlier (Samut Prakan, Samut Sakhon, Ratchaburi, Phra Nakhon Si Ayutthaya, Samut Songkhram, Nonthaburi, and Chonburi). For these provinces, we still reject the null hypothesis, meaning that revenue values remain spatially clustered.\n\n**LISA Map:**\n\n-   The pattern of **Low-High** clusters remains unchanged from the pre-COVID period, with the same provinces (Chachoengsao, Nakhon Nayok, etc.) showing low revenue while surrounded by high-revenue provinces. This continuity may suggest that the COVID-19 pandemic did not drastically change the spatial relationships in revenue across these provinces. The persistence of these clusters indicates that economic disparities in tourism remained stable during the pandemic.\n\n-   **High-High (Chonburi)**: Like the pre-COVID period, Chonburi maintains its \"High-High\" status, continuing to be a central hub of tourism activity and revenue, even during the pandemic. This suggests resilience in Chonburi's tourism sector despite the significant disruptions caused by COVID-19.\n\n## Post Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_local_moranI <- local_moran(post_covid_agg$revenue_all, \n                                   knn_post_covid, \n                                   knn_weights_post_covid, \n                                   nsim = 999)\npost_lisa_df <- as.data.frame(post_local_moranI)\n\npost_tourism_lisa <- post_covid_agg %>%\n  mutate(ii = post_lisa_df$ii, \n         p_ii_sim = post_lisa_df$p_ii_sim,\n         p_ii = post_lisa_df$p_ii,\n         mean = post_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-75-1.png){width=672}\n:::\n:::\n\n\n**Local Moran's I**:\n\n-   Bangkok continues to exhibit the strongest negative spatial autocorrelation for revenue, suggesting it remains a spatial outlier compared to its neighboring regions.\n-   Chonburi continues to exhibit strongest positive spatial autocorrelation.\n\n**P-value**:\n\n-   The post-COVID period shows the same trend as pre- and during-COVID. Significant spatial autocorrelation is observed in the central provinces of Samut Prakan, Samut Sakhon, Ratchaburi, Phra Nakhon Si Ayutthaya, Samut Songkhram, Nonthaburi, and Chonburi, where p-values are below the 0.05 threshold. This indicates that these provinces still exhibit spatial clustering in tourism revenue.\n\n**LISA Map:**\n\n-   The **Low-High** clusters again mirror the previous periods, indicating a prolonged trend of low revenue in these provinces relative to their high-performing neighbors. This suggests that the provinces in this category did not recover or gain the same momentum in tourism revenue as their surrounding regions, even after the pandemic.\n\n-   **High-High (Chonburi)**: Chonburi continues to be a strong performer in the post-COVID period, indicating sustained high tourism revenue both in the province and its neighbors. This demonstrates the region's ability to attract tourists and maintain its position as a key tourism destination in Thailand, despite the disruptions from COVID-19.\n:::\n\nAcross all three periods—pre, during, and post-COVID—the LISA maps reveal a consistent pattern in the spatial autocorrelation of tourism revenue. The **Low-High** provinces (e.g., Chachoengsao, Nakhon Nayok, and Rayong) show persistent economic underperformance in tourism revenue despite being located near high-revenue provinces. This pattern highlights ongoing economic disparities in tourism performance across these regions. Meanwhile, **Chonburi** maintains its status as a **High-High** cluster, resilient even during the pandemic. The consistent LISA patterns suggest that while COVID-19 may have impacted overall tourism activity, the spatial dynamics of tourism revenue remained stable, with the same provinces continuing to underperform or thrive relative to their neighbors.\n\n## 5.3 Occupancy Rate\n\n### 5.3.1 Global Spatial Autocorrelation Analysis\n\n::: panel-tabset\n## Pre Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(pre_covid_agg$ratio_tourist_stay, \n                       knn_pre_covid, \n                       knn_weights_pre_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = 0.16557, observed rank = 99, p-value = 0.02\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe negative Moran's I statistic indicates a tendency toward spatial dispersion of the `ratio_tourist_stay` values rather than clustering. The p-value of 0.02 is less than the significance level (0.05), suggesting that we **reject the null hypothesis** of spatial independence.\n\n## During Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(during_covid_agg$ratio_tourist_stay, \n                       knn_during_covid, \n                       knn_weights_during_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = 0.24708, observed rank = 100, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe negative value of the Moran's I statistic once again suggests spatial dispersion. The exceptionally low p-value indicates that there is **strong evidence** to suggest spatial dependence in the data during the COVID period. The very low p-value suggests that the spatial distribution of occupancy rates is not random. Instead, there is a significant pattern in how occupancy rates are distributed across the provinces.\n\n## Post Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(post_covid_agg$ratio_tourist_stay, \n                       knn_post_covid, \n                       knn_weights_post_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = 0.21328, observed rank = 100, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nSimilar to the previous periods, the negative Moran's I statistic indicates spatial dispersion. The very low p-value also suggests that **we will reject the null hypothesis** of spatial independence. This indicates that the occupancy rates exhibit significant spatial clustering,\n:::\n\nAcross all three periods, the consistently negative values of the Moran's I statistic for `ratio_tourist_stay` imply a trend toward spatial dispersion, rather than clustering. The p-values in the pre-COVID, during COVID, and post-COVID periods all are less the standard significance level (0.05), indicating a evidence to reject the null hypothesis of spatial independence.\n\nThe ratio of tourist occupancy rate is dependent on space throughout the specified time periods, showing significant spatial autocorrelation that provinces with high occupancy rates are clustered together.\n\n### 5.3.2 Local Spatial Autocorrelation Analysis\n\n::: panel-tabset\n## Pre Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_pre_local_moranI <- local_moran(pre_covid_agg$ratio_tourist_stay, \n                                   knn_pre_covid, \n                                   knn_weights_pre_covid, \n                                   nsim = 999)\nor_pre_lisa_df <- as.data.frame(or_pre_local_moranI)\n\nor_pre_tourism_lisa <- pre_covid_agg %>%\n  mutate(ii = or_pre_lisa_df$ii, \n         p_ii_sim = or_pre_lisa_df$p_ii_sim,\n         p_ii = or_pre_lisa_df$p_ii,\n         mean = or_pre_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-80-1.png){width=672}\n:::\n:::\n\n\n**Local Moran's I**:\n\n-   **Chiang Mai** shows the strongest negative spatial autocorrelation for occupancy rate, indicating it is a spatial outlier compared to its neighboring provinces.\n\n**P-value of Local Moran**:\n\n-   The p-values for all provinces are not significant, except for **Tak, Rayong, Samut Prakan, Chiang Mai, Ratchaburi, Nakhon Si Thammarat, Pathum Thani, and Kalasin**. With a p-value below 0.05, we reject the null hypothesis for these regions, confirming the presence of local spatial autocorrelation. This indicates that similar occupancy rate values are spatially clustered in these regions and its neighboring areas.\n\n**LISA Map:**\n\n-   **Low-low(Kalasin):** Kalasin exhibits low occupancy rates and is surrounded by other provinces with similarly low rates. This indicates a region that may be facing challenges in attracting tourists, suggesting a potential need for development strategies or marketing efforts to enhance its appeal and occupancy rates.\n-   **High-low(Chiang Mai, Tak**): Both Chiang Mai and Tak have high occupancy rates but are surrounded by provinces with low occupancy rates. This suggests that these provinces are successful in attracting tourists independently, but their high occupancy does not influence the neighboring low-occupancy areas. It highlights opportunities for further regional tourism development to connect these successful areas with their less successful neighbors.\n-   **Low-High (Chachoengsao, Nakhon Si Thammarat, Pathum Thani, Ratchaburi)**: These provinces have low occupancy rates while being surrounded by high occupancy provinces. This situation suggests that they are potentially missing out on tourism opportunities that their successful neighbors enjoy. There may be opportunities for tourism development, promotion, or infrastructure improvement to increase their occupancy rates and tap into the benefits of their geographic location.\n-   **High-High (Rayong, Samut Prakan)**: Rayong and Samut Prakan have high occupancy rates and are surrounded by other provinces with high occupancy rates. This indicates a strong tourism environment.\n\n## During Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_during_local_moranI <- local_moran(during_covid_agg$ratio_tourist_stay, \n                                   knn_during_covid, \n                                   knn_weights_during_covid, \n                                   nsim = 999)\nor_during_lisa_df <- as.data.frame(or_during_local_moranI)\n\nor_during_tourism_lisa <- during_covid_agg %>%\n  mutate(ii = or_during_lisa_df$ii, \n         p_ii_sim = or_during_lisa_df$p_ii_sim,\n         p_ii = or_during_lisa_df$p_ii,\n         mean = or_during_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-82-1.png){width=672}\n:::\n:::\n\n\n**Local Moran's I**:\n\n-   **Nakhon Si Thammarat** exhibit the strongest negative spatial autocorrelation for occupancy rates, indicating that this provinces is a spatial outlier compared to their neighbors.\n\n**P-value of Local Moran**:\n\n-   The p-values are significant for some souther provinces, such as **Phang Nga** and **Surat Thani**. With p-values below 0.05, we reject the null hypothesis for these provinces, indicating the presence of local spatial autocorrelation. This suggests that they experienced spatial clustering of occupancy rates, likely forming a high-rate cluster with surrounding provinces.\n\n**LISA Map:**\n\n-   **Low-Low (Bangkok, Nonthaburi, Phang Nga, Ranong, Samut Prakan, Surat Thani):**The provinces in the Low-Low category, including major urban centers like Bangkok and Nonthaburi, experienced low occupancy rates during COVID. This situation suggests that even populous and popular areas struggled to attract tourists during the pandemic. Factors such as travel restrictions, health concerns, and changes in tourist behavior may have significantly impacted their occupancy levels.\n\n\n```{=html}\n<!-- -->\n```\n\n-   **High-Low(Nakhon Si Thammarat)**: Nakhon Si Thammarat, while having a high occupancy rate, is surrounded by provinces with low occupancy. This suggests that it successfully attracted tourists independently during COVID, potentially due to its local attractions or outdoor tourism opportunities that aligned with pandemic travel preferences. However, the isolation from neighboring low-occupancy provinces indicates that these benefits are not being shared or are not affecting the surrounding areas, meaning there is a potential for developing stronger regional tourism networks.\n\n-   **Low-High( Mae Hong Son)**: Mae Hong Son is characterized by low occupancy rates but is surrounded by high-occupancy provinces. This indicates a missed opportunity for Mae Hong Son, as it could leverage the tourism successes of its neighbors. The province may need to enhance its visibility and attractiveness to tourists or develop infrastructure to connect better with high-occupancy areas.\n\n-   **High-High (Chiang Rai, Lamphun, Phayao, Phrae, Uttaradit):** The provinces in the High-High category experienced high occupancy rates and are surrounded by other high-occupancy provinces. This suggests that these areas formed a robust tourism network. Their success during the pandemic may provide a foundation for future growth, and strategies could be developed to sustain and further enhance tourism in these interconnected areas.\n\n## Post Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_post_local_moranI <- local_moran(post_covid_agg$ratio_tourist_stay, \n                                   knn_post_covid, \n                                   knn_weights_post_covid, \n                                   nsim = 999)\nor_post_lisa_df <- as.data.frame(or_post_local_moranI)\n\nor_post_tourism_lisa <- post_covid_agg %>%\n  mutate(ii = or_post_lisa_df$ii, \n         p_ii_sim = or_post_lisa_df$p_ii_sim,\n         p_ii = or_post_lisa_df$p_ii,\n         mean = or_post_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-84-1.png){width=672}\n:::\n:::\n\n\n**Local Moran's I**:\n\n-   **There is no strongly negative Moran's I values**.\n\n-   However, Chiang Rai has a strong positive Moran's I value indicating the neigboring provinces might also have high values of occupancy rates.\n\n**P-value of Local Moran**:\n\n-   The p-values are not significant for most provinces, except for northern provinces like  **Chiang Mai**. We reject the null hypothesis for these provinces as their p-values are below 0.05. This confirms local spatial autocorrelation, indicating spatial clustering of similar occupancy rates in these provinces and their surrounding areas.\n\n**LISA Map:**\n\n-   **High-High (Chiang Mai, Chiang Rai, Mae Hong Son, Nan, Phayao)**: The provinces in the High-High category experienced high occupancy rates and are characterized by strong tourism performance. This suggests that these areas successfully attracted tourists post-COVID. Their status as high-occupancy provinces indicates a robust recovery and possibly a growing appeal as safe travel destinations.\n:::\n\nThe analysis of occupancy rates across provinces during pre-COVID, during COVID, and post-COVID periods reveals significant trends in tourism dynamics. Pre-COVID, occupancy rates in various provinces were generally robust, driven by strong domestic and international tourism. During COVID, a new pattern emerged, with provinces like Bangkok and Nonthaburi experiencing low occupancy rates due to travel restrictions, while Nakhon Si Thammarat demonstrated a unique resilience with higher occupancy despite neighboring low rates. In the post-COVID landscape, provinces such as Chiang Mai, Chiang Rai, Mae Hong Son, Nan, and Phayao emerged as high performers with strong occupancy rates, likely benefiting from effective recovery strategies.\n\n## 5.4 Number of Foreign Tourists\n\n### 5.4.1 Global Spatial Autocorrelation Analysis\n\n::: panel-tabset\n## Pre Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(pre_covid_agg$no_tourist_foreign, \n                       knn_pre_covid, \n                       knn_weights_pre_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.014812, observed rank = 50, p-value = 1\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe negative Moran's I statistic indicates a tendency toward spatial dispersion of the number of foreign tourists, suggesting that areas with a high number of foreign tourists are not clustered together. The p-value of 1 is greater than the level of signifcants, therefore **we fail to reject** **null hypothesis** of spatial independence.\n\n## During Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(during_covid_agg$no_tourist_foreign, \n                       knn_during_covid, \n                       knn_weights_during_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.018951, observed rank = 26, p-value = 0.52\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nAgain, the negative value of the Moran's I statistic suggests spatial dispersion. The p-value of 0.52 indicates that we also **fail to reject the null hypothesis** during the COVID period.\n\n## Post Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_moran_perm(post_covid_agg$no_tourist_foreign, \n                       knn_post_covid, \n                       knn_weights_post_covid,\n                       nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 100 \n\nstatistic = -0.022147, observed rank = 18, p-value = 0.36\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe negative Moran's I statistic indicates spatial dispersion, consistent with previous findings. The p-value of 0.36 is also significantly higher than the conventional significance level, leading us to **fail to reject the null hypothesis** of spatial independence.\n:::\n\nAcross all three periods, the consistently negative values of the Moran's I statistic for `no_tourist_foreign` indicate a trend toward spatial dispersion rather than clustering. The p-values across all peroids all exceed the standard significance level (0.05), indicating a lack of evidence to reject the null hypothesis of spatial independence.\n\nThe number of foreign tourists is independent from space throughout the specified time periods, showing no significant spatial autocorrelation.\n\n### 5.4.2 Local Spatial Autocorrelation Analysis\n\n::: panel-tabset\n## Pre Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft_pre_local_moranI <- local_moran(pre_covid_agg$no_tourist_foreign, \n                                   knn_pre_covid, \n                                   knn_weights_pre_covid, \n                                   nsim = 999)\nft_pre_lisa_df <- as.data.frame(ft_pre_local_moranI)\n\nft_pre_tourism_lisa <- pre_covid_agg %>%\n  mutate(ii = ft_pre_lisa_df$ii, \n         p_ii_sim = ft_pre_lisa_df$p_ii_sim,\n         p_ii = ft_pre_lisa_df$p_ii,\n         mean = ft_pre_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-89-1.png){width=672}\n:::\n:::\n\n\n-   **Local Moran's I**:\n\n    -   **Bangkok** shows the strongest negative spatial autocorrelation.\n\n    -   **Chonburi** has the strongest positive spatial autocorrelation, indicating that Chonburi and its neighboring provinces might be a popular foreign tourist destination.\n\n-   **P-value of Local Moran**:\n\n    -   The p-values for all provinces except **Nonthaburi**, **Nakhon Nayok**, **Samut Sakhon**, **Chachoengsao**, **Chonburi**, **Rayong**, **Nakhon Pathom**, **Samut Prakan**, **Pathum Thani**, **Phra Nakhon Si Ayutthaya**, **Ratchaburi**, and **Samut Songkhram** are not significant.\n\n    -   For these 12 provinces, we reject the null hypothesis at the 0.05 significance level, indicating the presence of local spatial autocorrelation. This means that these provinces exhibit significant patterns in foreign tourist numbers, either clustering with similar values or differing significantly from their neighbors.\n\n-   **LISA Map**:\n\n    -   **Low-High** clusters are seen in several provinces, including **Nonthaburi**, **Nakhon Nayok**, **Samut Sakhon**, **Chachoengsao**, **Rayong**, and others. This suggests that these provinces experienced lower numbers of foreign tourists compared to their neighbors, possibly due to less developed tourism infrastructure or less attraction to foreign tourists.\n\n    -   **High-High** clusters are observed in **Chonburi** and **Phra Nakhon Si Ayutthaya**, indicating that these provinces had significantly higher foreign tourist numbers, likely due to their established reputation as major tourist destinations.\n\n## During Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft_during_local_moranI <- local_moran(during_covid_agg$no_tourist_foreign, \n                                   knn_during_covid, \n                                   knn_weights_during_covid, \n                                   nsim = 999)\nft_during_lisa_df <- as.data.frame(ft_during_local_moranI)\n\nft_during_tourism_lisa <- during_covid_agg %>%\n  mutate(ii = ft_during_lisa_df$ii, \n         p_ii_sim = ft_during_lisa_df$p_ii_sim,\n         p_ii = ft_during_lisa_df$p_ii,\n         mean = ft_during_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-91-1.png){width=672}\n:::\n:::\n\n\n-   **Local Moran's I**:\n\n    -   Similar to the pre-COVID period, **Bangkok** exhibits the strongest negative spatial autocorrelation.\n\n    -   **Chonburi** continues to show the strongest positive spatial autocorrelation, implying it maintained higher foreign tourist numbers than surrounding provinces, even during the pandemic.\n\n-   **P-value of Local Moran**:\n\n    -   The significance patterns remain the same, with only the 12 provinces mentioned above showing significant p-values. This suggests that local spatial autocorrelation persists in these areas during the pandemic, indicating that their patterns of foreign tourist distribution remained consistent.\n\n-   **LISA Map**:\n\n    -   Many of the same **Low-High** clusters are still present, such as in **Samut Prakan**, **Samut Songkhram**, **Chachoengsao**, **Nakhon Pathom**, and others. This suggests that the pandemic did not change the relative distribution of foreign tourists in these areas—they remained low compared to their neighbors.\n\n    -   **High-High** cluster persists in **Chonburi** and **Phra Nakhon Si Ayutthaya**, which likely maintained relatively higher foreign tourist numbers during the pandemic due to its international connections, despite overall global declines in tourism.\n\n## Post Covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft_post_local_moranI <- local_moran(post_covid_agg$no_tourist_foreign, \n                                   knn_post_covid, \n                                   knn_weights_post_covid, \n                                   nsim = 999)\nft_post_lisa_df <- as.data.frame(ft_post_local_moranI)\n\nft_post_tourism_lisa <- post_covid_agg %>%\n  mutate(ii = ft_post_lisa_df$ii, \n         p_ii_sim = ft_post_lisa_df$p_ii_sim,\n         p_ii = ft_post_lisa_df$p_ii,\n         mean = ft_post_lisa_df$mean,\n         .before = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-93-1.png){width=672}\n:::\n:::\n\n\n-   **Local Moran's I**:\n\n    -   Once again, **Bangkok** exhibits the strongest negative spatial autocorrelation.\n\n    -   **Chonburi** retains the strongest positive spatial autocorrelation, suggesting that even after the pandemic, it has recovered and continues to attract more foreign tourists than neighboring provinces.\n\n-   **P-value of Local Moran**:\n\n    -   Similar to pre- and during-COVID results, only the same 12 provinces have significant p-values. The persistence of this pattern post-COVID indicates that these areas exhibit consistent spatial patterns in foreign tourist numbers, either clustering or diverging from neighboring provinces\n\n-   **LISA Map**:\n\n    -   **Low-High** clusters remain in many of the same provinces as pre- and during-COVID periods, including **Pathum Thani**, **Ratchaburi**, **Chachoengsao**, **Samut Prakan**, and **Nakhon Nayok**, indicating continued challenges in attracting foreign tourists in these provinces relative to their neighbors.\n\n    -   **High-High** cluster in **Chonburi** remains post-COVID, showing resilience in recovering foreign tourism after the pandemic, likely due to strong international appeal.\n:::\n\nThroughout the pre, during, and post-COVID periods, we observe a consistent pattern where Chonburi stands out as a High-High cluster, attracting large numbers of foreign tourists. In contrast, provinces such as Nonthaburi, Samut Prakan, Nakhon Nayok, and Chachoengsao consistently form Low-High clusters, indicating that foreign tourism in these areas has lagged behind their neighbors. The pandemic had a limited impact on shifting these clusters, though foreign tourist numbers likely decreased across the board.\n\n## 5.5 Overall Results and Policy Suggestions from Space & Time Analysis\n\nThe three variables—revenue, occupancy rate, and number of foreign tourists—show consistent patterns of local spatial autocorrelation. Across all three periods, **Bangkok** consistently shows negative spatial autocorrelation for foreign tourist numbers, suggesting that it stands out among the neighbours. **Chonburi**, on the other hand, consistently exhibits positive spatial autocorrelation, confirming its strength as a foreign tourist hotspot and maintaining high revenue, occupancy, and foreign tourist numbers across all periods\n\nAlthough there are some shifts in occupancy rate clusters during the pandemic, the broader spatial patterns remain generally consistent across pre, during, and post-COVID periods.\n\nWith these results from the space and time study, the following are some policy suggestions for the sustainability of tourism economy in Thailand.\n\n-   **Targeted Support for Main Tourist Hubs**:\n\n    -   **Bangkok**: Given its persistent negative spatial autocorrelation, although Bangkok has the highest tourism revenue, policymakers should explore why Bangkok consistently stands out and consider targeted strategies, such as infrastructure investment or promotional campaigns, to ensure its tourism sector remains competitive in the neighboring provinces to benefit equally from the tourism flow.\n\n    -   **Chonburi**: With lots of tourist destinations and beautiful beaches like Pattaya in the Chonburi province, policymakers should maintain and market more attractions in this province.\n\n-   **Pandemic Recovery Support**:\n\n    -   **Recovery Plans**: During COVID, several provinces saw no tourist activity, which may have resulted in long-term damage to their local economies. A robust recovery plan focused on revitalizing tourism in these regions is essential. Policymakers could introduce incentives like tax breaks for tourism businesses, grants for tourism-related infrastructure, and marketing campaigns to rebuild tourism appeal post-pandemic.\n\n------------------------------------------------------------------------\n\n# 6 Emerging Hotspot Analysis\n\nHaving analyzed the spatial autocorrelation of the selected tourism economy indicators, we will now proceed to incorporate temporal trends and conduct an Emerging Hot Spot Analysis. This next phase aims to identify dynamic patterns in tourism data, revealing how hot spots and cold spots evolve over time. By integrating both spatial and temporal dimensions, we can gain deeper insights into the factors influencing tourism trends and their implications for economic development.\n\n## 6.1 Method Overview\n\nEmerging Hot Spot Analysis (EHSA) is a comprehensive approach to understanding spatial patterns by incorporating temporal trends, revealing how hot spots (areas with high values) and cold spots (areas with low values) evolve over time. Below are the primary steps and methodology for this analysis:\n\n1.  **Building a Space-Time Cube**\\\n    The first step in EHSA is constructing a space-time cube, which organizes spatial data by time slices (bins). Each location in the spatial dataset is represented by a series of time-stamped values, creating a 3D structure. This cube allows for the simultaneous analysis of both spatial and temporal dimensions, capturing how a phenomenon changes over time across different locations. In this analysis, each time slice corresponds to a specific period (month-year for our case), and the values at each location represent the attribute being studied (e.g., tourist revenue, occupancy rate, number of foreign tourists).\n\n2.  **Calculating the Getis-Ord Gi Statistic\\***\\\n    Once the space-time cube is built, the **Getis-Ord Gi**\\* statistic is computed for each bin (location at a specific time). This statistic measures the degree to which high or low values cluster spatially. By applying an FDR (False Discovery Rate) correction, the analysis adjusts for multiple testing, ensuring that the identification of significant hot spots and cold spots is statistically valid.\n\n3.  **Evaluating Hot and Cold Spot Trends Using the Mann-Kendall Trend Test**\\\n    To assess how these hot and cold spots evolve over time, the **Mann-Kendall trend test** is applied to the space-time cube data. This non-parametric test evaluates whether there is a statistically significant upward or downward trend in the hot or cold spot patterns over the period analyzed. The test helps determine whether the spatial clusters of high or low values are increasing, decreasing, or remaining stable over time.\n\n4.  **Categorizing Study Area Locations**\\\n    Based on the trend analysis, each study area location is categorized according to its temporal trend. This categorization is achieved by combining the z-scores and p-values from both the Mann-Kendall trend test and the Getis-Ord Gi\\* statistic. Locations are classified depending on whether the clusters of high or low values show significant changes over time. The categorization highlights areas with growing or fading clusters.\n\n## 6.1 Computing Gi\\* Statistics\n\nWe will need to derive a spatial weight matrix before we can compute local Gi\\* statistics using the include_self() code below.\n\nAlthough we used KNN for spatial autocorrelation analysis to capture relationships among a fixed number of neighboring provinces, inverse distance weights are appropriate for emerging hotspot analysis because this method captures the spatial decay of influence, where closer locations have a stronger impact on each other than those further apart. By using inverse distance weighting, we account for the fact that the influence of one region on another diminishes with increasing distance, reflecting a more realistic spatial interaction model. This approach allows us to better identify emerging hotspots where tourism dynamics are more likely influenced by nearby regions, providing a better understanding of how tourism patterns evolve over time in relation to spatial proximity.\n\nThe following code chunk will be used to identify neighbors and to derive an inverse distance weights matrix.\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_nb <- tourism_spt %>%\n  activate(\"geometry\") %>%\n  mutate(neighbours = include_self(st_knn(geometry, k = 6)),  # Find 6 nearest neighbors and include self\n         weights = st_inverse_distance(neighbours, geometry, scale = 1, alpha = 1),\n         .before = 1) %>%\n  set_nbs(\"neighbours\") %>%\n  set_wts(\"weights\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(tourism_nb, \"data/rds/tourism_nb.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_nb <- read_rds(\"data/rds/tourism_nb.rds\")\n```\n:::\n\n\n## Explanation\n\n-   **activate(\"geometry\")**: The `activate()` function from the `dplyr` package is used to activate the geometry context within the `tourism_spt` object. This focuses the operations on the spatial (geometric) data rather than the temporal data.\n\n-   **mutate()**: Within the geometry context, two new columns, `neighbours` and `weights`, are created:\n\n    -   neighbours: The `include_self()` function is used with `st_knn(geometry)`. `st_knn()` is used here because it ensures that each spatial feature (province) has a fixed number of neighbors, regardless of the geographic distribution of the data.\n\n    -   weights: The `st_inverse_distance()` function computes inverse distance weights for the neighbors using the `nb` column and `geometry`. These weights are scaled by a factor of 1, and the distance is raised to the power of `alpha`(which is set to 1).\n\n-   **set_nbs(\"**neighbours**\")** and **set_wts(\"**weights**\")**: After activating the data context again (automatically done by `%>%`), the `set_nbs()`and `set_wts()` functions are used to copy over the neighbours and weights columns to each time slice of the spatio-temporal data.\n:::\n\nWe can use these new columns to calculate the local Gi\\* for each location for each of the tourism economy indicators. We can do this by grouping by *date_int* and using `local_gstar_perm()` of sfdep package. Finally, we will use `unnest()` to unnest *gi_star* column of the newly created *gi_starts* data.frame.\n\n::: panel-tabset\n## Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrev_gi_stars <- tourism_nb %>% \n  group_by(date_int) %>% \n  mutate(gi_star = local_gstar_perm(\n    revenue_all, neighbours, weights)) %>% \n  tidyr::unnest(gi_star)\n```\n:::\n\n\n## Occpancy Rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_gi_stars <- tourism_nb %>% \n  group_by(date_int) %>% \n  mutate(gi_star = local_gstar_perm(\n    ratio_tourist_stay, neighbours, weights)) %>% \n  tidyr::unnest(gi_star)\n```\n:::\n\n\n## Number of Foreign Tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft_gi_stars <- tourism_nb %>% \n  group_by(date_int) %>% \n  mutate(gi_star = local_gstar_perm(\n    no_tourist_foreign, neighbours, weights)) %>% \n  tidyr::unnest(gi_star)\n```\n:::\n\n:::\n\n## 6.2 Mann-Kendall Test\n\nThe **Mann-Kendall test** is a non-parametric statistical method commonly used in time series analysis to detect trends in data, making it particularly useful in the context of EHSA. It is applied to evaluate the significance of trends in hot spots or cold spots, helping determine whether these patterns are random or systematic.\n\nThe following is the hypothesis we would like to test:\n\n-   **Null hypothesis(H0)**: There is no trend in the data, meaning the observed values are independent and randomly ordered.\n\n-   **Alternative hypothesis (H1):** A trend exists (either positive, negative, or non-null)\n\nRejecting the null hypothesis indicates the presence of a significant trend, either positive (increasing over time) or negative (decreasing over time).\n\n### 6.2.1 Revenue\n\n::: panel-tabset\n## Bangkok\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk_rev <- rev_gi_stars %>% \n  ungroup() %>% \n  filter(province_eng == \"Bangkok\") |> \n  select(province_eng, date_int, gi_star)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-790171f8b3bf5763008a\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-790171f8b3bf5763008a\">{\"x\":{\"data\":[{\"x\":[201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212,202301,202302],\"y\":[4.5364168131763876,4.6319632797051371,4.3994656756224293,5.2876457134664543,5.3544314367575438,5.229813602811956,5.8742004180786447,5.9047055360791783,5.854380528151534,5.0724072550499955,5.140875196068051,5.0692924256700058,4.5129512526709989,4.7962159496535257,4.8242705993900872,6.1170389407306889,6.1290213371988216,5.6832011909917739,5.1588891245900319,5.7553789380277482,5.7000245032506252,4.7961921551159286,4.7577608744801978,4.7980115317647556,5.8173767956082472,5.7145645422900646,5.5861056276597383,4.9624116599954675,5.5156458945887081,5.1956907314235767,2.6908603755110665,3.1085703481966549,3.217557937007685,3.2537034626366768,2.4812337571205734,4.3641374333669001,4.1371738801770492,4.2682597996462333,4.7184108214811218,4.8081327090457071,4.7673721331494656,4.8805198589573617,4.7374099976689612,4.7978287106271438,4.8028464458904487,5.0452775589462169,4.9803980890382382,5.066914926536624,5.0836180321457602,4.9742515271317451],\"text\":[\"date_int: 201901<br />gi_star: 4.536417\",\"date_int: 201902<br />gi_star: 4.631963\",\"date_int: 201903<br />gi_star: 4.399466\",\"date_int: 201904<br />gi_star: 5.287646\",\"date_int: 201905<br />gi_star: 5.354431\",\"date_int: 201906<br />gi_star: 5.229814\",\"date_int: 201907<br />gi_star: 5.874200\",\"date_int: 201908<br />gi_star: 5.904706\",\"date_int: 201909<br />gi_star: 5.854381\",\"date_int: 201910<br />gi_star: 5.072407\",\"date_int: 201911<br />gi_star: 5.140875\",\"date_int: 201912<br />gi_star: 5.069292\",\"date_int: 202001<br />gi_star: 4.512951\",\"date_int: 202002<br />gi_star: 4.796216\",\"date_int: 202003<br />gi_star: 4.824271\",\"date_int: 202004<br />gi_star: 6.117039\",\"date_int: 202005<br />gi_star: 6.129021\",\"date_int: 202006<br />gi_star: 5.683201\",\"date_int: 202007<br />gi_star: 5.158889\",\"date_int: 202008<br />gi_star: 5.755379\",\"date_int: 202009<br />gi_star: 5.700025\",\"date_int: 202010<br />gi_star: 4.796192\",\"date_int: 202011<br />gi_star: 4.757761\",\"date_int: 202012<br />gi_star: 4.798012\",\"date_int: 202101<br />gi_star: 5.817377\",\"date_int: 202102<br />gi_star: 5.714565\",\"date_int: 202103<br />gi_star: 5.586106\",\"date_int: 202104<br />gi_star: 4.962412\",\"date_int: 202105<br />gi_star: 5.515646\",\"date_int: 202106<br />gi_star: 5.195691\",\"date_int: 202107<br />gi_star: 2.690860\",\"date_int: 202108<br />gi_star: 3.108570\",\"date_int: 202109<br />gi_star: 3.217558\",\"date_int: 202110<br />gi_star: 3.253703\",\"date_int: 202111<br />gi_star: 2.481234\",\"date_int: 202112<br />gi_star: 4.364137\",\"date_int: 202201<br />gi_star: 4.137174\",\"date_int: 202202<br />gi_star: 4.268260\",\"date_int: 202203<br />gi_star: 4.718411\",\"date_int: 202204<br />gi_star: 4.808133\",\"date_int: 202205<br />gi_star: 4.767372\",\"date_int: 202206<br />gi_star: 4.880520\",\"date_int: 202207<br />gi_star: 4.737410\",\"date_int: 202208<br />gi_star: 4.797829\",\"date_int: 202209<br />gi_star: 4.802846\",\"date_int: 202210<br />gi_star: 5.045278\",\"date_int: 202211<br />gi_star: 4.980398\",\"date_int: 202212<br />gi_star: 5.066915\",\"date_int: 202301<br />gi_star: 5.083618\",\"date_int: 202302<br />gi_star: 4.974252\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283108,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":31.415525114155255},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[201880.95000000001,202322.04999999999],\"tickmode\":\"array\",\"ticktext\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"tickvals\":[201900,202000,202100,202200,202300],\"categoryorder\":\"array\",\"categoryarray\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"date_int\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[2.298844378116661,6.311410716202734],\"tickmode\":\"array\",\"ticktext\":[\"3\",\"4\",\"5\",\"6\"],\"tickvals\":[3,4,5,6],\"categoryorder\":\"array\",\"categoryarray\":[\"3\",\"4\",\"5\",\"6\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"e86cd592fcf\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"e86cd592fcf\",\"visdat\":{\"e86cd592fcf\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-   **Initial Increase:** *The Gi* values start around 4 and goes slightly higher, suggesting **this is a** periods where tourism revenue patterns are higher in Bangkok. This could indicate that certain regions of the city were performing well in terms of earning revenue from tourism.\n\n-   **Sharp Drop to Negative Values (Mid-2021)**: Around mid-2021 (07-11), the Gi\\* statistic drops sharply to a Gi value of 2.5. This indicates the revenue was significantly lower than before. This sharp decline correlates with the COVID-19 and the resulting lowest point of tourism revenue.\n\n-   **Slow Recovery (2022 onwards)**: The Gi\\* statistic sharply rises back up into 2022. Although the Gi\\* statistic stays below 5 (what it used to be pre-covid) for some time, there is an upward trend. This may reflect a slow recovery in revenue as tourism and business travel began to resume. Going into 2023, it has recovered back beyond 5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk_rev %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n     tau     sl     S     D   varS\n   <dbl>  <dbl> <dbl> <dbl>  <dbl>\n1 -0.174 0.0762  -213  1225 14292.\n```\n\n\n:::\n:::\n\n\nIn the results, sl is the p-value. Since it is slightly greater than our level of significance (0.05), we **fail to reject they null hypothesis** for Bangkok. There is no trend in the data, meaning the observed values are independent and randomly ordered.\n\n## Chonburi\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbr_rev <- rev_gi_stars %>% \n  ungroup() %>% \n  filter(province_eng == \"Chonburi\") |> \n  select(province_eng, date_int, gi_star)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-b4368f0841dd06d6138d\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-b4368f0841dd06d6138d\">{\"x\":{\"data\":[{\"x\":[201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212,202301,202302],\"y\":[3.7066519640063502,3.8104283291882224,3.7313430459371002,4.1521485817714314,4.2739410878395212,4.1050963204204907,3.5039298661628457,3.5342864358007073,3.4716176530793583,4.0232941608609414,4.1182838231217049,3.6583584742324948,3.5113086800073128,3.0954093901498805,3.520009635631705,3.3098777151044216,3.3125174177972498,3.7252338925409676,3.5104481379704349,3.5833331310433874,3.5653972909469327,3.972759083503254,4.3020813690056636,4.024070480832922,2.588598860404034,2.6767568326628783,2.6778685291402806,2.718740946234492,2.9982908360635014,3.2345300896187288,1.7495139667956365,1.8328732598023112,2.4129116757581839,3.0392566195601232,4.0845583981204809,3.7220123262311393,4.2586158993891186,4.1468281977680483,4.0941573897561012,4.0242255704730514,3.7121066729482011,3.551556048763111,3.2930557045692601,3.3478815742904962,3.2390224684126814,3.5522932122048463,3.742066589679089,3.9540668578179519,3.9074081344945815,3.6139673285138567],\"text\":[\"date_int: 201901<br />gi_star: 3.706652\",\"date_int: 201902<br />gi_star: 3.810428\",\"date_int: 201903<br />gi_star: 3.731343\",\"date_int: 201904<br />gi_star: 4.152149\",\"date_int: 201905<br />gi_star: 4.273941\",\"date_int: 201906<br />gi_star: 4.105096\",\"date_int: 201907<br />gi_star: 3.503930\",\"date_int: 201908<br />gi_star: 3.534286\",\"date_int: 201909<br />gi_star: 3.471618\",\"date_int: 201910<br />gi_star: 4.023294\",\"date_int: 201911<br />gi_star: 4.118284\",\"date_int: 201912<br />gi_star: 3.658358\",\"date_int: 202001<br />gi_star: 3.511309\",\"date_int: 202002<br />gi_star: 3.095409\",\"date_int: 202003<br />gi_star: 3.520010\",\"date_int: 202004<br />gi_star: 3.309878\",\"date_int: 202005<br />gi_star: 3.312517\",\"date_int: 202006<br />gi_star: 3.725234\",\"date_int: 202007<br />gi_star: 3.510448\",\"date_int: 202008<br />gi_star: 3.583333\",\"date_int: 202009<br />gi_star: 3.565397\",\"date_int: 202010<br />gi_star: 3.972759\",\"date_int: 202011<br />gi_star: 4.302081\",\"date_int: 202012<br />gi_star: 4.024070\",\"date_int: 202101<br />gi_star: 2.588599\",\"date_int: 202102<br />gi_star: 2.676757\",\"date_int: 202103<br />gi_star: 2.677869\",\"date_int: 202104<br />gi_star: 2.718741\",\"date_int: 202105<br />gi_star: 2.998291\",\"date_int: 202106<br />gi_star: 3.234530\",\"date_int: 202107<br />gi_star: 1.749514\",\"date_int: 202108<br />gi_star: 1.832873\",\"date_int: 202109<br />gi_star: 2.412912\",\"date_int: 202110<br />gi_star: 3.039257\",\"date_int: 202111<br />gi_star: 4.084558\",\"date_int: 202112<br />gi_star: 3.722012\",\"date_int: 202201<br />gi_star: 4.258616\",\"date_int: 202202<br />gi_star: 4.146828\",\"date_int: 202203<br />gi_star: 4.094157\",\"date_int: 202204<br />gi_star: 4.024226\",\"date_int: 202205<br />gi_star: 3.712107\",\"date_int: 202206<br />gi_star: 3.551556\",\"date_int: 202207<br />gi_star: 3.293056\",\"date_int: 202208<br />gi_star: 3.347882\",\"date_int: 202209<br />gi_star: 3.239022\",\"date_int: 202210<br />gi_star: 3.552293\",\"date_int: 202211<br />gi_star: 3.742067\",\"date_int: 202212<br />gi_star: 3.954067\",\"date_int: 202301<br />gi_star: 3.907408\",\"date_int: 202302<br />gi_star: 3.613967\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283108,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":43.105022831050235},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[201880.95000000001,202322.04999999999],\"tickmode\":\"array\",\"ticktext\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"tickvals\":[201900,202000,202100,202200,202300],\"categoryorder\":\"array\",\"categoryarray\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"date_int\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[1.6218855966851351,4.4297097391161646],\"tickmode\":\"array\",\"ticktext\":[\"2.0\",\"2.5\",\"3.0\",\"3.5\",\"4.0\"],\"tickvals\":[2,2.5,3,3.5,4],\"categoryorder\":\"array\",\"categoryarray\":[\"2.0\",\"2.5\",\"3.0\",\"3.5\",\"4.0\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"e86c2629d92c\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"e86c2629d92c\",\"visdat\":{\"e86c2629d92c\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-   **Initial Trend:** *The Gi* values starts lower than revenue, around 4, suggesting this is a periods where tourism revenue patterns are like pre covid in Chonburi. This could indicate that Chonburi has slighly weaker hotspots and stronger clustering of high values in certain areas compared to Bangkok.\n\n-   **Sharp Drop to Negative Values (Mid-2021)**: Around mid-2021 (07), the Gi\\* statistic drops sharply to a Gi value of 1.5. This indicates the revenue was significantly lower than before, similar to Bangkok.\n\n-   **Slow Recovery (2022 onwards)**: The Gi\\* statistic sharply rises back up into 2022 with higher Gi\\* statistic than pre-covid. This may reflect a faster recovery in revenue as tourism and business travel began to resume in Chonburi than in Bangkok.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbr_rev %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n      tau    sl     S     D   varS\n    <dbl> <dbl> <dbl> <dbl>  <dbl>\n1 -0.0824 0.403  -101  1225 14292.\n```\n\n\n:::\n:::\n\n\nSince p-value is greater than our level of significance (0.05), we also **fail to reject they null hypothesis** for Chonburi. This means that there is the no presence of a significant trend.\n:::\n\nWe can also see the results of the all provinces by using group_by() as in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nallprov_rev <- rev_gi_stars %>%\n  group_by(province_eng) %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>%\n  tidyr::unnest_wider(mk)\nhead(allprov_rev)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng      tau     sl     S     D   varS\n  <chr>           <dbl>  <dbl> <dbl> <dbl>  <dbl>\n1 Amnat Charoen -0.205  0.0365  -251  1225 14292.\n2 Ang Thong      0.0302 0.763     37  1225 14292.\n3 Bangkok       -0.174  0.0762  -213  1225 14292.\n4 Bueng Kan     -0.133  0.175   -163  1225 14292.\n5 Buriram       -0.0498 0.616    -61  1225 14292.\n6 Chachoengsao  -0.174  0.0762  -213  1225 14292.\n```\n\n\n:::\n:::\n\n\nThen , we can sort this dataframe to see significant emerging hot/cold spots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemerging_rev <- allprov_rev %>% \n  arrange(sl, abs(tau)) %>% \n  slice(1:10)\nhead(emerging_rev)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng           tau           sl     S     D   varS\n  <chr>                <dbl>        <dbl> <dbl> <dbl>  <dbl>\n1 Nakhon Si Thammarat -0.540 0.0000000337  -661  1225 14292.\n2 Nan                  0.461 0.00000238     565  1225 14292.\n3 Phatthalung         -0.450 0.00000421    -551  1225 14292.\n4 Chumphon            -0.429 0.0000117     -525  1225 14292.\n5 Chiang Rai           0.373 0.000136       457  1225 14292.\n6 Narathiwat          -0.365 0.000191      -447  1225 14292.\n```\n\n\n:::\n:::\n\n\nsl (p-values):\n\n-   6 provinces, namely Nakhon Si Thammarat, Nan, Phatthalung,Chumphon, Chiang Rai, Narathiwat, Pattani, Yala, Phayao, and Mae Hong Son, are the top hotspot/coldspot provinces in terms of total revenue generated from tourism.\n\n-   Provinces with very small sl values (e.g. Nan) indicate **high statistical significance**, suggesting that the observed trend is unlikely to be due to random variation.\n\n-   Provinces with higher absoulate tau values (e.g. Nakhon Si Thammarat) indicate **stronger trend** whether it is decreasing or increasing.\n\nTau values:\n\n-   **Negative tau values** (e.g., Nakhon Si Thammarat, Phatthalung, and Chumphon) suggest a **decreasing trend** in tourism revenue. Their hot spots are becoming weaker or less frequent over time.\n\n-   **Positive tau values** (e.g., Nan and Chiang Rai) indicate an increasing trend, meaning that these provinces are potential hotspots for development since there has been growth in tourism revenue overtime.\n\n### 6.2.2 Occupancy Rate\n\n::: panel-tabset\n## Bangkok\n\nthe province that has the strongest negative local autocorrelation consistently\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk_or <- or_gi_stars %>% \n  ungroup() %>% \n  filter(province_eng == \"Bangkok\") |> \n  select(province_eng, date_int, gi_star)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-284c5ae9d4cabeadbb39\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-284c5ae9d4cabeadbb39\">{\"x\":{\"data\":[{\"x\":[201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212,202301,202302],\"y\":[1.5311751342424935,1.6614623381106575,1.5655069694605175,1.8648602284433973,2.6215190710506224,2.2081147536907442,2.49840791545114,2.6882443487586674,1.7290591411370957,0.98601227619929677,1.8276182809862473,1.3770268886555428,1.2748293641480049,0.58102225094173154,-1.8581944703316313,4.0549961408329516,0.76529864415175497,-0.84977706727115587,-2.3624734316468983,-1.9251145429392835,-1.8535848004423388,-2.6169535464346119,-1.9717085397828673,-2.658890896273677,-2.6254391561997292,-3.2444197876659282,-3.4309655683203095,-2.3908564774404977,-0.089985592483701596,-0.3521465668982306,-1.3942222219293985,-1.19939285363555,1.1130268040069429,0.015196263622058248,-0.51683414374393166,-1.2356577059909615,-2.0483088111881109,-1.8667503219331452,-1.6977221389783044,-1.8824195369266161,-1.8906651324791679,-1.5798832521471928,-1.3811583397240421,-0.88917660477737936,-0.75601174650609559,-1.4434163784880523,-0.11037949623480421,-0.86223786090749477,-0.63644751528672383,-0.56900916571223714],\"text\":[\"date_int: 201901<br />gi_star:  1.53117513\",\"date_int: 201902<br />gi_star:  1.66146234\",\"date_int: 201903<br />gi_star:  1.56550697\",\"date_int: 201904<br />gi_star:  1.86486023\",\"date_int: 201905<br />gi_star:  2.62151907\",\"date_int: 201906<br />gi_star:  2.20811475\",\"date_int: 201907<br />gi_star:  2.49840792\",\"date_int: 201908<br />gi_star:  2.68824435\",\"date_int: 201909<br />gi_star:  1.72905914\",\"date_int: 201910<br />gi_star:  0.98601228\",\"date_int: 201911<br />gi_star:  1.82761828\",\"date_int: 201912<br />gi_star:  1.37702689\",\"date_int: 202001<br />gi_star:  1.27482936\",\"date_int: 202002<br />gi_star:  0.58102225\",\"date_int: 202003<br />gi_star: -1.85819447\",\"date_int: 202004<br />gi_star:  4.05499614\",\"date_int: 202005<br />gi_star:  0.76529864\",\"date_int: 202006<br />gi_star: -0.84977707\",\"date_int: 202007<br />gi_star: -2.36247343\",\"date_int: 202008<br />gi_star: -1.92511454\",\"date_int: 202009<br />gi_star: -1.85358480\",\"date_int: 202010<br />gi_star: -2.61695355\",\"date_int: 202011<br />gi_star: -1.97170854\",\"date_int: 202012<br />gi_star: -2.65889090\",\"date_int: 202101<br />gi_star: -2.62543916\",\"date_int: 202102<br />gi_star: -3.24441979\",\"date_int: 202103<br />gi_star: -3.43096557\",\"date_int: 202104<br />gi_star: -2.39085648\",\"date_int: 202105<br />gi_star: -0.08998559\",\"date_int: 202106<br />gi_star: -0.35214657\",\"date_int: 202107<br />gi_star: -1.39422222\",\"date_int: 202108<br />gi_star: -1.19939285\",\"date_int: 202109<br />gi_star:  1.11302680\",\"date_int: 202110<br />gi_star:  0.01519626\",\"date_int: 202111<br />gi_star: -0.51683414\",\"date_int: 202112<br />gi_star: -1.23565771\",\"date_int: 202201<br />gi_star: -2.04830881\",\"date_int: 202202<br />gi_star: -1.86675032\",\"date_int: 202203<br />gi_star: -1.69772214\",\"date_int: 202204<br />gi_star: -1.88241954\",\"date_int: 202205<br />gi_star: -1.89066513\",\"date_int: 202206<br />gi_star: -1.57988325\",\"date_int: 202207<br />gi_star: -1.38115834\",\"date_int: 202208<br />gi_star: -0.88917660\",\"date_int: 202209<br />gi_star: -0.75601175\",\"date_int: 202210<br />gi_star: -1.44341638\",\"date_int: 202211<br />gi_star: -0.11037950\",\"date_int: 202212<br />gi_star: -0.86223786\",\"date_int: 202301<br />gi_star: -0.63644752\",\"date_int: 202302<br />gi_star: -0.56900917\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283108,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":37.260273972602747},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[201880.95000000001,202322.04999999999],\"tickmode\":\"array\",\"ticktext\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"tickvals\":[201900,202000,202100,202200,202300],\"categoryorder\":\"array\",\"categoryarray\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"date_int\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-3.8052636537779727,4.4292942262906143],\"tickmode\":\"array\",\"ticktext\":[\"-2\",\"0\",\"2\",\"4\"],\"tickvals\":[-2,0,1.9999999999999996,3.9999999999999996],\"categoryorder\":\"array\",\"categoryarray\":[\"-2\",\"0\",\"2\",\"4\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"e86c7c6c6d6a\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"e86c7c6c6d6a\",\"visdat\":{\"e86c7c6c6d6a\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-   **Initial Positives:** *The Gi* values start around 2 or slightly higher, suggesting that we can see some patterns of temporal clustering (periods where occupancy rates are higher precovid), meaning areas in Bangkok had significantly higher occupancy rates than expected based on the overall distribution. This could indicate that certain regions of the city were performing well in terms of hotel occupancy before the pandemic.\n\n-   **Sharp Drop to Negative Values (Mid-2020)**: Unlike revenue which only decreased sharply in 2021, for occupancy rate, the Gi\\* statistic drops sharply to negative values, close to -2 around mid-2020. This indicates the emergence of cold spots, where the occupancy rate was significantly lower than expected. This sharp decline correlates exactly with the COVID-19 timeline and the resulting collapse in tourism and hospitality demand, leading to widespread low occupancy in Bangkok hotels.\n\n-   **Slow Recovery (2021 onwards)**: The Gi\\* statistic gradually rises from the negative values during late 2021 and into 2022. Although the Gi\\* statistic stays below 0 for some time, the upward trend suggests a weakening of cold spots. This may reflect a slow recovery in occupancy rates as tourism and business travel began to pick up post-pandemic, but the values remain below their pre-pandemic levels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk_or %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n     tau      sl     S     D   varS\n   <dbl>   <dbl> <dbl> <dbl>  <dbl>\n1 -0.313 0.00140  -383  1225 14292.\n```\n\n\n:::\n:::\n\n\nSince p-value is less than our level of significance, we **will reject the null hypothesis** for Bangkok, indicating that there is might be montonic trend in the data.From the tau value we see that the temporal trend is negative over the period of 2019 to 2023. If the tau is negative in conjunction with Gi\\* statistics, it could imply that there is a decline in spatial clustering of high occupancy rates over time.\n\n## Khon Kaen\n\nthe province that has the strongest positive local autocorrelation pre-covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkk_or <- or_gi_stars %>% \n  ungroup() %>% \n  filter(province_eng == \"Khon Kaen\") |> \n  select(province_eng, date_int, gi_star)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-f0bfaad072558b439a66\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f0bfaad072558b439a66\">{\"x\":{\"data\":[{\"x\":[201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212,202301,202302],\"y\":[-1.8378687583888651,-2.7093835006734719,-1.5443167261279345,-1.4070960040457645,-1.7426351083537575,-0.58891011442093733,0.0044544320987438797,-0.44598123146691371,-0.024677278740795297,-0.9201886475766522,-1.5610416119449257,-2.2826930253069451,-1.9709697338171768,-1.1535869340498843,-2.6828097261382871,-1.4477304797441086,-0.49210505619284461,-1.715787710498343,0.15257566850337761,0.59503017849082684,0.5285869072099898,0.73205685631289819,0.34376198638792227,1.0701519030285405,1.1935088674043108,0.17813741729744142,0.68666271054308103,-1.9793882423772757,-1.2165149644623929,-1.2595592538794245,-0.78284006102839621,-0.91045034372569478,-2.0872288742812817,-1.2355237714227476,-1.3516359318102968,-0.78344959549893067,-1.3182820388038963,-1.498318580552608,-1.3413736060537864,-0.029659474613908342,-0.43495083096617204,-0.26828001459868839,-0.62571037109897631,-0.13814089716822595,-0.78960663595225322,-1.0054994741778147,-1.4177444462245392,-1.4914377048042524,-0.93334443289091173,-1.2366295099417421],\"text\":[\"date_int: 201901<br />gi_star: -1.837868758\",\"date_int: 201902<br />gi_star: -2.709383501\",\"date_int: 201903<br />gi_star: -1.544316726\",\"date_int: 201904<br />gi_star: -1.407096004\",\"date_int: 201905<br />gi_star: -1.742635108\",\"date_int: 201906<br />gi_star: -0.588910114\",\"date_int: 201907<br />gi_star:  0.004454432\",\"date_int: 201908<br />gi_star: -0.445981231\",\"date_int: 201909<br />gi_star: -0.024677279\",\"date_int: 201910<br />gi_star: -0.920188648\",\"date_int: 201911<br />gi_star: -1.561041612\",\"date_int: 201912<br />gi_star: -2.282693025\",\"date_int: 202001<br />gi_star: -1.970969734\",\"date_int: 202002<br />gi_star: -1.153586934\",\"date_int: 202003<br />gi_star: -2.682809726\",\"date_int: 202004<br />gi_star: -1.447730480\",\"date_int: 202005<br />gi_star: -0.492105056\",\"date_int: 202006<br />gi_star: -1.715787710\",\"date_int: 202007<br />gi_star:  0.152575669\",\"date_int: 202008<br />gi_star:  0.595030178\",\"date_int: 202009<br />gi_star:  0.528586907\",\"date_int: 202010<br />gi_star:  0.732056856\",\"date_int: 202011<br />gi_star:  0.343761986\",\"date_int: 202012<br />gi_star:  1.070151903\",\"date_int: 202101<br />gi_star:  1.193508867\",\"date_int: 202102<br />gi_star:  0.178137417\",\"date_int: 202103<br />gi_star:  0.686662711\",\"date_int: 202104<br />gi_star: -1.979388242\",\"date_int: 202105<br />gi_star: -1.216514964\",\"date_int: 202106<br />gi_star: -1.259559254\",\"date_int: 202107<br />gi_star: -0.782840061\",\"date_int: 202108<br />gi_star: -0.910450344\",\"date_int: 202109<br />gi_star: -2.087228874\",\"date_int: 202110<br />gi_star: -1.235523771\",\"date_int: 202111<br />gi_star: -1.351635932\",\"date_int: 202112<br />gi_star: -0.783449595\",\"date_int: 202201<br />gi_star: -1.318282039\",\"date_int: 202202<br />gi_star: -1.498318581\",\"date_int: 202203<br />gi_star: -1.341373606\",\"date_int: 202204<br />gi_star: -0.029659475\",\"date_int: 202205<br />gi_star: -0.434950831\",\"date_int: 202206<br />gi_star: -0.268280015\",\"date_int: 202207<br />gi_star: -0.625710371\",\"date_int: 202208<br />gi_star: -0.138140897\",\"date_int: 202209<br />gi_star: -0.789606636\",\"date_int: 202210<br />gi_star: -1.005499474\",\"date_int: 202211<br />gi_star: -1.417744446\",\"date_int: 202212<br />gi_star: -1.491437705\",\"date_int: 202301<br />gi_star: -0.933344433\",\"date_int: 202302<br />gi_star: -1.236629510\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283108,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":37.260273972602747},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[201880.95000000001,202322.04999999999],\"tickmode\":\"array\",\"ticktext\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"tickvals\":[201900,202000,202100,202200,202300],\"categoryorder\":\"array\",\"categoryarray\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"date_int\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-2.9045281190773609,1.3886534858082],\"tickmode\":\"array\",\"ticktext\":[\"-2\",\"-1\",\"0\",\"1\"],\"tickvals\":[-2,-1,0,1],\"categoryorder\":\"array\",\"categoryarray\":[\"-2\",\"-1\",\"0\",\"1\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"e86c4d9c207f\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"e86c4d9c207f\",\"visdat\":{\"e86c4d9c207f\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-   **Initial Negatives:** *The Gi* values start around -2 and not passing 0 , suggesting that Khon Kaen is already identified as a cold spot, where the measured variable occupancy rate is significantly lower than in surrounding areas pre covid.\n\n-   **Increase to Positive Values (2020-2021)**: The sharp increase in Khon Kaen's Gi\\* statistic during 2020–2021 could indicate that while the province may not have seen substantial growth, its performance relative to surrounding regions improved significantly, likely due to the uneven impacts of COVID-19. Major tourist hubs suffered more during this period, while smaller or less tourist-reliant provinces like Khon Kaen may have experienced less negative impact, leading to a positive spatial clustering of values.\n\n-   **Sharp drop (mid-2021) and Recovery (2022 onwards)**: The Gi\\* statistic drops again mid 2021 as with Bangkok. After an initial adjustment to COVID-19, 2021 could have brought new challenges as lockdowns and restrictions continued or were reinstated. This could have impacted local businesses, occupancy rates, and tourism again, causing a temporary decline in the Gi\\* statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkk_or %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n     tau    sl     S     D   varS\n   <dbl> <dbl> <dbl> <dbl>  <dbl>\n1 0.0873 0.375   107  1225 14292.\n```\n\n\n:::\n:::\n\n\nSince p-value is greater than our level of significance, we **fail to reject the null hypothesis** for Khon Kaen, there is no montonic trend.\n\n## Chiang Rai\n\nthe province that has the strongest positive local autocorrelation post-covid\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncr_or <- or_gi_stars %>% \n  ungroup() %>% \n  filter(province_eng == \"Chiang Rai\") |> \n  select(province_eng, date_int, gi_star)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-f3ee1de60e73128aa4e6\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f3ee1de60e73128aa4e6\">{\"x\":{\"data\":[{\"x\":[201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212,202301,202302],\"y\":[2.0312225724964725,0.26255047799971587,-2.6661459360679927,-2.0497341885594444,-1.635954114469196,-2.0859851090854704,-2.1418570505439241,-1.9532175118125492,-1.6484833556789713,-1.1801806198910234,0.70211590331325102,1.8641436103252089,2.2083714496274363,-0.015902397679950036,2.326830226217957,1.9747679146802732,4.4252804721045376,2.5475129799318128,2.5280502222513421,2.3004848664838713,2.2625463332979465,2.747731943927668,4.0067999452850733,3.3395312467941118,1.1209546772056638,1.1450645594246198,0.29404915420562594,-0.89223275437253291,3.4459535750793058,3.0517364311556276,4.3977246611945118,4.7270692789720146,4.3991165561058336,4.1972642948702852,4.9683010343122307,5.1309895925334486,5.3683060136723277,5.7842718435068363,4.5423513344081003,4.1019560718545005,3.548317050940113,3.5829880905596441,3.1676782555058143,2.6536790565307755,2.877675486255642,3.3926688087274894,4.9323138822970289,5.3736638924490236,5.0151060588592005,3.6751914290717416],\"text\":[\"date_int: 201901<br />gi_star:  2.0312226\",\"date_int: 201902<br />gi_star:  0.2625505\",\"date_int: 201903<br />gi_star: -2.6661459\",\"date_int: 201904<br />gi_star: -2.0497342\",\"date_int: 201905<br />gi_star: -1.6359541\",\"date_int: 201906<br />gi_star: -2.0859851\",\"date_int: 201907<br />gi_star: -2.1418571\",\"date_int: 201908<br />gi_star: -1.9532175\",\"date_int: 201909<br />gi_star: -1.6484834\",\"date_int: 201910<br />gi_star: -1.1801806\",\"date_int: 201911<br />gi_star:  0.7021159\",\"date_int: 201912<br />gi_star:  1.8641436\",\"date_int: 202001<br />gi_star:  2.2083714\",\"date_int: 202002<br />gi_star: -0.0159024\",\"date_int: 202003<br />gi_star:  2.3268302\",\"date_int: 202004<br />gi_star:  1.9747679\",\"date_int: 202005<br />gi_star:  4.4252805\",\"date_int: 202006<br />gi_star:  2.5475130\",\"date_int: 202007<br />gi_star:  2.5280502\",\"date_int: 202008<br />gi_star:  2.3004849\",\"date_int: 202009<br />gi_star:  2.2625463\",\"date_int: 202010<br />gi_star:  2.7477319\",\"date_int: 202011<br />gi_star:  4.0067999\",\"date_int: 202012<br />gi_star:  3.3395312\",\"date_int: 202101<br />gi_star:  1.1209547\",\"date_int: 202102<br />gi_star:  1.1450646\",\"date_int: 202103<br />gi_star:  0.2940492\",\"date_int: 202104<br />gi_star: -0.8922328\",\"date_int: 202105<br />gi_star:  3.4459536\",\"date_int: 202106<br />gi_star:  3.0517364\",\"date_int: 202107<br />gi_star:  4.3977247\",\"date_int: 202108<br />gi_star:  4.7270693\",\"date_int: 202109<br />gi_star:  4.3991166\",\"date_int: 202110<br />gi_star:  4.1972643\",\"date_int: 202111<br />gi_star:  4.9683010\",\"date_int: 202112<br />gi_star:  5.1309896\",\"date_int: 202201<br />gi_star:  5.3683060\",\"date_int: 202202<br />gi_star:  5.7842718\",\"date_int: 202203<br />gi_star:  4.5423513\",\"date_int: 202204<br />gi_star:  4.1019561\",\"date_int: 202205<br />gi_star:  3.5483171\",\"date_int: 202206<br />gi_star:  3.5829881\",\"date_int: 202207<br />gi_star:  3.1676783\",\"date_int: 202208<br />gi_star:  2.6536791\",\"date_int: 202209<br />gi_star:  2.8776755\",\"date_int: 202210<br />gi_star:  3.3926688\",\"date_int: 202211<br />gi_star:  4.9323139\",\"date_int: 202212<br />gi_star:  5.3736639\",\"date_int: 202301<br />gi_star:  5.0151061\",\"date_int: 202302<br />gi_star:  3.6751914\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283108,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":37.260273972602747},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[201880.95000000001,202322.04999999999],\"tickmode\":\"array\",\"ticktext\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"tickvals\":[201900,202000,202100,202200,202300],\"categoryorder\":\"array\",\"categoryarray\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"date_int\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-3.088666825046734,6.2067927324855781],\"tickmode\":\"array\",\"ticktext\":[\"-2\",\"0\",\"2\",\"4\",\"6\"],\"tickvals\":[-2,0,2,4,5.9999999999999991],\"categoryorder\":\"array\",\"categoryarray\":[\"-2\",\"0\",\"2\",\"4\",\"6\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"e86c4d9dd84c\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"e86c4d9dd84c\",\"visdat\":{\"e86c4d9dd84c\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-   **Initial Negatives:** *The Gi* values start around 2 and stays below 0 initially , suggesting that Chiang Rai is might have seasonality trends, where the measured variable occupancy rate is significantly lower than in surrounding areas. It only increases back in December to positive values.\n\n-   **Sharp drop (mid-2021)**: The sharp decrease in Chiang Rai's Gi\\* statistic during 2020–2021. This drop in occupancy rate is seen throughout the other provinces so it may be due to new lockdowns and restrictions.\n\n-   **Recovery (2022 onwards)**: After the one month of drop in April 2021, The Gi\\* statistic drastically increases again into 2023 unlike Khon Kaen, much higher than the initial pre-covid time. This means that hotspots are beginning to emerge in Chiang Rai quickly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncr_or %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n    tau    sl     S     D   varS\n  <dbl> <dbl> <dbl> <dbl>  <dbl>\n1 0.584     0   715  1225 14292.\n```\n\n\n:::\n:::\n\n\nSince p-value is less than our level of significance, we **will reject the null hypothesis** for Chiang Rai as well, indicating that there is might be montonic trend in the data. From the tau value we see that the temporal trend is positive over the period of 2019 to 2023. The tau value of Chiang Rai is much higher than that of Khon Kaen, implying that there is an increase in spatial clustering of high occupancy rates and it is growing over time in Chiang Rai.\n:::\n\nNow we view the emerging hotspots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|echo: False\nallprov_or <- or_gi_stars %>%\n  group_by(province_eng) %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>%\n  tidyr::unnest_wider(mk)\nhead(allprov_or)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng     tau          sl     S     D   varS\n  <chr>          <dbl>       <dbl> <dbl> <dbl>  <dbl>\n1 Amnat Charoen -0.208 0.0336       -255  1225 14292.\n2 Ang Thong     -0.512 0.000000164  -627  1225 14292.\n3 Bangkok       -0.313 0.00140      -383  1225 14292.\n4 Bueng Kan      0.167 0.0879        205  1225 14292.\n5 Buriram        0.311 0.00148       381  1225 14292.\n6 Chachoengsao  -0.373 0.000137     -457  1225 14292.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nemerging_or <- allprov_or %>% \n  arrange(sl, abs(tau)) %>% \n  slice(1:10)\nhead(emerging_or)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng    tau           sl     S     D   varS\n  <chr>         <dbl>        <dbl> <dbl> <dbl>  <dbl>\n1 Nan           0.540 0              661  1225 14292.\n2 Chiang Rai    0.584 0              715  1225 14292.\n3 Suphan Buri  -0.543 0.0000000279  -665  1225 14292.\n4 Phayao        0.528 0.000000119    647  1225 14292.\n5 Ang Thong    -0.512 0.000000164   -627  1225 14292.\n6 Chainat      -0.497 0.000000366   -609  1225 14292.\n```\n\n\n:::\n:::\n\n\nsl (p-values):\n\n-   10 provinces, namely Nan, Chiang Rai, Suphan Buri, Chiang Rai, Phayao, Ang Thong, Chainat, Nakhon Pathom, Samut Songkhram, Samut Sakhon and Chiang Mai, are the top hotspot/coldspot provinces in terms of tourist occupancy rate.\n\n-   Provinces with very small sl values (e.g., Nan and Chiang Rai) indicate **high statistical significance**, suggesting that the observed trend is unlikely to be due to random variation.\n\nTau values:\n\n-   **Negative tau values** (e.g., Suphan Buri, Ang Thong, Chainat, Nakhon Pathom, Samut Songkhram, Samut Sakhon) suggest a **decreasing trend** in the occupancy rate.Their hot spots are becoming weaker over time.\n\n-   **Positive tau values** (e.g., Chiang Mai, Phayao, Nan and Chiang Rai) indicate an **increasing trend**, meaning that these provinces are potential hotspots for development of hotels, motels and other tourist infratstructure since there has been growth in tourism occupancy.\n\n### 6.2.3 Number of Foreign Tourists\n\n::: panel-tabset\n## Bangkok\n\nthe province that has the strongest negative local autocorrelation consistently\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk_ft <- ft_gi_stars %>% \n  ungroup() %>% \n  filter(province_eng == \"Bangkok\") |> \n  select(province_eng, date_int, gi_star)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-10ef9a283e08251d6d01\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-10ef9a283e08251d6d01\">{\"x\":{\"data\":[{\"x\":[201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212,202301,202302],\"y\":[5.0528804460648438,5.3099441018538061,4.9873696179266345,5.1769914434966813,5.1584206206841881,5.1451115514813202,5.6932365985369344,5.8588445958399191,5.591276816324406,4.4653650967969591,4.5281516508890354,4.8389504028901298,5.0239803155536507,5.3308841396512188,5.559050056744443,6.1248923884973543,6.1351690561662942,5.9918970853041751,5.8524718452547067,5.8600265117584938,5.9310294541746691,5.970115118770134,5.9094167665695023,6.1468814793876811,6.1699432422818141,6.1617678630070705,6.2833361374271508,6.1803963282940995,6.180384205854569,6.1977469190919949,4.8377151948335948,4.8419761314510401,4.1584621635576955,5.3068618328141932,5.5909117861916515,5.4511075502548261,4.7059549290664222,5.1670141774234164,5.4671603908464848,5.3647937346747305,5.829397121638606,5.8054203075816373,5.7388002880591058,5.7083354899962595,5.6101516494110779,5.6916568552819129,5.727159435363423,5.7033791962919675,5.6572788090464847,5.4939308399865645],\"text\":[\"date_int: 201901<br />gi_star: 5.052880\",\"date_int: 201902<br />gi_star: 5.309944\",\"date_int: 201903<br />gi_star: 4.987370\",\"date_int: 201904<br />gi_star: 5.176991\",\"date_int: 201905<br />gi_star: 5.158421\",\"date_int: 201906<br />gi_star: 5.145112\",\"date_int: 201907<br />gi_star: 5.693237\",\"date_int: 201908<br />gi_star: 5.858845\",\"date_int: 201909<br />gi_star: 5.591277\",\"date_int: 201910<br />gi_star: 4.465365\",\"date_int: 201911<br />gi_star: 4.528152\",\"date_int: 201912<br />gi_star: 4.838950\",\"date_int: 202001<br />gi_star: 5.023980\",\"date_int: 202002<br />gi_star: 5.330884\",\"date_int: 202003<br />gi_star: 5.559050\",\"date_int: 202004<br />gi_star: 6.124892\",\"date_int: 202005<br />gi_star: 6.135169\",\"date_int: 202006<br />gi_star: 5.991897\",\"date_int: 202007<br />gi_star: 5.852472\",\"date_int: 202008<br />gi_star: 5.860027\",\"date_int: 202009<br />gi_star: 5.931029\",\"date_int: 202010<br />gi_star: 5.970115\",\"date_int: 202011<br />gi_star: 5.909417\",\"date_int: 202012<br />gi_star: 6.146881\",\"date_int: 202101<br />gi_star: 6.169943\",\"date_int: 202102<br />gi_star: 6.161768\",\"date_int: 202103<br />gi_star: 6.283336\",\"date_int: 202104<br />gi_star: 6.180396\",\"date_int: 202105<br />gi_star: 6.180384\",\"date_int: 202106<br />gi_star: 6.197747\",\"date_int: 202107<br />gi_star: 4.837715\",\"date_int: 202108<br />gi_star: 4.841976\",\"date_int: 202109<br />gi_star: 4.158462\",\"date_int: 202110<br />gi_star: 5.306862\",\"date_int: 202111<br />gi_star: 5.590912\",\"date_int: 202112<br />gi_star: 5.451108\",\"date_int: 202201<br />gi_star: 4.705955\",\"date_int: 202202<br />gi_star: 5.167014\",\"date_int: 202203<br />gi_star: 5.467160\",\"date_int: 202204<br />gi_star: 5.364794\",\"date_int: 202205<br />gi_star: 5.829397\",\"date_int: 202206<br />gi_star: 5.805420\",\"date_int: 202207<br />gi_star: 5.738800\",\"date_int: 202208<br />gi_star: 5.708335\",\"date_int: 202209<br />gi_star: 5.610152\",\"date_int: 202210<br />gi_star: 5.691657\",\"date_int: 202211<br />gi_star: 5.727159\",\"date_int: 202212<br />gi_star: 5.703379\",\"date_int: 202301<br />gi_star: 5.657279\",\"date_int: 202302<br />gi_star: 5.493931\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283108,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":43.105022831050235},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[201880.95000000001,202322.04999999999],\"tickmode\":\"array\",\"ticktext\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"tickvals\":[201900,202000,202100,202200,202300],\"categoryorder\":\"array\",\"categoryarray\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"date_int\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[4.0522184648642225,6.3895798361206237],\"tickmode\":\"array\",\"ticktext\":[\"4.5\",\"5.0\",\"5.5\",\"6.0\"],\"tickvals\":[4.5,5,5.5,6],\"categoryorder\":\"array\",\"categoryarray\":[\"4.5\",\"5.0\",\"5.5\",\"6.0\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"e86c47e4372f\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"e86c47e4372f\",\"visdat\":{\"e86c47e4372f\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-   **Initial Increase:** *The Gi* values start at a high value of around 5 and goes slightly higher, suggesting **this is a** periods where patterns of foreign tourist are higher in Bangkok. This could indicate that certain regions of the city were tourist attractions.\n\n-   **Sharp Drop to Negative Values (Mid-2021)**: Around September 2021, the Gi\\* statistic drops sharply to a Gi value of 4. This indicates the number of tourists was significantly lower than before. This sharp decline correlates with the COVID-19 and the resulting lowest point of foreign tourist arriving in Bangkok.\n\n-   **Fast Recovery (2022 onwards)**: The Gi\\* statistic sharply rises back up by November 2021. The Gi\\* statistic went back to its original status at around 5.5 meaning that Bangkok has fully recovered and welcoming foreign tourists as usual or even more than usual.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk_ft %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n    tau    sl     S     D   varS\n  <dbl> <dbl> <dbl> <dbl>  <dbl>\n1 0.140 0.155   171  1225 14292.\n```\n\n\n:::\n:::\n\n\nSince p-value is greater than our level of significance, we **fail to reject the null hypothesis** for Bangkok, there is no montonic trend.\n\n## Chonburi\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbr_ft <- ft_gi_stars %>% \n  ungroup() %>% \n  filter(province_eng == \"Chonburi\") |> \n  select(province_eng, date_int, gi_star)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-f9ffb9521747c0cbc56d\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f9ffb9521747c0cbc56d\">{\"x\":{\"data\":[{\"x\":[201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210,202211,202212,202301,202302],\"y\":[4.2179757880071991,4.2763049483063247,4.2334146722161172,4.4003352577263799,4.5009876993643099,4.2482268439161661,4.33940190128612,4.3136870026650209,4.2474081963427857,4.6824909046671905,4.6861603998545789,4.101742086803168,4.2042358645442173,3.6918690239778496,3.7501429602501264,3.3257898486427502,3.3456681051101991,4.0924534824879339,4.1475985986051143,3.9860467676236753,3.9636746224408408,3.9264724303382277,4.1765843865803571,3.572760531140736,3.0514063814551564,3.0823586433067889,3.0225510234631314,2.9897844196130179,3.0419689363242211,3.088099284635426,2.3085376527203136,2.314971710072697,1.9608136795732987,2.4558110744368031,3.351475863432543,2.8966773369304941,4.3951200509558701,4.0705117924245364,3.3911152010256469,3.3057657877465108,3.3657090378247032,3.4556215608765011,3.3443417461675953,3.4442669601478832,3.3484607640371,3.6565763581641919,3.93285664449744,4.1051197791159408,4.2764404684163146,4.3407141732758268],\"text\":[\"date_int: 201901<br />gi_star: 4.217976\",\"date_int: 201902<br />gi_star: 4.276305\",\"date_int: 201903<br />gi_star: 4.233415\",\"date_int: 201904<br />gi_star: 4.400335\",\"date_int: 201905<br />gi_star: 4.500988\",\"date_int: 201906<br />gi_star: 4.248227\",\"date_int: 201907<br />gi_star: 4.339402\",\"date_int: 201908<br />gi_star: 4.313687\",\"date_int: 201909<br />gi_star: 4.247408\",\"date_int: 201910<br />gi_star: 4.682491\",\"date_int: 201911<br />gi_star: 4.686160\",\"date_int: 201912<br />gi_star: 4.101742\",\"date_int: 202001<br />gi_star: 4.204236\",\"date_int: 202002<br />gi_star: 3.691869\",\"date_int: 202003<br />gi_star: 3.750143\",\"date_int: 202004<br />gi_star: 3.325790\",\"date_int: 202005<br />gi_star: 3.345668\",\"date_int: 202006<br />gi_star: 4.092453\",\"date_int: 202007<br />gi_star: 4.147599\",\"date_int: 202008<br />gi_star: 3.986047\",\"date_int: 202009<br />gi_star: 3.963675\",\"date_int: 202010<br />gi_star: 3.926472\",\"date_int: 202011<br />gi_star: 4.176584\",\"date_int: 202012<br />gi_star: 3.572761\",\"date_int: 202101<br />gi_star: 3.051406\",\"date_int: 202102<br />gi_star: 3.082359\",\"date_int: 202103<br />gi_star: 3.022551\",\"date_int: 202104<br />gi_star: 2.989784\",\"date_int: 202105<br />gi_star: 3.041969\",\"date_int: 202106<br />gi_star: 3.088099\",\"date_int: 202107<br />gi_star: 2.308538\",\"date_int: 202108<br />gi_star: 2.314972\",\"date_int: 202109<br />gi_star: 1.960814\",\"date_int: 202110<br />gi_star: 2.455811\",\"date_int: 202111<br />gi_star: 3.351476\",\"date_int: 202112<br />gi_star: 2.896677\",\"date_int: 202201<br />gi_star: 4.395120\",\"date_int: 202202<br />gi_star: 4.070512\",\"date_int: 202203<br />gi_star: 3.391115\",\"date_int: 202204<br />gi_star: 3.305766\",\"date_int: 202205<br />gi_star: 3.365709\",\"date_int: 202206<br />gi_star: 3.455622\",\"date_int: 202207<br />gi_star: 3.344342\",\"date_int: 202208<br />gi_star: 3.444267\",\"date_int: 202209<br />gi_star: 3.348461\",\"date_int: 202210<br />gi_star: 3.656576\",\"date_int: 202211<br />gi_star: 3.932857\",\"date_int: 202212<br />gi_star: 4.105120\",\"date_int: 202301<br />gi_star: 4.276440\",\"date_int: 202302<br />gi_star: 4.340714\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.228310502283108,\"r\":7.3059360730593621,\"b\":40.182648401826498,\"l\":31.415525114155255},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[201880.95000000001,202322.04999999999],\"tickmode\":\"array\",\"ticktext\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"tickvals\":[201900,202000,202100,202200,202300],\"categoryorder\":\"array\",\"categoryarray\":[\"201900\",\"202000\",\"202100\",\"202200\",\"202300\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"date_int\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[1.8245463435592346,4.8224277358686427],\"tickmode\":\"array\",\"ticktext\":[\"2\",\"3\",\"4\"],\"tickvals\":[2,3,4],\"categoryorder\":\"array\",\"categoryarray\":[\"2\",\"3\",\"4\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"e86c20e85e\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"e86c20e85e\",\"visdat\":{\"e86c20e85e\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-   **Gradual Decline:** *The Gi* values start at a high value of around 4 and gradually decreases even pre-covid suggesting this is a periods where patterns of foreign tourist are high but getting lower in Chonburi.\n\n-   **Sharp Drop to Negative Values (Mid-2021)**: Around September 2021, the Gi\\* statistic drops sharply to a Gi value of 2 as with Bangkok. This indicates the number of tourists was significantly lower than before in this specific month which may be due to COVID-19 restrictions.\n\n-   **Fast Recovery (2022 onwards)**: The Gi\\* statistic sharply rises back up by November 2021. Then the Gi\\* statistic went back to its original status at around 4.2 meaning that Chonburi also has fully recovered and welcoming foreign tourists.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbr_ft %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>% \n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n     tau      sl     S     D   varS\n   <dbl>   <dbl> <dbl> <dbl>  <dbl>\n1 -0.306 0.00176  -375  1225 14292.\n```\n\n\n:::\n:::\n\n\nSince p-value is less than our level of significance, we **will reject the null hypothesis** for Chonburi indicating that there is might be montonic trend in the data. From the tau value we see that the temporal trend is negative over the period of 2019 to 2023, suggesting that there might me a decreasing trend of foreign tourist visitng Chonburi.\n:::\n\nNow we view the emerging hotspots.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng      tau      sl     S     D   varS\n  <chr>           <dbl>   <dbl> <dbl> <dbl>  <dbl>\n1 Amnat Charoen  0.125  0.204     153  1225 14292.\n2 Ang Thong     -0.0188 0.854     -23  1225 14292.\n3 Bangkok        0.140  0.155     171  1225 14292.\n4 Bueng Kan      0.273  0.00521   335  1225 14292.\n5 Buriram        0.169  0.0849    207  1225 14292.\n6 Chachoengsao   0.143  0.146     175  1225 14292.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nemerging_ft <- allprov_ft %>% \n  arrange(sl, abs(tau)) %>% \n  slice(1:10)\nhead(emerging_ft)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng           tau        sl     S     D   varS\n  <chr>                <dbl>     <dbl> <dbl> <dbl>  <dbl>\n1 Trat                -0.406 0.0000334  -497  1225 14292.\n2 Chanthaburi         -0.383 0.0000905  -469  1225 14292.\n3 Prachuap Khiri Khan -0.378 0.000111   -463  1225 14292.\n4 Rayong              -0.360 0.000233   -441  1225 14292.\n5 Chumphon            -0.355 0.000283   -435  1225 14292.\n6 Nong Khai            0.327 0.000820    401  1225 14292.\n```\n\n\n:::\n:::\n\n\nsl (p-values):\n\n-   10 provinces, namely Trat, Chanthaburi, Prachuap Khiri Kahn,Rayong, Chumphon, Nong Khai, Udon Thani, Phatthalung, Chonburi, and Sakhon Nakhon, are the top hotspot/coldspot provinces in terms of foreign tourist visitors.\n\n-   Provinces with very small sl values (e.g., Trat and Chanthaburi) indicate **high statistical significance**, suggesting that the observed trend is unlikely to be due to random variation.\n\nTau values:\n\n-   **Negative tau values** (e.g., Trat, Chanthaburi, Prachuap Khiri Kahn,Rayong, Chumphon,Phatthalung, and Chonburi) suggest a **decreasing trend** in the number of tourist visitors likely since they are already coldspots.\n\n-   **Positive tau values** (e.g., Sakhon Nakhon, Udon Thani and Nong Khai) indicate an **increasing trend**, meaning that these provinces are potential hotspots for foreign visitors.\\\n\n## 6.3 Performing Emerging Hotspot Analysis\n\nSince we have observed Gi\\* statistics, we will now perform EHSA analysis by using ***emerging_hotspot_analysis()*** of sfdep package with the code chunk below.\n\n::: panel-tabset\n## Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrev_ehsa <- emerging_hotspot_analysis(\n  x = tourism_spt, \n  .var = \"revenue_all\", \n  k = 1, \n  nsim = 99\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(rev_ehsa, \"data/rds/rev_ehsa.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrev_ehsa <- read_rds(\"data/rds/rev_ehsa.rds\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-130-1.png){width=672}\n:::\n:::\n\n\n-   **Sporadic cold spots**: There are 36 provinces, including Amnat Charoen, Bueng Kan, Chumphon, Phatthalung, and Surat Thani, which are characterized by fluctuating patterns of cold spots. These provinces experienced periods where tourism revenue was significantly lower than expected, but these cold spots were not consistent over time. The sporadic nature of cold spots suggests that while there are dips in revenue, they are not long enough to show a consistent downward trend.\n\n-   **Sporadic hot spots**: Only 9 provinces, such as Bangkok, Chonburi, and Phuket, were identified as sporadic hot spots. These provinces had periods of significantly higher tourism revenue, but these peaks were inconsistent. The \"on-again, off-again\" nature of these hot spots might reflect seasonal tourism fluctuations or external factors such as short-term policy changes, events, or market dynamics that temporarily boosted tourism in these areas.\n\n-   **No pattern detected**: A total of 32 provinces, such as Ang Thong, Khon Kaen, and Rayong, showed no clear spatial pattern in tourism revenue. This suggests that tourism revenue in these provinces did not follow any detectable trend, either positive or negative, over 2019-2023. These provinces may be subject to a range of influences that prevent clear emerging patterns from forming or may not have much tourist activities.\n\n## Occupancy Rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_ehsa <- emerging_hotspot_analysis(\n  x = tourism_spt, \n  .var = \"ratio_tourist_stay\", \n  k = 1, \n  nsim = 99\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(or_ehsa, \"data/rds/or_ehsa.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nor_ehsa <- read_rds(\"data/rds/or_ehsa.rds\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-134-1.png){width=672}\n:::\n:::\n\n\n-   **Oscillating hotspots**: A total of 33 provinces, including Chiang Mai, Nakhon Phanom, and Prachuap Khiri Khan, were identified as oscillating hotspots. These provinces experienced recurring periods where occupancy rates were significantly higher than expected, indicating a consistent rebound in demand for accommodations. The oscillating nature of these hotspots suggests that while there are strong peaks in occupancy rates, these trends are followed by periods of lower demand, likely driven by seasonal tourism, festivals, or regional events that create fluctuations in visitor numbers.\n\n-   **Oscillating cold spots**: 10 provinces, such as Nonthaburi, Pathum Thani, and Samut Sakhon, were marked as oscillating cold spots. These areas consistently saw periods of lower-than-expected occupancy rates, yet these patterns were not sustained over time. The intermittent nature of these cold spots may reflect localized challenges or temporary downturns in tourism, but without indicating a long-term decline in accommodation demand.\n\n-   **Sporadic cold spots**: Two provinces, Chanthaburi and Ranong, were classified as sporadic cold spots. In these areas, there were brief periods of significantly lower occupancy rates, but these cold spots did not persist long enough to suggest an enduring downward trend in tourism-related accommodation. These provinces may have experienced temporary challenges that caused short-term dips in accommodation demand.\n\n-   **No pattern detected**: A large number of provinces, 33 in total, such as Bangkok, Krabi, Suphan Buri, and Ang Thong, showed no significant spatial pattern in occupancy rates. This lack of detectable trends indicates that these provinces do not follow a consistent trajectory of either increased or decreased accommodation demand over time. The absence of clear patterns suggests that these areas might be subject to a variety of influencing factors, such as unpredictable shifts in local tourism, preventing clear hotspots or cold spots from emerging.\n\n## Number of Foreign Tourist\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft_ehsa <- emerging_hotspot_analysis(\n  x = tourism_spt, \n  .var = \"no_tourist_foreign\", \n  k = 1, \n  nsim = 99\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(ft_ehsa, \"data/rds/ft_ehsa.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nft_ehsa <- read_rds(\"data/rds/ft_ehsa.rds\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-138-1.png){width=672}\n:::\n:::\n\n\n-   **Sporadic cold spots**: A large number of provinces (47 out of 77), including **Amnat Charoen**, **Bueng Kan**, **Chaiyaphum**, and **Surat Thani**, were identified as sporadic cold spots. These provinces experienced fluctuations in foreign tourist numbers, with periods where tourist arrivals were significantly lower than expected. However, these cold periods were not consistent enough to show a long-term decline in foreign tourist activity.\n\n-   **Sporadic hot spots**: Only 12 provinces, such as Bangkok, Chonburi, and Krabi, were classified as sporadic hot spots. These provinces saw intermittent peaks in foreign tourist numbers, suggesting short-term boosts possibly driven by seasonal events, marketing campaigns, or other external factors. These increases were not sustained over time, resulting in an on-and-off pattern rather than continuous growth in foreign tourist arrivals.\n\n-   **No pattern detected**: Some provinces, such as Chiang Rai, Trat, and Satun, showed no statistically significant spatial pattern for foreign tourists, indicating that these areas had neither sustained periods of higher nor lower foreign tourist activity. This lack of consistent trends might suggest that foreign tourist numbers in these provinces are more random or influenced by a wide range of uncontrollable variables.\n:::\n\n## 6.4 Visualizing Emerging Hotspot Analysis\n\n::: panel-tabset\n## Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrev_ehsa_joined <- thaibounds %>%\n  left_join(rev_ehsa,\n            by = join_by(province_eng == location))\n```\n:::\n\n\n## Occupancy Rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_ehsa_joined <- thaibounds %>%\n  left_join(or_ehsa,\n            by = join_by(province_eng == location))\n```\n:::\n\n\n## Number of Foreign Tourist\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft_ehsa_joined <- thaibounds %>%\n  left_join(or_ehsa,\n            by = join_by(province_eng == location))\n```\n:::\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrev_ehsa_sig <- rev_ehsa_joined %>%\n  filter(p_value < 0.05)\n\nor_ehsa_sig <- or_ehsa_joined %>%\n  filter(p_value < 0.05)\n\nft_ehsa_sig <- ft_ehsa_joined %>%\n  filter(p_value < 0.05)\n\ntmap_mode(\"plot\")\n\nrev_map <- tm_shape(rev_ehsa_joined) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\n  tm_shape(rev_ehsa_sig) +\n  tm_fill(\"classification\") + \n  tm_borders(alpha = 0.4) +\n  tm_layout(title = \"Revenue EHSA\", \n            title.size = 0.4, \n            legend.text.size = 0.4, \n            legend.title.size = 0.4)\n\nor_map <- tm_shape(or_ehsa_joined) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\n  tm_shape(or_ehsa_sig) +\n  tm_fill(\"classification\") + \n  tm_borders(alpha = 0.4) +\n  tm_layout(title = \"Occupancy Rate EHSA\", \n            title.size = 0.4, \n            legend.text.size = 0.4, \n            legend.title.size = 0.4)\n\nft_map <- tm_shape(ft_ehsa_joined) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\n  tm_shape(ft_ehsa_sig) +\n  tm_fill(\"classification\") + \n  tm_borders(alpha = 0.4) +\n  tm_layout(title = \"Foreign Tourist EHSA\", \n            title.size = 0.4, \n            legend.text.size = 0.4, \n            legend.title.size = 0.4)\n\ntmap_arrange(rev_map, or_map, ft_map, ncol = 3)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-142-1.png){width=672}\n:::\n:::\n\n\n**Chonburi** stands out as a consistent hotspot across all variables, indicating strong tourism development and economic benefits.\n\nOther interesting provinces are the following:\n\n1.  **Phang Nga**:\n\n    -   **Revenue**: Identified as a **coldspot**.\n\n    -   **Occupancy Rate**: Identified as a **coldspot**.\n\n    -   **Number of Foreign Tourists**: Identified as a **hotspot**.\n\n    -   **Observation**: While Phang Nga has a significant number of foreign tourists, it is classified as a coldspot for both revenue and occupancy rate. This could suggest that while many foreign tourists visit, their spending is lower compared to other provinces.\n\n2.  **Krabi**:\n\n    -   **Revenue**: Identified as a **coldspot**.\n\n    -   **Occupancy Rate**: Identified as a **coldspot**.\n\n    -   **Number of Foreign Tourists**: Identified as a **hotspot**.\n\n    -   **Observation**: Similar to Phang Nga, Krabi has a high number of foreign tourists but is a coldspot in terms of revenue and occupancy rate, indicating potential issues in capitalizing on foreign tourist visits.\n\n3.  **Bangkok**:\n\n    -   **Revenue**: Identified as a **coldspot**.\n\n    -   **Occupancy Rate**: Identified as a **hotspot**.\n\n    -   **Number of Foreign Tourists**: Identified as a **hotspot**.\n\n    -   **Observation**: Bangkok shows a strong presence in foreign tourists and occupancy rates but is a coldspot in revenue, suggesting a discrepancy between visitor numbers and overall economic impact.\n\n# 7 Conclusion\n\nIn conclusion, this study aimed to explore the spatial and spatio-temporal dependencies of key indicators within Thailand's tourism economy. By preparing comprehensive geospatial data layers at the provincial level, including a dedicated focus on Bangkok, we were able to analyze the relationships between tourism indicators and their geographic contexts. Using various methods from the `sfdep` package, we conducted global and local spatial autocorrelation analyses alongside emerging hotspot detection. The findings revealed significant clusters and outliers in tourism indicators, highlighting regions of high and low economic activity. Notably, Chonburi emerged as a consistent hotspot across revenue, occupancy rates, and foreign tourist numbers, while other provinces, despite their appeal in one economic indicator like number of foreign tourists, exhibited discrepancies in another such as revenue generation. These insights provide a deep understanding of Thailand's tourism dynamics across time and provinces.\n\n------------------------------------------------------------------------\n\n# References\n\nBetgem, F. (n.d.). *Things to do in the Golden Triangle*. Chiang Mai a la Carte. Retrieved October 7, 2024, from <https://www.chiangmai-alacarte.com/chiangmai-alacarte/things-to-do/things-to-do-in-the-golden-triangle/>\n\nCheung, Elizabeth (13 January 2020). [\"Thailand confirms first case of Wuhan virus outside China\"](https://www.scmp.com/news/hong-kong/health-environment/article/3045902/wuhan-pneumonia-thailand-confirms-first-case). *South China Morning Post*. Archived from the original on 13 January 2020. Retrieved 29 September 2024.\n\nTourism Authority of Thailand. (n.d.). *Chon Buri: Destinations & attractions*. Tourism Thailand. Retrieved October 3, 2024, from <https://www.tourismthailand.org/Destinations/Provinces/Chon-Buri/464>\n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}